ory/kratos

.circleci/config.yml, .circleci/release_name.bash, .golangci.yml, Makefile, README.md, doc.go, errorx/manager_test.go, identity/doc.go, identity/identity.go, identity/pool_memory.go, identity/pool_test.go, schema/loader.go, selfservice/handler_test.go, selfservice/oidc/strategy.go, selfservice/oidc/strategy_helper_test.go, selfservice/oidc/strategy_test.go, selfservice/password/extension.go, selfservice/password/validator.go, selfservice/request.go, verify/extension.go, x/cookie_test.go, x/map_json.go
=> Enable Circle CI

selfservice/body_decoder.go, selfservice/body_decoder_test.go, selfservice/oidc/form.go, selfservice/password/registration.go, selfservice/password/registration_test.go
Previously the form parser would try to detect the field type by
asserting types for the whole form. That caused passwords
containing only numbers to fail to unmarshal into a string
value.
This patch resolves that issue by introducing a prefix
option to the BodyParser
Closes #98
=> selfservice: Explicitly whitelist form parser keys

docs/.kratos.yaml, driver/registry_default_hooks.go, persistence/sql/persister_session.go, selfservice/hook/hooks.go, selfservice/hook/session_destroyer.go, selfservice/hook/session_destroyer_test.go, session/persistence.go
=> Optionally allow only one active session per identity 

driver/registry.go, driver/registry_default_hooks.go, driver/registry_default_login.go, driver/registry_default_registration.go, selfservice/hook/session_destroyer.go
=> Separate post register/login hooks

cmd/serve.go, driver/configuration/provider_viper.go, go.mod, selfservice/flow/login/request_method.go, selfservice/flow/profile/request.go, selfservice/flow/registration/request_method.go, selfservice/form/fields.go, selfservice/strategy/password/login.go, selfservice/strategy/password/login_test.go, selfservice/strategy/password/registration.go, selfservice/strategy/password/registration_test.go
closes #178 
The request field will not be added any more. The tests make sure it is not present.
We also check from now on that the form method is always set.
=> Registration/Login HTML form: remove request field and ensure method is set

selfservice/flow/profile/handler.go, selfservice/flow/profile/handler_test.go
=> ss/profile: Use request ID as query param everywhere

cmd/serve.go, courier/courier_test.go, persistence/reference.go, persistence/sql/persister.go, persistence/sql/persister_courier.go, persistence/sql/persister_errorx.go, persistence/sql/persister_identity.go, persistence/sql/persister_login.go, persistence/sql/persister_profile.go, persistence/sql/persister_registration.go, persistence/sql/persister_session.go, persistence/sql/persister_test.go, persistence/sql/persister_transaction_helpers.go, persistence/sql/persister_verify.go
=> refactor(persistence/sql): move connection to context to enable transactions

cmd/daemon/serve.go, courier/courier.go, courier/courier_test.go
Courier would not stop with the provided Background handler.
This changes the methods of Courier so that the graceful package can be
used in the same way as the http endpoints can be used.
#295 
@aeneasr
This adapts the API of courier to match the API of http servers and therefore allows the usage of graceful.
=> fix:add graceful shutdown to courier handler

install.sh
I tried to install on
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
but it failed when I ran  install.sh.
Remove inconsistencies between continuous deployment artfact names and the install script.
=> fix: Linux install script

docs/api.swagger.json, internal/httpclient/client/common/get_self_service_error_parameters.go, selfservice/errorx/handler.go
None
The query parameter for the self-service errors endpoint was named `id` in the API docs, whereas it is the `error` param that is used by the handler.
I regenerated the SDK
=> Fix the query parameter name in the get self-service error endpoint in API docs

identity/address.go
Closes ory/sdk#11
I have marked the field `verified_at` as not required because if a user is not verified then the field must be null. This causes problems when using the Python SDK.
the changes.
works.
Signed-off-by: Jakob Sinclair <sinclair.jakob@mailbox.org>
=> fix: verified_at field should not be required

docs/docs/self-service/flows/user-login-user-registration.md
N/A
- Update links in user-registration-user-login docs to point at current url
- `/auth/browser/(login|registration)` -> `/self-service/browser/flows/requests/(login|registration)`
- Format json blob in same docs to be easier to read:
before:
after:
the changes.
works.
The old links pointed at `/auth/browser/(login|registration)`
which seems to be outdated now.
From the ui node code: https://github.com/ory/kratos-selfservice-ui-node/blob/489c76d1b0474ee55ef56804b28f54d8718747ba/src/routes/auth.ts#L28
and the api documentation for kratos https://www.ory.sh/kratos/docs/reference/api#get-the-request-c …
=> docs: Update self service reg docs

contrib/quickstart/oathkeeper/access-rules.yml
close #389
Fix access rules of oathkeeper for quick start to access `/` as dashboard same as standalone quick start.
the changes.
works.
=> fix: Access rules of oathkeeper for quick start

docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx, docs/sidebar.js
This patch changes the social sign in guide to represent more use cases such as Google and Facebook. Additionally, the example has been updated to work with Jsonnet.
This patch also documents limitations around merging user data from GitHub.
Closes #49
=> docs: improve social sign in guide

persistence/sql/persister_identity.go
Just stumbled across this.
Using the transaction function this way we can call e.g. `CreateIdentity` from within another transaction and it will continue in the context of the outer one.
=> fix: transaction usage in the identity persister

selfservice/flow/registration/request.go
Closes ory/sdk#14
I have marked the field `active` as not required because it is omitted if it not set. This causes problems when using the Python SDK.
the changes.
works.
Signed-off-by: Jakob Sinclair <sinclair.jakob@mailbox.org>
=> fix: active field should not be required

selfservice/flow/settings/hook.go, selfservice/strategy/password/settings_test.go, test/e2e/cypress/integration/profiles/email/settings/success.spec.js
#420
Clear error messages after updating settings successfully.
the changes.
works.
=> fix: Clear error messages after updating settings successfully

docs/docs/self-service/flows/user-login-user-registration.mdx, selfservice/errorx/handler.go, selfservice/flow/login/handler.go, selfservice/flow/registration/handler.go, selfservice/form/fields.go
These are minor fixes for just a few errors in the documentation that I've spotted while learning Kratos. Hope this helps!
* Remove some repeated sentences
* Fix some REST paths
* Fix `<input disabled>`
the changes.
works.
=> docs: minor fixes

selfservice/strategy/password/validator.go, test/e2e/cypress/integration/profiles/email/registration/errors.spec.js
=> fix: Improve grammar of similar password error

selfservice/flow/login/handler_test.go, selfservice/flow/login/request.go, selfservice/flow/settings/error.go, selfservice/strategy/password/login_test.go
Closes #477
BREAKING CHANGE: To refresh a login session it is now required to append `refresh=true` instead of `prompt=login` as the second has implications for revoking an existing issue and might be confusing when used in combination with OpenID Connect.
the changes.
works.
=> refactor: rename prompt=login to refresh=true

.schema/api.swagger.json, internal/httpclient/client/public/initialize_self_service_browser_login_flow_parameters.go, internal/httpclient/models/generic_error_payload.go, selfservice/flow/login/handler.go, selfservice/flow/settings/error.go
=> fix: document login refresh parameter in swagger

.schema/api.swagger.json, docs/docs/concepts/identity-data-model.md, docs/docs/concepts/index.md, docs/docs/concepts/ui-user-interface.md, docs/docs/self-service/flows/user-settings.mdx, docs/docs/self-service/flows/user-settings/change-password.mdx, go.sum, internal/httpclient/models/generic_error_payload.go, internal/httpclient/models/settings_request.go, persistence/sql/README.md, persistence/sql/migrations/20200607165100_settings.down.fizz, persistence/sql/migrations/20200607165100_settings.up.fizz, selfservice/flow/recovery/request.go, selfservice/flow/settings/hook.go, selfservice/flow/settings/request.go, selfservice/flow/settings/state.go, selfservice/flow/settings/strategy_profile_test.go, selfservice/strategy/oidc/strategy_settings_test.go, selfservice/strategy/password/settings_test.go
Closes #449
BREAKING CHANGE: Replaces the `update_successful` field of the settings request
with a field called `state` which can be either `show_form` or `success`.
=> refactor: replace settings update_successful with state

docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx
None
Fixing a small typo
the changes.
works.
Should I have adjusted the file in the 0.3 documentation sub-folder as well?
=> docs: fix typo in oauth sign in documentation

docs/versioned_docs/version-v0.3/sdk.md
the rest api is no longer under sdk but under reference.
=> broken link

docs/docs/concepts/credentials/username-email-password.mdx, docs/versioned_docs/version-v0.1/self-service/strategies/username-email-password.md, docs/versioned_docs/version-v0.2/self-service/strategies/username-email-password.md, docs/versioned_docs/version-v0.3/concepts/credentials/username-email-password.mdx
This is a documentation correction
url: https://www.ory.sh/kratos/docs/concepts/credentials/username-email-password#use-case-username-and-password
**Problem**:
The Username and Password use case example shows an email example instead of a username example.
**Fix**:
This PR renames the `email` to `username` and removes `format` based on the username block in the following use case.
=> docs: Fixed username & password use case example by replacing email with username

docs/docs/guides/zero-trust-iap-proxy-identity-access-proxy.mdx, docs/docs/quickstart.mdx
The docs referenced Mailhog but the quickstart uses MailSlurper.
This PR replaces references to Mailhog with Mailslurper in the latest docs. I did not update the versioned docs as I do not know when Mailhog was actually used.
urls:
- https://www.ory.sh/kratos/docs/quickstart
- https://www.ory.sh/kratos/docs/guides/zero-trust-iap-proxy-identity-access-proxy
=> docs: Replaced mailhog references with mailslurper in current documentation.

quickstart-crdb.yml, quickstart-mysql.yml, quickstart-postgres.yml
All of the databases must exist on the same docker network to allow the main kratos applications to communicate with them.
Fixes the issue described in https://community.ory.sh/t/running-kratos-with-postgres/1908, I've tested them all locally.
the changes.
works.
=> fix: docker-compose quickstart connectivity issues

session/handler.go, session/handler_test.go
We're using the AuthService provided by Ambassador to check if the user is authenticated but right now we're separately calling the whoami again. This means that for every request that a user does we're talking to Kratos twice. By adding the User ID to a header we can prevent this by using the `allowed_authorization_headers` option (see Ambassador doc: https://www.getambassador.io/docs/latest/topics/running/services/auth-service/). 
Set the UserID in a header, I've put it on "X-Authenticated-User" right now.
the changes.
works.
=> feat: Add User ID to a header when calling whoami

.schema/config.schema.json, docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx, go.mod, go.sum, selfservice/strategy/oidc/provider_config.go, selfservice/strategy/oidc/provider_generic_oidc.go, selfservice/strategy/oidc/provider_microsoft.go
This PR adds a new OIDC provider called `microsoft`, that adds support for the multi-tenant features of the Microsoft identity platform. The platform can already be used as an OIDC provider when authenticating towards a specific Tenant - as it behaves as a generic OIDC provider - but when using it to authenticate e.g. with personal Microsoft accounts the endpoints behave in a somewhat special way, described in [this blog post](https://www.cloudidentity.com/blog/2014/08/26/the-common-endpoint-walks-like-a-tenant-talks-like-a-tenant-but-is-not-a-tenant/).
The proposed code differs from the generic OIDC provider by getting the issuer from the returned JWT `id_token`, but subsequently verifies the returned token in the exact same way. It also adds another property in the OIDC provider …
=> feat: Add support for Multitenant Azure AD as an OIDC provider

driver/registry.go, driver/registry_test.go
The configuration shortcut `dsn="memory"` was not recognize correctly. This PR fixes the check for SQLite memory mode and extracts the test into a function and adds a test for the function.
the changes.
works.
=> fix: detection of SQLite memory mode

.schema/config.schema.json
Kratos requires `selfservice.default_browser_return_url` to be set but this was not reflected in the config schema.
=> fix: require selfservice.default_browser_return_url to be set in config

driver/driver_default_test.go, identity/manager_test.go, identity/pool.go, identity/stub/manager.schema.json, persistence/sql/persister_identity.go, selfservice/strategy/oidc/provider_microsoft.go, x/maxitems.go
=> feat: add tests and helpers to test recovery/verifiable addresses

selfservice/strategy/password/validator.go, selfservice/strategy/password/validator_test.go
closes #581 
Whether the longest common substring is too long is now relative to the length of the password.
=> fix: password validator uses relative threshold to judge longest common substring

identity/handler.go, identity/handler_test.go, identity/manager.go, identity/manager_test.go, identity/stub/handler/customer.schema.json, identity/stub/handler/employee.schema.json, internal/testhelpers/identity_schema.go, selfservice/flow/settings/hook.go
This patch resolves several issues that occurred when creating or updating identities using the Admin API. Now, all hooks are running properly and updating privileged properties no longer causes errors.
Closes #435
See #500
=> fix: resolve identity admin api issues 

driver/configuration/provider_viper.go, driver/configuration/provider_viper_test.go, internal/httpclient/client/admin/create_identity_responses.go, internal/httpclient/client/admin/delete_identity_responses.go, internal/httpclient/client/admin/get_identity_responses.go, internal/httpclient/client/admin/list_identities_responses.go, internal/httpclient/client/admin/update_identity_responses.go, internal/httpclient/client/common/get_schema_responses.go, internal/httpclient/client/common/get_self_service_browser_login_request_responses.go, internal/httpclient/client/common/get_self_service_browser_recovery_request_responses.go, internal/httpclient/client/common/get_self_service_browser_registration_request_responses.go, internal/httpclient/client/common/get_self_service_browser_settings_request_responses.go, internal/httpclient/client/common/get_self_service_error_responses.go, internal/httpclient/client/common/get_self_service_verification_request_responses.go, internal/httpclient/client/health/is_instance_alive_responses.go, internal/httpclient/client/health/is_instance_ready_responses.go, internal/httpclient/client/public/complete_self_service_browser_recovery_link_strategy_flow_responses.go, internal/httpclient/client/public/complete_self_service_browser_settings_o_id_c_settings_flow_responses.go, internal/httpclient/client/public/complete_self_service_browser_settings_password_strategy_flow_responses.go, internal/httpclient/client/public/complete_self_service_browser_settings_profile_strategy_flow_responses.go, internal/httpclient/client/public/complete_self_service_browser_verification_flow_responses.go, internal/httpclient/client/public/initialize_self_service_browser_login_flow_responses.go, internal/httpclient/client/public/initialize_self_service_browser_logout_flow_responses.go, internal/httpclient/client/public/initialize_self_service_browser_registration_flow_responses.go, internal/httpclient/client/public/initialize_self_service_browser_verification_flow_responses.go, internal/httpclient/client/public/initialize_self_service_recovery_flow_responses.go, internal/httpclient/client/public/initialize_self_service_settings_flow_responses.go, internal/httpclient/client/public/self_service_browser_verify_responses.go, internal/httpclient/client/public/whoami_responses.go, internal/httpclient/client/version/get_version_responses.go
When `selfservice.flows.logout.after.default_browser_return_url` was not set a logout resulted in a fatal crash.
The fallback now is `selfservice.default_browser_return_url`
the changes.
works.
=> fix: fallback to default return url if logout after url is not defined

cmd/daemon/serve.go, driver/configuration/provider_viper.go, driver/registry.go
It looks like the tracer is declared but not used even if one is allowed to set env vars to activate and configure it.
I just added it as a negroni middleware, exactly like it's already done on oathkeeper.
the changes.
works.
=> feat: add the already declared (and settable) tracer as a middleware

.circleci/config.yml
=> ci: improve e2e cache keys

courier/courier.go
As discussed with @aeneasr via email.
Previously there was no way to use smtps to send email without adding `?skip_ssl_verify=true` to the end of the courier.smtp.connection_uri. In practice this means that anyone with the ability to poison DNS records (for any kratos installation that supports password reset emails) will be able to register an ssl certificate for any-old-domain and receive all password reset emails (since there is no way to configure kratos to verify the ssl server name for the email provider).
> thank you for the disclosure! Given that misconfiguration results in an error (or enforces TLS verification skipping which results in raised eyebrows :) ) I would not classify this as a security vulnerability. Hence, it is ok (and encouraged) to just open a public PR for this. …
=> fix: tell tls what the smtps server name is

.schema/config.schema.json, contrib/quickstart/kratos/email-password/kratos.yml, x/http_secure_redirect_test.go
Currently ui_url for each of the flows is a `uri`. This means that we have to generate a new config file for each developer's cluster, and another one for production as they are each served from a different domain.
We are hosting kratos and our webserver behind an nginx proxy, so specifying a relative uri like `/auth/login` would solve this problem for us..
How do people feel about allowing relative urls like `/auth/login` to be specified as the ui_urls? If nobody can think of a security reason against this, I will happily continue with this PR, as it would save us a bunch of hassle generating config files.
[security@ory.sh](mailto:security@ory.sh)) from the …
=> feat: use uri-reference for ui_url etc. to allow relative urls

docs/docs/admin/managing-users-identities.mdx
I was talking to aeneas in #kratos and he pointed out that this endpoint was recently merged. I tried it out on my own infrastructure and noticed that the url was wrong https://github.com/FutureNHS/futurenhs-platform/pull/103/files ( infrastructure/scripts/new-kratos-user.sh )
=> docs: fix url of admin-api /recovery/link

.github/workflows/closed_references.yml
This adds our https://github.com/ory/closed-reference-notifier GitHub action. It runs every day at 7am.
When running locally it found the following references, which seems legit to me (not all are closed):
```
Found reference "github.com/ory/x/issues/169" in file driver/configuration/provider_viper.go
Found reference "github.com/gobuffalo/pop/issues/574" in file persistence/sql/persister.go
Found reference "github.com/gobuffalo/pop/issues/574" in file persistence/sql/persister.go
Found reference "github.com/gobuffalo/pop/pull/481" in file persistence/sql/persister_test.go
Found reference "github.com/ory/kratos/issues/347" in file test/schema/schema_test.go
Found reference "github.com/gobuffalo/pop/issues/538" in file persistence/sql/migratest/migration_test.go
Found reference …
```
=> ci: add closed reference notifier action

.github/workflows/closed_references.yml
The manual trigger will allow us to confirm the creation of more than 5 issues. I tested the `||` operator works as in JS in another repo.
=> ci: bump closed reference notifier and add manual trigger

.schema/api.swagger.json, .schema/config.schema.json, contrib/quickstart/kratos/email-password/kratos.yml, docs/docs/reference/configuration.md, driver/configuration/provider_viper.go, driver/configuration/stub/.defaults-verification.yml, internal/.kratos.yaml, internal/httpclient/client/admin/admin_client.go, internal/httpclient/client/admin/create_recovery_link_responses.go, selfservice/strategy/recoverytoken/strategy.go, test/e2e/profiles/recovery/.kratos.yml, test/e2e/profiles/verification/.kratos.yml, test/schema/fixtures/config.schema.test.failure/wrongTypes.main.yaml, test/schema/fixtures/config.schema.test.success/allKeys.main.yaml
BREAKING CHANGE: Configuration option request_lifespan changed to lifespan
Closes #666 
Rename `request_lifespan` to `lifespan`
the changes.
works.
Maybe, all occurrences of the "RequestLifespan" in function names should also be replaced with "Lifespan".
=> refactor(config): rename request_lifespan to lifespan #666

docs/docs/quickstart.mdx
Added a section outlining some easy config changes, that users can apply to the quickstart to test out different scenarios and configurations. 
__Motivation__ for this appendix was, that several of these came up often in discussions with users on slack or the forum, and this would be a place where they can find it quickly and easily. 
Please correct me, where I was wrong or if there was a different place this sort of information would be better suited.
the changes.
works.
=> docs: quickstart next steps

selfservice/form/html_form.go, selfservice/strategy/password/registration.go, selfservice/strategy/password/registration_test.go, selfservice/strategy/password/stub/profile.schema.json
closes #670
Only set the value and not the whole field when generating the registration form with error messages.
=> fix: keep HTML form type on registration error

.schema/api.swagger.json, docs/docs/reference/api.mdx, docs/docs/reference/configuration.md, internal/httpclient/models/login_via_api_response.go, internal/httpclient/models/registration_via_api_response.go, selfservice/flow/login/session.go, selfservice/flow/registration/session.go
=> fix: escape jsx characters in api documentation

.github/workflows/closed_references.yml, README.md, docs/docs/contributing.md
Updated repository templates to https://github.com/ory/meta/commit/92ae8b93c03738d00573f229a412f9eac7a71a99.
=> chore: update repository template to 92ae8b93

.schema/api.swagger.json, internal/httpclient/models/recovery_flow_method.go, internal/httpclient/models/registration_flow_method.go, internal/httpclient/models/settings_flow_method.go, internal/httpclient/models/verification_flow_method.go, selfservice/flow/recovery/flow_method.go, selfservice/flow/registration/flow_method.go, selfservice/flow/settings/flow_method.go, selfservice/flow/verification/flow_method.go, selfservice/strategy/oidc/strategy_settings_test.go
=> fix: mark flow methods' fields as required

Makefile
no related issue
Fix misspelled Make keyword `.PHONE` to `.PHONY` to match the rest of the document.
the changes.
works.
I noticed this bug while working on #567. Extracting this into a separate pull request since it is an unrelated change that should be discussed and shipped separately.
=> docs: Fix PHONY spelling

README.md
Contractions (shortening "who is" to "who's") are very informal and typically only used in oral language. I think written documentation can be casual but should maintain a written style.
the changes.
works.
=> docs: Remove contraction

package-lock.json, package.json
Add `ory-prettier-styles` to main repo so that `npm run format` works there.
the changes.
works.
=> fix: Add ory-prettier-styles to main repo

README.md
The TOC in this file is outdated. Are you still using doctoc as the comments in various MD files indicate? It's not included in `package.json`. Setting it up seems not straightforward since it adds TOCs everywhere so I wanted to check in about this first before hacking on this.
the changes.
works.
=> docs: Add missing TOC entries

README.md
Replace `&` with `and` since "identity and access proxy" reads better than "identity & access proxy" to me. This is an extract from #567, it makes sense to discuss this separately. Not feeling strongly about this. If the `&` is part of the branding we can leave it in.
the changes.
works.
=> docs: Replace ampersand

docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx
Adds a guide to setup twitch as an oidc provider
the changes.
works.
=> docs: adds twitch oidc provider guide

selfservice/strategy/oidc/provider_config.go
Adds gitlab to list of supported providers in error message.
the changes.
works.
=> fix: adds missing gitlab to list of supported oidc providers

contrib/quickstart/oathkeeper/access-rules.yml
closes #762 
Change contrib/oathkeeper/access-rules.yml on line 24
```
-
id: "ory:kratos-selfservice-ui-node:anonymous"
upstream:
preserve_host: true
url: "http://kratos-selfservice-ui-node:4435"
match:
url: "http://127.0.0.1:4455/<{error,verify,auth/*,**.css,**.js}{/,}>" # add 'recovery' here
...
```
the changes.
works.
=> fix: fixed missing 'recovery' path in oathkeeper access-rules.yml

docs/docs/contributing.md
Updated repository templates to https://github.com/ory/meta/commit/ca7946dd99da07241afd45e1e6a7a831b5b13e32.
=> chore: update repository template to ca7946dd

.schema/config.schema.json, docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx, go.mod, go.sum, selfservice/strategy/oidc/provider_config.go, selfservice/strategy/oidc/provider_discord.go
Closes #533 
Closes #534 
Adds discord as an oidc provider. This is a continuation of the stale PR #534.
the changes.
works.
I will improve the documentation with further direct code references once we have a final commit id or release.
=> feat: adds discord oidc provider

docs/versioned_docs/version-v0.5/concepts/terminology.mdx
Fixed spelling mistake
the changes.
works.
=> docs: fixed spelling mistake on terminology documentation

docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx
* Adds reference to where the claims struct is built
* Removes statement that `iss` claim is added by `email` scope. It is only be added by the `identify` scope
* Makes it more clear that the `email` scope is an addition to the `identify` scope. `email` does not work / has no function without `identify`
the changes.
works.
=> docs: small improvements to discord oidc provider guide

docs/docs/self-service/flows/account-recovery.mdx, docs/docs/self-service/flows/user-login.mdx, docs/docs/self-service/flows/user-registration.mdx, docs/docs/self-service/flows/user-settings.mdx, docs/docs/self-service/flows/verify-email-account-activation.mdx, docs/versioned_docs/version-v0.5/self-service/flows/account-recovery.mdx, docs/versioned_docs/version-v0.5/self-service/flows/user-login.mdx, docs/versioned_docs/version-v0.5/self-service/flows/user-registration.mdx, docs/versioned_docs/version-v0.5/self-service/flows/user-settings.mdx, docs/versioned_docs/version-v0.5/self-service/flows/verify-email-account-activation.mdx
None.
Trivial documentation fix: Use correct syntax for `info` [docosaurus admonitions](https://v2.docusaurus.io/docs/markdown-features/#calloutsadmonitions)
the changes.
works.
None.
=> Fix docosaurus admonitions

selfservice/flow/settings/handler.go
None.
Fixes a spelling error in the selfservice settings handler method `fetchPublicFlow`. This method is not part of any interface, thus I _guess_ that it is private (i.e., not exposed to anything outside the file).
the changes.
works.
None.
=> fix: case in settings handler method

docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx, docs/versioned_docs/version-v0.5/guides/sign-in-with-github-google-facebook-linkedin.mdx
None
It looks like some of the docs for the oidc login method still reflect url patterns and `yaml` structure used before 89851896 and 9369d1bb
Update those docs to match the code.
the changes.
works.
None
=> docs: fix oidc config examples

docs/docs/guides/setting-up-password-hashing-parameters.md
CI docs build failing on master
=> docs: fix broken relative markdown link

docs/sidebar.json, docs/versioned_sidebars/version-v0.5-sidebars.json
There was a leftover category in the sidebar from old CLI docs generation.
=> docs: remove leftover category from reference sidebar

.schema/api.swagger.json, selfservice/flow/settings/handler.go
Closes https://github.com/ory/sdk/issues/43
the changes.
works.
=> fix: swagger specs for settings api's browser flow

x/nosurf.go
https://github.com/ory/kratos/issues/821
This PR will set the SameSite attribute to Lax if ran in dev mode.
the changes.
works.
This lacks tests. Help with those would be appreciated.
=> fix: set samesite attribute to lax if in dev mode

session/handler.go
#838 
Exempt the Revoke Session endpoint from requiring a CSRF token.
the changes.
works.
I followed the example of the `RouteWhoami` CSRF exemption in `session/handler.go`.
My go skills need some work, so any recommendations on tests or whatever would be welcome. :smile:
=> fix: CSRF token is required when using the Revoke Session API endpoint

docs/docs/concepts/credentials/username-email-password.mdx
Typo on the Username / Email & Password credentials docs page.
the changes.
works.
=> docs: fix typo

CONTRIBUTING.md, README.md, docs/docs/contributing.md
Updated repository templates to https://github.com/ory/meta/commit/781e8fb26afe90cedb50a939ad3fb6fa3798eefd.
=> chore: update repository template to 781e8fb2

docs/docs/contributing.md
Updated repository templates to https://github.com/ory/meta/commit/8042a8da0b42c9ff50deb9860249f95c756af18f.
=> chore: update repository template to 8042a8da

x/nocache.go
#601 
Cache-control: 0 has, to my understanding, no specific meaning, and in the case of using a CDN such as CloudFront, doesn't actually limit caching of values - this leads to re-use of CSRF cookies and flow session ID's.
Using a more-specific set of cache-control directives prevents CloudFront from caching the result of those URL's that explicitly want no caching, including CDN's.
the changes.
works.
I've worked around this by setting up a specific non-caching behavior for ORY Kratos url's, but the patch above should work across CDN's and caching proxies.
=> Use working cache-control header for cdn/proxies/cache

selfservice/flow/login/flow.go, selfservice/flow/login/flow_method.go, selfservice/flow/recovery/flow.go, selfservice/flow/recovery/flow_method.go, selfservice/flow/registration/flow.go, selfservice/flow/registration/flow_method.go, selfservice/flow/settings/flow.go, selfservice/flow/settings/flow_method.go, selfservice/flow/verification/flow.go, selfservice/flow/verification/flow_method.go
Closes #716
the changes.
works.
=> fix: remove obsolete types

docs/versioned_docs/version-v0.5/guides/docker.md
No issue, I was just reading the doc and took the initiative to fix wrong code section
the changes.
works.
=> fix: :memo: quickfix ory home directory path in section docker of the documentation

.github/ISSUE_TEMPLATE/config.yml, CONTRIBUTING.md, docs/docs/contributing.md, docs/sidebar.json
Updated repository templates to https://github.com/ory/meta/commit/3193a1c149e88bd322dde3e813f2ada23b32709d.
=> chore: update repository template to 3193a1c1

docs/versioned_docs/version-v0.5/guides/sign-in-with-github-google-facebook-linkedin.mdx
This fixes a mistake in formatting for the documentation for third party logins, introduced in commit 62b4d63. A `:::note` block encapsulated more content than it was supposed to and thus altered the structure of the document.
the changes.
works.
=> docs: fix note block in third party login guide

docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx
The :::note::: consumed the whole rest of the page.
The build is failing because of the sidebar.json issue I mentioned in Slack.
the changes.
works.
=> docs: fix formatting

.circleci/config.yml, docs/sidebar.json, go.sum, internal/httpclient/go.mod, internal/httpclient/go.sum
Workaround for https://github.com/sonatype-nexus-community/nancy/issues/207
Use `sed` to remove the local rewrite. The dependencies of `./internal/httpclient` are included in `go list -m all` anyway (at least it looks like that when I compare the output locally).
As this is quite a special situation here in Kratos, I did not bother adding an option to the nancy pod. But we will have to do that when we consume the other the project's CLIs externally.
=> ci: fix nancy check by stripping the local rewrite

cmd/identities/import.go, docs/docs/reference/api.mdx, docs/versioned_docs/version-v0.5/admin/managing-users-identities.mdx
No related issue
The import identities command documentation was hard to understand since there were no example credential files. There were also no references to the import identities command in the managing user identities documentation.
the changes.
works.
=> Import identities documentation improvements

docs/docs/self-service/flows/user-login.mdx
No related issue, minor fix in the documentation.
Fixes an incorrect link in the infobox at the top on https://www.ory.sh/kratos/docs/self-service/flows/user-login/
the changes.
works.
no further comments, have a great day everybody!
=> docs: fix link to Self-Service Flows overview

cmd/identities/definitions.go, docs/docs/sdk.md, selfservice/strategy/link/strategy_recovery_test.go, selfservice/strategy/oidc/strategy_settings_test.go, selfservice/strategy/profile/strategy_test.go
Fixes #1018
- Changes `string(i.ID)` to `string(*i.ID)` in `cmd/identities/definitions.go`
- Fixes breaking CI tests where pointer types are being compared to string types.
- Autoformat docs to fix prettier in CI
the changes.
works.
Traced backwards and noticed that if the redirect for `github.com/ory/kratos-client-go` wasn't used it's working fine. Noticed that the redirect to https://github.com/ory/kratos/blob/master/internal/httpclient/models/identity.go changes it to a `*UUID` instead of a `UUID` here https://github.com/ory/kratos-client-go/blob/master/models/identity.go.
Dereferencing the `ID` …
=> fix: dereference pointer types from new flow structures

cmd/daemon/serve.go
Currently, the Prometheus metrics middleware is only used on the Admin API. This PR adds it to the Public API, so that Public API requests may be monitored, as well.
the changes.
works.
=> feat: Add Prometheus monitoring to Public API

driver/registry_default.go, driver/registry_default_recovery.go, driver/registry_default_settings.go, driver/registry_default_test.go, selfservice/strategy/handler.go, selfservice/strategy/link/strategy.go, selfservice/strategy/link/strategy_recovery.go, selfservice/strategy/link/strategy_recovery_test.go, selfservice/strategy/oidc/strategy.go, selfservice/strategy/oidc/strategy_settings.go, selfservice/strategy/oidc/strategy_settings_test.go, selfservice/strategy/oidc/strategy_test.go, selfservice/strategy/password/login.go, selfservice/strategy/password/registration.go, selfservice/strategy/password/settings.go, selfservice/strategy/password/strategy_test.go, selfservice/strategy/profile/strategy.go, selfservice/strategy/profile/strategy_test.go
#954 
Return 400 with message `This endpoint was disabled by system administrator. Please check your url or contact the system administrator to enable it.` when user requests endpoints belonging to disabled methods. 
the changes.
works.
=> fix: give specific message instead of only 404 when method disabled

docs/docs/admin/managing-users-identities.mdx, docs/docs/debug/csrf.mdx, docs/versioned_docs/version-v0.5/admin/managing-users-identities.mdx
=> docs: fix broken link

.schema/config.schema.json, docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx, selfservice/strategy/oidc/provider_config.go, selfservice/strategy/oidc/provider_facebook.go
https://github.com/ory/kratos/issues/1034
- Adds provider_facebook.go and updates the configuration schema to allow for facebook as an OIDC provider
- Adds description to documentation
the changes.
works.
=> feat: add facebook provider to oidc providers and documentation

courier/courier.go, courier/message.go, courier/persistence.go, persistence/sql/persister_courier.go, selfservice/strategy/link/sender_test.go
~~#402~~ #652, #732 
Fixes the courier message dequeuing race condition by modifying `*sql.Persister.NextMessages(ctx context.Context, limit uint8)` to retrieve only messages with status `MessageStatusQueued` and update the status of the retrieved messages to `MessageStatusProcessing` within a transaction. On message send failure, the message's status is reset to `MessageStatusQueued`, so that the message can be dequeued in a subsequent `NextMessages` call. On message send success, the status is updated to `MessageStatusSent` (no change there).
the changes.
works.
I updated the existing message …
=> fix: Courier message dequeuing race condition

driver/config/config.go, driver/config/config_test.go
#1032 @aeneasr 
Lots of hybrid applications that are built with [electron](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#blank-screen-on-builds-but-works-fine-on-serve), cordova, capacitor, etc. use hash-based routing. When we use URLs with a hash mark ([fragment](https://en.wikipedia.org/wiki/URI_fragment)), Kratos replaced it with `%23` because [ParseRequestURI](https://golang.org/pkg/net/url/#ParseRequestURI) assumed that URL dows not to have a #fragment suffix (see docs). [Parse](https://golang.org/pkg/net/url/#Parse) function parse URL correctly with #fragment.
- [x ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x ] I have read the [security policy](../security/policy).
- [x ] I confirm that this pull request does …
=> fix: Hashtag in url converts to %23

CONTRIBUTING.md, README.md, docs/docs/contributing.md
Updated repository templates to https://github.com/ory/meta/commit/9c9e465a1a1c06e4fe353464672c9069f1f11f49.
=> chore: update repository template to 9c9e465a

cmd/courier/watch_test.go
#652 #732
Following the discussion in #1024, this PR defines a new `kratos courier watch` command which runs the message courier in the foreground, as well as disabling the background courier by default when `kratos serve` is executed. 
The `--watch-courier` flag can be passed to the `serve` command to execute the courier in the background as is the current behavior.
the changes.
works.
=> feat: Courier foreground worker with "kratos courier watch"

cmd/courier/watch_test.go, driver/config/config.go, driver/config/config_test.go, go.mod, go.sum
#1040 added a check to disallow the empty host name on URLs. This is required though for absolute file URLs to work.
Allow empty host in URLs (just as before #1040)
I had to replace the mogodb driver because they somehow released a version twice... https://jira.mongodb.org/browse/GODRIVER-1851
=> fix: allow absolute file URLs as config values

docs/versioned_docs/version-v0.5/debug/performance-out-of-memory-password-hashing-argon2.md
blog post link fixed in versioned docs 0.5
=> docs: fix link

docs/.gitignore
With 
```
src/theme/faq.module.gen.css
docs/faq.mdx
```
in gitignore the FAQ is not committed when building the docs. 
This reverts this change.
the changes.
works.
=> fix: revert gitignore

courier/courier.go, courier/courier_test.go, driver/config/.schema/config.schema.json, driver/config/config.go
Currently, there is no way to configure Email `from` name for Kratos. 
By checking  [ory/mail's source code](https://github.com/ory/mail/blob/e6b733ef914946a8c48b5c81a451c5277d0da0bc/message.go#L133), I am convinced that Kratos is equipped with the ability to handle [RFC-5322](https://tools.ietf.org/html/rfc5322#section-3.4) `mailbox` format. 
This PR introduces a new optional `from_name` properties under `smtp.from_name`.
the changes.
works.
If this looks alright, I am happy to raise another PR to update doc or just do it as part of this change too.
=> feat: Allow specifying Sender Name in smtp.from_address

.docker/Dockerfile-build
Remove call to `make pack` in Dockerfile after it was removed from the Makefile.
the changes.
works.
=> fix: remove absolete 'make pack' from Dockerfile

.golangci.yml
The linter was not enabled and thus not checking the formatting on PRs.
Enable goimports in golangci-lint
=> chore: enable goimports linter

courier/courier.go, x/pagination.go
In some cases we had a wrong bitsize of `64`, while the var was later cast to `int`.
Replaced with a bitsize of `0`, which is the value to cast to `int`.
[3 fixed alerts :tada:](https://github.com/ory/kratos/pull/1178/checks?check_run_id=2208117918)
=> fix: integer parsing bit size

docs/docs/concepts/docker.md, docs/docs/guides/docker.md, docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx, docs/docs/quickstart.mdx, docs/versioned_docs/version-v0.3/guides/sign-in-with-github-google-facebook-linkedin.mdx, docs/versioned_docs/version-v0.4/guides/sign-in-with-github-google-facebook-linkedin.mdx, docs/versioned_docs/version-v0.4/quickstart.mdx, docs/versioned_docs/version-v0.5/guides/docker.md, docs/versioned_docs/version-v0.5/guides/sign-in-with-github-google-facebook-linkedin.mdx, docs/versioned_docs/version-v0.5/quickstart.mdx
The Quickstart documentation have broken links in then, this fixes them.
The file `.kratos.yml` have changed name to `kratos.yml` and the lines references have changed. 
vulnerability. [...]
works.
=> docs: Docker file links

docs/docs/guides/zero-trust-iap-proxy-identity-access-proxy.mdx, docs/docs/quickstart.mdx, docs/versioned_docs/version-v0.1/quickstart.mdx, docs/versioned_docs/version-v0.2/guides/zero-trust-iap-proxy-identity-access-proxy.md, docs/versioned_docs/version-v0.2/quickstart.mdx, docs/versioned_docs/version-v0.3/guides/zero-trust-iap-proxy-identity-access-proxy.md, docs/versioned_docs/version-v0.3/quickstart.mdx, docs/versioned_docs/version-v0.4/guides/zero-trust-iap-proxy-identity-access-proxy.mdx, docs/versioned_docs/version-v0.4/quickstart.mdx, docs/versioned_docs/version-v0.5/guides/zero-trust-iap-proxy-identity-access-proxy.mdx, docs/versioned_docs/version-v0.5/quickstart.mdx
The `docker pull` command pulls the wrong images as they are not used in the quickstart (uses e.g. oryd/kratos:v0.5.5-alpha.1.pre.1-sqlite tag). The quickstart still works, even though pulling the wrong images, as the docker-compose command itself automatically pulls the images from docker. Therefore the `docker pull` command can be omitted.
=> docs: Remove unnecessary and wrong docker pull commands

docs/docs/self-service/flows/account-recovery.mdx, docs/versioned_docs/version-v0.5/self-service/flows/account-recovery.mdx
Fix the docs/screenshot about the emails sent when performing account recovery
the changes.
works.
=> docs: fix known/unknown email account recovery

go.mod, go.sum, selfservice/strategy/link/strategy_recovery.go, x/http_secure_redirect_test.go
https://github.com/ory/kratos/issues/1188
@aeneasr 
Specify option to output JSON without escaping HTML entities, to keep the `&` in the query string intact.
the changes.
works.
Tested manually using cURL, but I'm not sure about the best way to add automatic tests for this.
I ran `go get github.com/ory/herodot@v0.9.5` `go mod tidy`, which led to the changes in `go.mod` and `go.sum`.
=> fix: Avoid unicode-escaping ampersand in recovery URL query string

docs/versioned_docs/version-v0.5/reference/configuration.md, driver/config/.schema/config.schema.json
Add one line to the config docs to mention the ID of the default schema. This is useful for using the schema/{id} API. It is not mentioned anywhere else in the docs.
- [x ] I have read the [security policy](../security/policy).
- [x ] I confirm that this pull request does not address a security
the changes.
- [x ] I have added tests that prove my fix is effective or that my feature
works.
- [x ] I have added or changed [the documentation](docs/docs).
=> Make explicit the ID of the default schema

session/handler.go, spec/swagger.json
I believe this resolves #1215; for the `whoami` endpoint, the Authorization string was included as 'query' parameter in the OpenAPI spec as the used 'in' location was not valid. As a result, generated API clients pass the authorization to Kratos via a query param, which is not supported.
PR includes a small patch to change the location from 'query' to 'header', which should let users generate a working API client from the spec.
the changes.
works.
Regenerating the specification via `make` resulted in a number of unrelated changes for me, which I've not included in this PR for brevity.
=> fix: marking whoami auhorization parameter as 'in header'

docs/docs/self-service/flows/code/login/index.js, docs/docs/self-service/flows/code/recovery/index.js, docs/docs/self-service/flows/code/registration/index.js, docs/docs/self-service/flows/code/settings/index.js, docs/docs/self-service/flows/code/verification/index.js, docs/versioned_docs/version-v0.5/self-service/flows/code/login/index.js, docs/versioned_docs/version-v0.5/self-service/flows/code/recovery/index.js, docs/versioned_docs/version-v0.5/self-service/flows/code/registration/index.js, docs/versioned_docs/version-v0.5/self-service/flows/code/settings/index.js, docs/versioned_docs/version-v0.5/self-service/flows/code/verification/index.js
Fix tab labels in self-service code flows documentation.
The labels `Angular` and `ExpressJS` are interchanged: [Example in docs](https://www.ory.sh/kratos/docs/self-service/#initialization-and-redirect-to-ui)
the changes.
works.
=> docs: fix self-service code flows labels

courier/template/load_template_test.go
Dependency "github.com/shurcooL/go/ioutil" no longer exists. It's replaced with "os", in this case.
the changes.
works.
=> fix: replace broken dependency in test

cmd/identities/validate.go
=> fix: use correct openapi path for validation

.circleci/config.yml, .schema/version.schema.json
Closes #1331 
Closes #1101 
This fixes the config schema paths in the version.schema.json to reflect the new path since we use go embed.
See also https://github.com/ory/hydra/pull/2427
The CI was also updated to include the new schema path.
=> fix: version schema

identity/credentials.go, identity/identity.go, identity/identity_test.go, internal/httpclient/api/openapi.yaml, internal/httpclient/docs/Identity.md, internal/httpclient/model_identity.go, spec/openapi.json, spec/swagger.json
#820
the changes.
works.
This is a simple attempt to add the information of the last changed date to the admin api for "get identity".
I'd like to see what you think about it.
=> feat: Include Credentials Metadata in admin api.

docs/versioned_docs/version-v0.6/guides/docker.md
Fixes doc typo in which files are suggested to be copied to `/ory/home` instead of `/home/ory`.
=> docs: Fix incorrect command

docs/docs/concepts/ui-user-interface.md, docs/versioned_docs/version-v0.6/concepts/ui-user-interface.md
I think it should mean 'password' instead of 'assword', shouldn't it?
the changes.
works.
=> docs: Fixes typo in "Sign in/up with ID & assword"

corp/context.go, corp/noop.go
First part of #1363 
Refactor the `corp` package/module to allow an easier override of the `Contextualize*` functions.
Once this is merged, you can update your own build pipeline to overwrite `corp.DefaultContextualizer` in some `init` function.
After that the `corp/go.{mod,sum}` files can be removed, as well as the `replace` directive in `go.mod`.
This will then ease building kratos from other packages (see #1363 for details).
=> refactor: introduce DefaultContextualizer in corp package

docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx, driver/config/.schema/config.schema.json, go.mod, selfservice/strategy/oidc/provider_config.go, selfservice/strategy/oidc/provider_vk.go, selfservice/strategy/oidc/provider_yandex.go
#1234
- Adds provider_vk.go and updates the configuration schema to allow for vk as an OIDC provider
- Adds provider_yandex.go and updates the configuration schema to allow for yandex as an OIDC provider
- Adds description to documentation
the changes.
works.
=> feat: add vk and yandex providers to oidc providers and documentation

docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx, docs/versioned_docs/version-v0.6/guides/sign-in-with-github-google-facebook-linkedin.mdx, selfservice/strategy/oidc/provider.go, selfservice/strategy/oidc/provider_slack.go
I did name the property in the Claims struct Team, although I can see it being called something more generic like OrganizationId since Team may be a specific Slack term, but some generic organization seems like something that will be present in many other OAuth providers.
Closes #1408
#1408
Reasoning behind this change described in the related issue. Basically it's a small change to include the team ID user belongs to in the Slack OIDC provider response so it's usable information in the hooks
the changes.
works.
=> feat: Team id in slack oidc

docs/package-lock.json, selfservice/strategy/oidc/strategy.go, selfservice/strategy/oidc/types.go, test/e2e/cypress/integration/profiles/oidc/registration/success.spec.js, text/message_registration.go
When signing up with an OIDC provider and the traits model is missing some fields, the submit button shows all OIDC options. Instead, it should show just one option called "Continue".
Closes #1422
Closes #1320
the changes.
works.
=> fix: continue button for oidc registration step

driver/config/.schema/config.schema.json
#1435
SMTP validation requires the connection string to be a valid URI, however, AWS SES adds invalid characters to the password, failing validation
the changes.
works.
We match against `SMTP://` or `SMTPS://` plus a valid string after.
=> fix: change SMTP config validation from URI to a Regex pattern

.docker/Dockerfile-build
`make quickstart-dev` doesn't work anymore, because of an obsolete ADD statement in the Dockerfile:
```sh
Step 6/23 : ADD internal/httpclient/go.* internal/httpclient/
---> Using cache
---> 9c824cb98053
Step 7/23 : ADD corp/go.* corp/
ADD failed: no source files were specified
make: *** [/home/nick/GolandProjects/github/ory/kratos/Makefile:113: quickstart-dev] Error 1
```
Removal of the ADD statement for the no longer existing `corp` module. Breaking change occurred here with the deletion of module files: 0202dc57aacc0d48e4c1ee4e68c91654451f63fa
the changes.
works.
=> fix: remove obsolete ADD for corp module

README.md, docs/docs/CHANGELOG.md
Updated repository templates to https://github.com/ory/meta/commit/261aeeaa11d4ac53571fac1c7ff941cf272115a1.
=> chore: update repository template to 261aeeaa

.schema/version.schema.json
schema URLs for pre-release tags will not resolve as the tags get deleted after release. removing this version to avoid IDE/tooling errors when validating a `kratos.json` config file.
resolves ory/kratos#1485
See discussion with @zepatrik and @aeneasr at #1485
- [x ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x ] I am following the
- [x ] I have read the [security policy](../security/policy).
- [x ] I confirm that this pull request does not address a security
the changes.
works.
=> fix: remove v0.5.3-alpha.1.pre.0 from version schema

x/clean_url_test.go, x/doc.go, x/nosurf_test.go
The x package name is neither very descriptive nor has comment
describing what the package is. This addresses the latter.
Also fix two staticcheck warnings by doing minor restructuring of
two tests.
=> refactor: Cleanup lint errors and add docstring to x

persistence/sql/persister_identity.go
This change should improve the `/identities` endpoint performance. Right now it uses `Eager()` method to load identity model associations n times (where n is the number of identities fetched per request, default is 100). This causes 100+1 SQL queries. It is a tradeoff between memory and speed/queries. I found out that on our setup (yes, our DEV DB have significant lag due to some infrastructure setup but it is not crazy high ~100ms which can happen in some low tier setups as well).
Currently queries looks like this:
```sql
SELECT * FROM identities LIMIT, OFFSET;
SELECT * FROM identity_verifiable_addresses WHERE identity_id = id1;
SELECT * FROM identity_verifiable_addresses WHERE identity_id = id2;
SELECT * FROM identity_verifiable_addresses WHERE identity_id = id3;
...
SELECT * FROM …
```
=> fix: list identities tuning

cmd/hashers/root.go
All `kratos hashers *` cli commands were not registered properly due to creation of two hashers cmd instances.
the changes.
works.
=> fix: argon2 cli commands not registering

.schema/openapi/patches/generic_error.yaml, .schema/openapi/patches/security.yaml, Makefile, internal/httpclient/README.md, internal/httpclient/api/openapi.yaml, internal/httpclient/api_v0alpha1.go, internal/httpclient/docs/GenericError.md, internal/httpclient/model_generic_error.go, spec/api.json
Closes #1609
the changes.
works.
=> fix(sdk): use proper annotation for genericError

selfservice/strategy/oidc/provider_discord.go
When a value for prompt isn't provided, discord defaults prompt="consent". This change makes it so that if isForced is not true, prompt is "none". I didn't find any tests in the original commit that added this provider and I haven't run the tests locally, so I'm hoping CI can make sure I don't break anything :)
#1593
the changes.
works.
=> fix: skip prompt on discord authorization by default

docs/versioned_docs/version-v0.7/quickstart.mdx
Since we are running the quick-start locally —at least most will— the actual location of the redirect is `http://127.0.0.1:4433/self-service/login/browser` and not the one starting with  `https://playground.projects.oryapis.com/api/kratos/public`.
_None_
- [ x] I am following the
- [ x] I have read the [security policy](../security/policy).
- [ x] I confirm that this pull request does not address a security
the changes.
works.~~
- [x ] I …
=> docs: fix a redirect specified in play-by-play steps

docs/docs/guides/docker.md
Kratos does not automatically use a config file that exists at `$HOME/.kratos.yaml`, or any other similar pattern. The documentation in the Docker Images section of the guides could lead developers to believe that the --config flag is unnecessary if they are binding the directory the configuration file is in to $HOME or using a custom docker image to provide the file.
This will make Kratos easier to work with for people starting out.
```
BREAKING CHANGES: None.
```
https://github.com/ory/kratos/issues/1619
the …
=> docs: Update docker.md - Outdated information

driver/config/config.go
- replaced ViperKeyPublicBaseURL with keyURL in function baseURL(..) to produce correct warning message
https://github.com/ory/kratos/issues/1672
the changes.
works. - only formatting
=> fix: static parameter for warning message in config.baseURL(...)

docs/docs/self-service/flows/code/logout/samples/browser/node.txt, docs/versioned_docs/version-v0.7/self-service/flows/code/logout/samples/browser/node.txt
fix: naming of createSelfServiceLogoutUrlForBrowsers
"@ory/kratos-client": "^0.7.1-alpha.1" doesn't have function createSelfServiceLogoutUrlForBrowsers. Renamed createSelfServiceLogoutUrlForBrowsers to createSelfServiceLogoutFlowUrlForBrowsers
- [ x] I am following the
- [ x] I have read the [security policy](../security/policy).
- [ x] I confirm that this pull request does not address a security
the changes.
works.
- [ x] I have added …
=> docs: fix func naming for Logout flow

docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx, driver/config/.schema/config.schema.json, selfservice/strategy/oidc/provider_config.go, selfservice/strategy/oidc/provider_github-app.go
This change if for adding GitHub App as provider.
The main difference between GitHub Oauth2 and GitHub App here is that with GitHub App you can get the refresh token
@aeneasr 
the changes.
works.
We can also remove part of code of the current GitHub provider as it cn handle both cases
=> feat github-app provider

courier/courier.go, courier/courier_test.go, docs/docs/concepts/email-sms.md, docs/docs/reference/configuration.md, driver/config/.schema/config.schema.json, driver/config/config.go
This adds a simple configuration option for passing custom headers to the SMTP server.
https://github.com/ory/kratos/issues/1725
the changes.
works.
All automated tests pass for me locally, and I also confirmed with a manual test that the headers are propagated correctly to SES.  One thing I'm not quite sure how to test is the yaml config json schema validation.  It might be nice to add a `propertyNames.pattern` regex validation for the headers object and/or prohibit reserved headers like `To`, `Subject`, etc.  But, …
=> feat: custom smtp header config

internal/testhelpers/e2e_server.go
Just fix tests in `cmd/serve` due to some typo.
the changes.
works.
=> fix: typo tests in cmd/serve

.github/config.yml
Updated repository templates to https://github.com/ory/meta/commit/f62edfea9c162e724a286224e34d84cc3bef6807.
=> chore: update repository template to f62edfea

docs/docs/concepts/index.md, docs/docs/quickstart.mdx, docs/versioned_docs/version-v0.7/concepts/index.md, docs/versioned_docs/version-v0.7/quickstart.mdx
This PR closes https://github.com/ory/kratos/issues/1635 and we can create a separete issue/pr for a possible playground-based quickstart/tutorial. 
- Changing instances of `https://playground.projects.oryapis.com` to local kratos 
- Changing the login & registration payload examples so they work correctly. 
- Changing the end section & next steps a bit 
(IMO we dont need to tease adding login with github to the quickstart, when we have a great step-by-step guide based on the quickstart already)
=> fix: quickstart curl examples

schema/handler.go, schema/handler_test.go
=> fix: base64 schemas endpoint

cmd/daemon/serve.go, docs/docs/milestones.md, driver/config/config.go, embedx/config.schema.json
This PR introduces a new boolean configuration parameter that allows turning off logging of health endpoints requests in the access log. The implementation is basically a rip-off from Ory Hydra and the configuration parameter is the same:
```
serve.public.access_log.disable_for_health
serve.admin.access_log.disable_for_health
```
The default value is _false_.
the changes.
works.
Couldn't find any documentation to update, so if I'm missing anything, please direct me to the right place.
=> fix: Make health endpoints access logging configurable

docs/docs/concepts/ui-user-interface.mdx, test/e2e/run.sh
=> fix: e2e test regression

docs/docs/guides/2fa.mdx
none
the changes.
works.
just found this while implementing totp into my app (which was surprisingly easy, thanks for that!)
=> fix: totp unlink image in 2fa docs

docs/docs/concepts/ui-user-interface.mdx, text/context.go
The docs is auto-generating with useless changes, see e.g. https://github.com/ory/kratos/commit/64bf08d356051089bf163583ec382fdd16565c57 because we used `sjson` which does not order keys.
For less CI spam I am proposing to instead use `json.Marshal`. A quick benchmark shows that in this specific case `sjson` is only insignificantly faster:
<details>
<summary>Go benchmark</summary>
```go
package sjsonbench_test
import (
"encoding/json"
"github.com/tidwall/sjson"
"testing"
"time"
)
var now = time.Now()
func BenchmarkSJSON(b *testing.B) {
for i := 0; i < b.N; i++ {
j := "{}"
j, err := sjson.Set(j, "foobar", "some value")
if err != nil {
b.Errorf("error: %s", err)
}
j, err = sjson.Set(j, "asdf", 13241345)
if err != nil {
b.Errorf("error: %s", err)
}
j, err = sjson.Set(j, "jkhad", …
```
=> chore: use json.Marshal for the message context

Makefile, cmd/clidoc/main.go, docs/docs/concepts/ui-user-interface.mdx, text/id.go, text/message_login.go, text/message_node.go, text/message_recovery.go, text/message_registration.go, text/message_settings.go, text/message_validation.go, text/message_verification.go
closes #1956 
the changes.
works.
The clidoc util now ensures that there are no duplicate IDs.
It works, as before changing the ID I got this error:
```
$ make docs/cli
go run ./cmd/clidoc/. .
Unable to validate messages: message ID 1070000 is used more than once: InfoSelfServiceVerification InfoNodeLabel
main.validateAllMessagesExist
/home/patrik/git/kratos/cmd/clidoc/main.go:267
main.main
/home/patrik/git/kratos/cmd/clidoc/main.go:127
runtime.main
/usr/lib/go/src/runtime/proc.go:255 …
```
=> fix: de-duplicate message IDs

docs/docs/guides/setting-up-cors.mdx, docs/versioned_docs/version-v0.8/guides/setting-up-cors.mdx
It's a documentation update. Cors fails in case when Kratos public is not on the same subdomain as client. 
I could be fixed by adding `Content-Type` to allow headers. 
Refer to https://github.com/ory/kratos/discussions/1993
=> docs: Add content-type to allowed headers

cmd/identities/get.go, cmd/identities/get_test.go
Implement this https://github.com/ory/kratos/issues/1970
the changes.
works.
This is my first contrib :partying_face:
=> feat(cmd): add oidc credential include 

selfservice/strategy/password/validator.go, selfservice/strategy/password/validator_test.go, test/e2e/cypress/integration/profiles/email/registration/errors.spec.ts, test/e2e/cypress/integration/profiles/email/settings/errors.spec.ts, test/e2e/cypress/integration/profiles/mfa/totp.spec.ts, test/e2e/cypress/integration/profiles/mobile/registration/errors.spec.ts
Kratos follows [NIST Digital Identity Guidelines - 5.1.1.2 Memorized Secret Verifiers](https://pages.nist.gov/800-63-3/sp800-63b.html) and [password policy](https://www.ory.sh/kratos/docs/concepts/security#password-policy) says
> Passwords must have a minimum length of 8 characters and all characters (unicode, ASCII) must be allowed:
but currently Kratos requires 6 chars minimum. So I fixed to 8 chars.
the changes.
works.
=> fix: Require minimum length of 8 characters password

.docker/Dockerfile, .docker/Dockerfile-build, .docker/Dockerfile-debug, .docker/Dockerfile-sqlite, Makefile, docs/docs/self-service/flows/code/registration/index.js, docs/docs/self-service/flows/code/verification/index.js, docs/scripts/config.js, docs/src/theme/CodeFromRemote.js, docs/src/theme/ketoRelationTuplesPrism.js
Closes #1948
the changes.
works.
=> feat: buildkit with multi stage build

docs/docs/concepts/credentials/username-email-password.mdx
I think this is closer to how things are implemented, from what I have observed in the current code. So password is not silently truncated, but an error is returned. Also, the limit of 72 bytes (not characters!) is a property of the bcrypt algorithm itself and not the implementation.
the changes.
works.
=> docs: improve text around bcrypt

docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx, embedx/config.schema.json, go.mod, go.sum, selfservice/strategy/oidc/provider_config.go, selfservice/strategy/oidc/provider_spotify.go
Closes #1985
the changes.
works.
=> feat(oidc): add spotify provider

.circleci/config.yml, package-lock.json, package.json, test/e2e/package-lock.json, test/e2e/package.json, test/e2e/proxy/package-lock.json, test/e2e/run.sh
=> test(e2e): split e2e script into setup and test phase

contrib/quickstart/oathkeeper/access-rules.yml
Add "welcome,registration,login,verification" and "**.png" to the paths oathkeeper forwards to self service ui.
Currently the self service UI doesn't work when using `quickstart-oathkeeper.yml` from https://www.ory.sh/kratos/docs/guides/zero-trust-iap-proxy-identity-access-proxy/. This is due to the paths above missing from the access rules.
Fixes https://github.com/ory/kratos/issues/2048
the changes.
works.
=> fix: Add missing sample app paths to oathkeeper config

docs/docs/guides/2fa.mdx, docs/versioned_docs/version-v0.8/guides/2fa.mdx
As discussed.
I removed the three :::tips and moved it all to a separate section, since it looked really spooky having all these warning so prominently. 
Like this people can easily find it and it looks less scary. 
- adds webauthn constraints section
- moves all webauthn constraints to that secion
=> fix: add section on webauthn constraints

install.sh
The new download URLs don't match the link created in [install.sh](https://github.com/ory/kratos/blob/master/install.sh) and the download through this script fails. This commit fixed this issue.
the changes.
works.
=> fix: update download urls according to the new names

driver/config/config.go, driver/config/config_test.go, driver/config/stub/.kratos.yaml, embedx/config.schema.json, selfservice/flow/registration/error.go, selfservice/flow/registration/error_test.go, selfservice/flow/registration/handler.go, selfservice/flow/registration/handler_test.go, selfservice/strategy/oidc/strategy_test.go, test/e2e/cypress/integration/profiles/oidc/login/error.spec.ts, test/e2e/cypress/support/commands.ts, test/e2e/cypress/support/index.d.ts, text/message_error.go
This feature is to allow disabling of registration flows for all methods.
#882
the changes.
works.
=> feat: allow registration to be disabled

internal/testhelpers/errorx.go, selfservice/flow/registration/hook.go, selfservice/hook/session_issuer.go, selfservice/hook/session_issuer_test.go, selfservice/strategy/password/registration_test.go
This fixes the registration hooks to not include a `session` property in the response for API and SPA flows if there is no `"session"` hook configured. This new behavior matches up with pre-existing documentation.
Fixes #2093
the changes.
works.
* Since the presence of the `"session"` hook determines whether a valid session will be created, checking for that works well here. I do not know whether there is a more explicit way of verifying session validity that does not depend on the config.
* …
=> fix: Do not send session after registration without hook

internal/httpclient/api/openapi.yaml, internal/httpclient/docs/UiNodeAttributes.md, internal/httpclient/docs/UiNodeScriptAttributes.md, internal/httpclient/model_ui_node_script_attributes.go, selfservice/strategy/webauthn/login_test.go, selfservice/strategy/webauthn/settings_test.go, spec/api.json, spec/swagger.json, ui/node/attributes.go, ui/node/attributes_input.go
Closes https://github.com/ory/kratos-selfservice-ui-node/issues/162
the changes.
works.
=> feat: add preset CSP nonce

selfservice/flow/login/handler_test.go, selfservice/flow/recovery/handler_test.go, selfservice/flow/registration/handler_test.go, selfservice/flow/settings/handler_test.go, selfservice/flow/verification/handler.go, selfservice/flow/verification/handler_test.go
Fixes the verification handler to write the error, instead of nil object, when the flow does not exist. Adds tests for every handler to check proper behavior in that regard.
Fixes #2099 
the changes.
works.
=> fix: Send 404 instead of null response for unknown verification flows

docs/docs/concepts/email-sms.md, docs/docs/concepts/identity-schema.mdx, docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx
-  fix: use direct link instead of master
- fix: use relative link
- fix: beautiful arrows
Follow up PR as requested in https://github.com/ory/kratos/pull/2101#pullrequestreview-846823931.
Next step will be to add the rest of items to documentation 🥳 
the changes.
works.
=> fix: minor fixes in FAQ update

selfservice/flow/login/error.go
Fix error handling when failed to prepare for an expired flow.
This may not be happened normally so I don't know how to reproduce this.
But if this error occurs once, kratos logs same error endlessly and resources will be exhaust.
the changes.
works.
=> fix(login): Error handling when failed to prepare for an expired flow

persistence/sql/migrations/sql/20220114135828000000_verified_address_identity_index.cockroach.down.sql, persistence/sql/migrations/sql/20220114135828000000_verified_address_identity_index.cockroach.up.sql, persistence/sql/migrations/sql/20220114135828000000_verified_address_identity_index.mysql.down.sql, persistence/sql/migrations/sql/20220114135828000000_verified_address_identity_index.mysql.up.sql, persistence/sql/migrations/sql/20220114135828000000_verified_address_identity_index.postgres.down.sql, persistence/sql/migrations/sql/20220114135828000000_verified_address_identity_index.postgres.up.sql, persistence/sql/migrations/sql/20220114135828000000_verified_address_identity_index.sqlite3.down.sql, persistence/sql/migrations/sql/20220114135828000000_verified_address_identity_index.sqlite3.up.sql, persistence/sql/migrations/templates/20220114135828_verified_address_identity_index.down.fizz, persistence/sql/migrations/templates/20220114135828_verified_address_identity_index.up.fizz
The verifiable addresses are loaded eagerly into the identity. When that happens, the `identity_verifiable_addresses` table is queried by `nid` and `identity_id`. This index should greatly improve performance, especially of the `/sessions/whoami` endpoint.
=> fix: add `identity_id` index to `identity_verifiable_addresses` table

docs/docs/concepts/rest-api.mdx
Fixes: #2039
the changes.
works.
=> docs: pagination

embedx/config.schema.json
Inside the ``config.schema.json`` under the CORS setting, add the missing type (string) for the items of the ``allowed_origins`` array.
I'm proposing this because I process this schema through a library, and this crucial missing piece of information leads to unexpected behavior.
the changes.
works.
=> fix: include missing type string in config schema

courier/template/load_template.go, courier/template/load_template_test.go, courier/template/recovery_invalid.go, courier/template/recovery_valid.go, courier/template/stub.go, courier/template/verification_invalid.go, courier/template/verification_valid.go
Adds `embed.FS` support to the templates.
the changes.
works.
=> feat: courier templates fs support

x/http_secure_redirect.go, x/http_secure_redirect_test.go
Fixes a problem that when `after_verification_return_to` parameter containing hashtag # is specified, the server redirects to URL containing hashtag in URLEncoded form `%23`.
For example, specify `after_verification_return_to=/foo/kratos#abcd`
Incorrect behavior (before the fix): 
The verification flow redirects to `/foo/kratos%23abcd`
Correct behavior (after the fix): 
The verification flow redirects to `/foo/kratos#abcd`
Fixes #2068
the changes.
works.
=> fix: URL with hash sign in after_verification_return_to stays encoded

selfservice/strategy/webauthn/settings.go, selfservice/strategy/webauthn/settings_test.go
=> fix(selfservice): Cannot login after remove security keys and all other 2FA settings

selfservice/flow/login/hook.go, selfservice/strategy/totp/login_test.go, selfservice/strategy/totp/settings_test.go, session/manager.go, session/manager_test.go, test/e2e/cypress/integration/profiles/mfa/totp.spec.ts
=> fix(selfservice): Login self service flow with TOTP does not pass on return_to URL

courier/template/courier/builtin/templates/test_stub/email.body.sprig.gotmpl, courier/template/load_template.go, courier/template/load_template_test.go, x/stub_fs.go
Removes vulnerable sprig functions from go templates.
#2087 
the changes.
works.
=> fix: remove non-hermetic sprig functions

.github/workflows/ci.yaml
The `docs/cli-next` invocation was missing a required `output-dir` argument.
=> fix: add output-dir input to cli-next

selfservice/flow/settings/handler.go, selfservice/flow/settings/hook.go, selfservice/flow/settings/strategy_helper.go, selfservice/flow/settings/strategy_helper_test.go, selfservice/strategy/webauthn/settings.go, selfservice/strategy/webauthn/settings_test.go
Fix bug removing all credentials when remove all security keys.
Related: #2181
the changes.
works.
I'm sorry my previous PR #2181 fixes a bug but causes new bug.
=> fix: Do not remove all credentials when remove all security keys

cmd/hashers/argon2/root.go, selfservice/flow/settings/error.go, selfservice/flow/settings/handler.go, selfservice/flow/settings/sort.go, selfservice/flow/settings/strategy_helper_test.go
Closes https://github.com/ory/cloud/issues/56
the changes.
works.
=> fix: appropriately pass context around

.github/workflows/ci.yaml
The current ones are for a test audience. This switches to the live mailing list.
=> chore: use live mailchimp list ids

.schema/openapi/patches/identity.yaml, internal/httpclient/api/openapi.yaml, internal/httpclient/docs/IdentityCredentialsType.md, internal/httpclient/model_identity_credentials_type.go, spec/api.json
When an identity has `webauthn` or `lookup_secret` credentials, `AdminGetIdentity` http client returns validation error because these values are not `IdentityCredentialsType` list at SDK.
the changes.
works.
=> fix(sdk): Fix validation for an identity has webauthn or lookup_secret credentials

courier/courier_dispatcher.go, courier/courier_dispatcher_test.go, courier/message.go, courier/test/persistence.go, driver/config/config.go, driver/config/config_test.go, driver/config/stub/.kratos.courier.messageTTL.yaml, embedx/config.schema.json, test/schema/fixtures/config.schema.test.failure/root.invalidTypes.yaml, test/schema/fixtures/config.schema.test.success/root.courierSMS.yaml
This PR adds the option to configure a TTL (Time-To-Live) for messages that can not be delivered. After the TTL has passed since the message's creation and it was not delivered, the message is `Abandoned` and the courier will not try to deliver the message again. This is done by setting its `status` to `MessageStatusAbandoned` in the database. The courier will only try to deliver messages with the status `MessageStatusQueued`. 
This PR resolves https://github.com/ory/kratos/issues/944
the …
=> feat: add configurable timeout for unsent messages (#944)

internal/httpclient/api_v0alpha2.go, selfservice/flow/recovery/handler.go
- fix: broken links API spec
- fix: broken links handler.go
- fix: broken links api.go
the changes.
works.
=> docs: fix broken links API doc"

selfservice/flow/login/error.go, selfservice/flow/login/handler.go, selfservice/flow/login/sort.go, ui/container/container_test.go, ui/node/attributes_input_test.go
=> fix: properly pass context

contrib/quickstart/oathkeeper/access-rules.yml
This is a fix for 2 minor issues I found while working on #2311:
1. http://127.0.0.1:4455/ returns a `404` instead of redirecting to http://127.0.0.1:4455/welcome (which is the behaviour in the standalone setup)
2. http://127.0.0.1:4455/error should be accessible in order to display more friendly and more detailed error messages.
the changes.
works.
=> fix: provide access to root path and error page

.docker/Dockerfile-build
The default mode is 0644, which is allows broader access than necessary.
the changes.
works.
I haven't added an automated test, as I didn't see a clean place to add it (maybe `test/e2e/run.sh` but there are no assertions there, and Cypress seems more about asserting what happens in the browser. If I should add a test, let me know where.
Instead, here's "proof" that it works:
```
$ docker-compose -f quickstart.yml -f quickstart-standalone.yml up --build --force-recreate
[...]
Ctrl+C
$ sudo ls …
```
=> fix: change SQLite database mode to 0600

schema/handler.go
Do not expose debug in a response when a schema is not found.
This debug property does not look valuable for clients and just risks which is exposing server information such as middleware.
```
$  curl http://localhost:4455/.ory/kratos/public/schemas/not_found
{"error":{"code":404,"status":"Not Found","debug":"id=\nrid=\nerror=The request was malformed or contained invalid parameters\nreason=Unable to find JSON Schema ID: not_found\ndetails=map[]\ndebug=\n\ngithub.com/ory/kratos/schema.Schemas.GetByID\n\t/project/schema/schema.go:37\ngithub.com/ory/kratos/schema.(*Handler).getByID\n\t/project/schema/handler.go:106\ngithub.com/ory/kratos/x.NoCacheHandle.func1\n\t/project/x/nocache.go:18\ngithub.com/ory/kratos/x.NoCacheHandle.func1\n\t/project/x/nocache.go:18\ngithub.com/julienschmidt/httprou …
```
=> fix: Do not expose debug in a response when a schema is not found

cmd/daemon/serve.go
Since admin endpoints have been moved under /admin prefix, `serve.admin.request_log.disable_for_health` parameter doesn't work anymore.
This PR fixes the issue by adding the missing prefix in front of ignored URLs.
Using kratos quickstart:
```bash
yq -i '.serve.admin.request_log.disable_for_health  = true' contrib/quickstart/kratos/email-password/kratos.yml
docker-compose -f quickstart.yml -f quickstart-standalone.yml up --build --force-recreate
curl http://127.0.0.1:4434/admin/health/ready
```
Output in logs:
```
kratos_1                      | time=2022-04-14T12:25:38Z level=info msg=started handling request func=github.com/ory/x/reqlog.(*Middleware).ServeHTTP file=/go/pkg/mod/github.com/ory/x@v0.0.358/reqlog/middleware.go:131 http_request=map[headers:map[accept:*/* …
```
=> fix: serve.admin.request_log.disable_for_health behaviour

courier/smtp.go, courier/smtp_test.go, driver/config/config.go, embedx/config.schema.json
This is an implementation of certificate based authentication for the smtp client, as described in design document [#2350](https://github.com/ory/kratos/issues/2350)
the changes.
works.
=> feat: add certificate based authentication for smtp client

driver/registry_default.go, go.mod, selfservice/strategy/password/validator.go, selfservice/strategy/password/validator_test.go
This PR changes internal storage for HIBP API call results to use ristretto cache instead of plain map to avoid excessive memory allocations when handling substantial load (each checked hash is stored indefinitely in memory).
* https://github.com/ory/kratos/issues/2354
the changes.
works.
This patch was running for a few days on our cluster and it looks like memory usage is not increasing and stabilised around 70MB which is great :-)
=> fix: avoid excessive memory allocations

identity/handler.go
- docs: remove notice importing credentials not possible
I tested with `make sdk` and looked as expected.
the changes.
works.
=> docs: remove notice importing credentials not possible api doc

examples/go/selfservice/login/main.go, identity/handler.go, identity/handler_test.go
Signed-off-by: Veena Saini <veena.code.assignment@gmail.com>
This PR fixes the issue https://github.com/ory/kratos/issues/2307. 
Currently if a user sends HTTP PUT request with empty json data or incorrect json path (means the file does not exist), then that results into "internal server error". This error message is a generic and creates confusion. 
Empty json (or we can say http request without body) triggers io.EOF error.  This PR provides the user a better error message when io.EOF error is encountered.
**Affected Module: Identity Update** 
There can be other scenarios of malformed user requests that may trigger "internal server error" during identity update, but those are not handled in this PR.
- [x ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md). …
=> fix: Internal Server Error on Empty PUT /identities/id body

courier/smtp.go, driver/config/config.go, embedx/config.schema.json
This PR introduces a new configuration `courier.smtp.local_name` that is passed to the SMTP dialer used in kratos courier.
The config value is used in the  SMTP HELO/EHLO command and was previously hardcoded to `localhost`.
Some SMTP relays (e.g. Gmail) require a unique identifier during the HELO command and close the connection if a generic value like `localhost` is used. Therefore those SMTP relays can currently not be used with Kratos.
See https://support.google.com/a/answer/2956491?product_name=UnuFlow&hl=en&visit_id=637871815371283723-3216367043&rd=1&src=supportwidget0&hl=en
> We recommend that you configure your mail server to present a unique identifier (such as your domain name or the name of your mail server) in the HELO or EHLO command in the SMTP relay connections your server …
=> feat: add localName to smtp config

internal/httpclient/api/openapi.yaml, internal/httpclient/api_v0alpha2.go, internal/httpclient/docs/V0alpha2Api.md, selfservice/flow/login/handler.go, selfservice/flow/recovery/handler.go, selfservice/flow/registration/handler.go, selfservice/flow/settings/handler.go, selfservice/flow/verification/handler.go, spec/api.json, spec/swagger.json
Closes #2003
Closes #2454
the changes.
works.
=> feat(sdk): add cookie headers to all form submissions

selfservice/flow/recovery/error.go, selfservice/flow/recovery/handler_test.go
I am not sure what the policy here is for returning the `id` field in errors, but since Kratos returns `session_already_available` in the login and registration flows, it should probably also return it when attempting recovery. This has been reported to me by our frontend developer. I suppose he'd want to detect this error reliably and handle it accordingly.
the changes.
works.
=> Add ID to the recovery error when already logged in

selfservice/flow/verification/flow.go, selfservice/strategy/link/strategy_verification.go, selfservice/strategy/link/strategy_verification_test.go, test/e2e/cypress/support/commands.ts
This pull request basically appends the flow ID when redirecting the user to the passed `return_to` URL after clicking the verification link.
#2481
the changes.
works.
=> fix: add flow id when return_to is passed to the verification

selfservice/strategy/oidc/provider_auth0.go, selfservice/strategy/oidc/provider_auth0_test.go
Closes #2485
the changes.
works.
=> fix(auth0): created_at workaround

.github/workflows/ci.yaml
The label for the CI badge currently reads "CI Tasks for Ory Kratos", resulting in this long badge:
This PR shortens the badge label to "CI".
vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the
maintainers to push the changes.
=> Shorten the CI badge label

README.md, cmd/clidoc/main.go
This changes the message list on the [Customize User Interface](https://www.ory.sh/docs/kratos/concepts/ui-user-interface#ui-message-codes) page to be rendered as a single JSON block, so that it's easier to copy and paste when dealing with translations.
I removed the original rendering with the headers for each message, since it felt weird to put both renderings underneath each other, and the headers didn't seem very useful anyway. If you disagree, I can bring them back, just let me know.
resolves #2498 
vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the
maintainers to push the changes.
=> docs: write messages as single json document

identity/handler.go, identity/handler_test.go
Making this a draft PR as there are (unrelated) tests failing.  
The admin API should allow changing the credentials. The simple use case is the ability of an admin user to update a password for a regular one.  
Should fix #2334 
the changes.
works.
Unfortunately, running make test (go test -p 1 -tags sqlite -count=1 -failfast ./...) have failed tests which are totally unrelated to the PR. Running a single test fails with 
`time=2022-04-25T12:32:06+03:00 level=warning msg=Unable to connect to …
=> implemented handler for update API with credentials

persistence/sql/persister_session.go, session/handler_test.go
The `GET /admin/identities/{id}/sessions` endpoint would return `null` instead of `[]` if the identity had no sessions (or the identity didn't exist). It's very easy to miss this case when deserializing responses into slices in tests.
=> fix: return an empty array not null when there are no sessions

selfservice/strategy/oidc/provider_apple.go
No issuer url was specified when using the Apple ID provider, this forced usersers to manually enter it in the provider config.
This PR adds the Apple ID issuer url to the provider simplifying the setup.
Fixes: https://github.com/ory/kratos/issues/2558
=> fix: add IssuerURL for Apple ID

selfservice/strategy/link/strategy_recovery_test.go, session/session.go
When user tries to login with oidc and encounters "account disabled" error it is hard to find which identity is inactive.
oidc provider user id (subject) is needed to find the identity.
To make this simpler, this PR adds identity id to the logs.
- [ x] I am following the [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ x] I have read the [security policy](../security/policy).
- [ x] I confirm that this pull request does not address a security vulnerability. 
=> feat: add identity id to "account disabled" error

selfservice/strategy/webauthn/login.go
=> docs(sdk): identifier is actually required

selfservice/flow/login/flow.go, selfservice/flow/login/flow_test.go, selfservice/flow/login/handler.go, selfservice/flow/login/hook.go, selfservice/flow/recovery/flow.go, selfservice/flow/recovery/flow_test.go, selfservice/flow/registration/flow.go, selfservice/flow/registration/flow_test.go, selfservice/flow/registration/handler.go, selfservice/flow/registration/hook.go, selfservice/flow/settings/flow.go, selfservice/flow/settings/flow_test.go, selfservice/strategy/oidc/strategy_login.go, selfservice/strategy/oidc/strategy_registration.go, selfservice/strategy/oidc/strategy_test.go, x/http_secure_redirect.go
When handling the callback from the oidc provider and starting a new registration flow to sign up the user we create a new temp request that contains the initial request parameters from the login flow.
Proposal to close https://github.com/ory/kratos/issues/2444.
the changes.
works.
=> fix: return browser to 'return_to' when logging in without registered account using oidc. 

session/handler.go, session/handler_test.go, session/manager.go, session/manager_http.go
Closes #2562
I chose to use the method proposed here https://github.com/ory/kratos/issues/2562#issuecomment-1181382333 and added the new value `expires_at` to the cookie.
Additionally I added a new method `ReIssueRefreshedCookie()` to `session.Manager` that checks if the `expires_at` value of the cookie and the stored session are out of sync and re-issues the cookie.
The `/session/whoami` endpoint now also calls `ReIssueRefreshedCookie()`.
I added two new test cases. The first case tests that no cookies are issued when the session wasn't extended.
The second case tests that the cookie is issued after extending the session in the backend.
#2562
I confirm that I got green light (please contact …
=> fix: Re-issue outdated cookie in /whoami

.docker/Dockerfile-debug, script/debug-entrypoint.sh
The new go version needs some tweaks in our debugging setup.
* Disabling `-buildvcs=false` in go build, this is a new "feature" introduced in go 1.18 but is not required for working binary and if turned on can throw errors on incompatible versions of git
* `RUN go get github.com/go-delve/delve/cmd/dlv` doesn't work on the new version and instead is recommended to use `go install` with the specified version
=> fix: Fix debugging Docker setup

.schema/openapi/patches/schema.yaml, ui/node/attributes.go
=> fix(sdk): rust compile issue with required enum

.schemastore/config.schema.json, courier/courier_dispatcher.go, courier/courier_dispatcher_test.go, courier/message.go, courier/persistence.go, courier/smtp.go, courier/test/persistence.go, driver/config/config.go, driver/config/config_test.go, driver/config/stub/.kratos.courier.messageTTL.yaml, driver/config/stub/.kratos.courier.message_retries.yaml, embedx/config.schema.json, persistence/sql/README.md, persistence/sql/migrations/sql/20220802103909000000_courier_send_count.down.sql, persistence/sql/migrations/sql/20220802103909000000_courier_send_count.up.sql, persistence/sql/persister_courier.go, test/schema/fixtures/config.schema.test.failure/root.invalidTypes.yaml, test/schema/fixtures/config.schema.test.success/root.courierSMS.yaml
This PR replaces the `courier.message_ttl` configuration option with a `courier.message_retries` option to limit how often the sending of a message is retried before it is marked as `abandoned`. 
This is a breaking change, as it removes the `message_ttl` config key.
https://github.com/ory/kratos/issues/402 https://github.com/ory/kratos/issues/1598
=> feat: replace message_ttl with static max retry count

go.mod, identity/identity_recovery.go, identity/identity_recovery_test.go, identity/identity_verification.go, identity/identity_verification_test.go, package-lock.json, persistence/sql/persister_identity.go, persistence/sql/persister_test.go, selfservice/strategy/link/test/persistence.go
This PR modifies persister.UpdateIdentity to only update the recovery addresses that changed, leaving the unchanged once (and their associated recovery tokens) valid.
Shout-out to @thcyron for the analysis.
Fixes #2433
---
=> fix: do not invalidate recovery addr on update

persistence/sql/migratest/testdata/20220907132836_testdata.sql, persistence/sql/migrations/sql/20220907132836000000_sessions_add_client_fields.cockroach.up.sql, persistence/sql/migrations/sql/20220907132836000000_sessions_add_client_fields.mysql.up.sql, persistence/sql/migrations/sql/20220907132836000000_sessions_add_client_fields.postgres.up.sql, persistence/sql/migrations/sql/20220907132836000000_sessions_add_client_fields.sqlite3.up.sql, persistence/sql/persister_session.go, session/persistence.go, session/session.go, session/session_test.go
This PR fixes the eager query for Session devices and adds the creation of the devices in the Upsert. The update operation for devices doesn't belong with the upsert as at most one device would need an update (Due to change of IP or simply updating the `last_seen` timestamp).
Fixes - https://github.com/ory/kratos/pull/2715#discussion_r970537554
=> feat: complete session devices upsert

internal/httpclient/api_metadata.go, internal/httpclient/api_v0alpha2.go, package-lock.json
Fixes leftover formatting issues from when the SDK generator didn't format changes. This problem should no longer happen since https://github.com/ory/ci/pull/109 is shipped now.
the changes.
works.
=> chore: fix formatting

Makefile, go_mod_indirect_pins.go
listx doesn't seem to be used anywhere in this repo. Looking at https://github.com/ory/x/blob/master/tools/listx/main.go, it seem replacable with `find -f -name "*.go" -not -path "./vendor/"`. Given that there isn't a vendor folder anymore, this seems obsolete altogether.
the changes.
works.
=> chore: remove listx dependency

session/persistence.go
Removing tests dead code. These tests are currently not run and a more extensive test suite exists (including the ones in `session/persistence.go`) under `session/test/persistence.go`
=> chore: remove dead code

.docker/Dockerfile-build, .docker/Dockerfile-debug, .github/workflows/ci.yaml, .golangci.yml, cmd/identities/delete.go, cmd/identities/delete_test.go, cmd/identities/get.go, cmd/identities/get_test.go, cmd/identities/import.go, cmd/identities/import_test.go, cmd/identities/list.go, cmd/identities/list_test.go, cmd/root.go, cmd/root_test.go, go.mod, go.sum, test/e2e/mock/webhook/Dockerfile
#2770 with passing tests :wink: 
----
golangci-lint warned:
```
$ golangci-lint run
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [linters context] structcheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649. 
```
Because we already have `unused` enabled, it was just a matter of removing the deprecated …
=> chore: cli do not pass down root

identity/handler.go, identity/handler_test.go, identity/identity.go, identity/identity_test.go
The admin identities list response now includes `metadata_admin` property within the returned identities.
https://github.com/ory/kratos/issues/2711
the changes.
works.
_(n/a: This fix makes the implementation compliant with existing docs)_
=> fix: #2711 include metadata_admin in admin identity list response

persistence/sql/persister_session.go, session/handler.go, session/handler_test.go, session/persistence.go, session/test/persistence.go
This resolves issue #2762
This resolves the issue of missing pagination headers in the response to the `/admin/identities/{id}/sessions` endpoint by adding a `CountSessionsByIdentity` function to the `persistence` module, and then using that new function within the api handler to get the total records count needed for calling the `x.PaginationHeader` function.
The `CountSessionsByIdentity` function is scoped to the provided Identity ID, and respects the `active` query parameter if it was present. 
Changelog entry:
```
Fixed adminListIdentitySessions endpoint response missing pagination headers
```
This PR resolves the following ticket, which I just opened a short bit ago to comply with the Contributions guide. That ticket details the issue more thoroughly, including the steps for …
=> fix: identity sessions list response includes pagination headers

courier/email_templates.go, courier/email_templates_test.go, selfservice/strategy/code/sender.go, test/e2e/cypress/integration/profiles/recovery/code/errors.spec.ts, test/e2e/cypress/support/commands.ts, test/e2e/cypress/support/index.d.ts
This PR fixes the usage of the wrong template when trying to recover a not registered account. Also clarifies the tests to reflect this case. 
the changes.
works.
=> fix: missing usage to recovery_code_invalid template

internal/httpclient/api/openapi.yaml, internal/httpclient/api_v0alpha2.go, internal/httpclient/docs/V0alpha2Api.md, selfservice/flow/login/handler.go, selfservice/flow/registration/handler.go, spec/api.json, spec/swagger.json
=> chore(sdk): update order of arguments

internal/httpclient/README.md, internal/httpclient/api/openapi.yaml, internal/httpclient/api_v0alpha2.go, internal/httpclient/docs/V0alpha2Api.md, persistence/sql/persister_session.go, session/expand.go, session/handler.go, session/handler_test.go, spec/api.json, spec/swagger.json
- Adding an API to get session with expand options
- Refactor Session Listing to add expand options to query params and default to expand nothing
https://github.com/ory-corp/cloud/issues/2007
the changes.
works.
=> feat: add admin get api for session

courier/email_templates.go, internal/httpclient/api/openapi.yaml, spec/api.json, spec/swagger.json
=> chore: make `courier.TemplateType` an enum

go.mod, go.sum
Ref https://github.com/ory/x/pull/635
=> chore: bump ory/x

test/e2e/cypress/integration/profiles/verification/verify/errors.spec.ts
=> chore: remove .only from test

driver/config/config.go, driver/config/config_test.go, embedx/config.schema.json, session/handler.go, session/handler_test.go
- Added config key `session.whoami.caching` with default being disabled
- Set cache headers based on configuration
https://github.com/ory-corp/cloud/issues/3283
the changes.
works.
=> feat: add session cache header feature flag

internal/testhelpers/courier.go, internal/testhelpers/strategy_code.go, selfservice/strategy/code/.schema/recovery.schema.json, selfservice/strategy/code/.snapshots/TestAdminStrategy-case=form_should_not_contain_email_field_when_creating_recovery_code.json, selfservice/strategy/code/.snapshots/TestRecovery-description=should_set_all_the_correct_recovery_payloads_after_submission.json, selfservice/strategy/code/code_sender_test.go, selfservice/strategy/code/strategy.go, selfservice/strategy/code/strategy_recovery.go, selfservice/strategy/code/strategy_recovery_test.go, test/e2e/cypress/helpers/index.ts, test/e2e/cypress/support/commands.ts
=> feat: change code length to 6 numbers

persistence/sql/migratest/fixtures/session/7458af86-c1d8-401c-978a-8da89133f78b.json, persistence/sql/migratest/fixtures/session/7458af86-c1d8-401c-978a-8da89133f98b.json, persistence/sql/migratest/fixtures/session/dcde5aaa-f789-4d3d-ae1f-76da8d57e67c.json, persistence/sql/migratest/fixtures/session/f38cdebe-e567-42c9-a562-1bd4dee40998.json, persistence/sql/migratest/testdata/20210810153530_testdata.sql, session/handler_test.go, session/session.go
- Use `.isActive()` eval for state 
the changes.
works.
=> fix: marshalled session state 

hash/hash_comparator.go, hash/hasher_test.go, identity/.snapshots/TestHandler-case=should_be_able_to_import_users-with_md5_password.json, identity/handler_import.go, identity/handler_test.go
=> feat: support importing MD5 hashes

selfservice/hook/stub/test_body.jsonnet, selfservice/hook/web_hook.go, selfservice/hook/web_hook_integration_test.go
Request cookies were already available in raw form in the `ctx.request_headers` top-level argument to the Jsonnet snippet. Parsing cookies in Jsonnet is tedious and error-prone, though, so we parse them internally for convenience.
Ref https://github.com/ory-corp/cloud/issues/3434
=> feat: forward parsed request cookies to webhook Jsonnet snippet

embedx/config.schema.json
=> feat: require verification on login

cmd/daemon/serve.go
CORS response headers not added to the response:
```
access-control-allow-credentials: true
access-control-allow-origin: ...
access-control-expose-headers: Content-Type, Set-Cookie
```
#2922 
the changes.
works.
I just wanted to quickly fix the issue. I noticed that upgrading the docker image breaks CORS. Checked the changes before releases and reverted the cause of the problem.
BTW: I noticed that response headers are added by the middleware but they disappear somehow during the processing …
=> fix: cors headers not added to the response #2922

driver/config/config_test.go
This fixes a problematic unit test, that monitors log messages and expected a specific message at the end of the list. This has been corrected by searching for the expected message in the list.
the changes.
works.
=> fix: flaky test

courier/courier_dispatcher.go, courier/smtp.go
Added `message_nid` field to logs from courier
https://github.com/ory-corp/cloud/issues/3509
the changes.
works.
=> feat: add NID to logs in courier

driver/config/config_test.go
Addendum to #2964
the changes.
works.
=> fix: dont reset to false

persistence/sql/persister_session.go, session/handler_test.go, session/session.go, session/test/persistence.go
- `Where` clause added to also check session expiry timestamp to return correct list
- Fixed to query identity only once
- Remove marshalling mutation 
https://github.com/ory/kratos/issues/2930
the changes.
works.
=> fix: listing sessions query

selfservice/hook/web_hook.go, selfservice/hook/web_hook_integration_test.go
Previously, async webhooks (`response.ignore=true`) would be canceled early once the incoming Kratos request was served and it's associated context released. We now dissociate the cancellation of async hooks from the normal request processing flow.
I've also improved the OpenTelemetry instrumentation.
=> fix: spurious cancelation of async webhooks, better tracing

session/manager_http.go, session/manager_http_test.go
This patch removes the undocumented and experimental `X-Session-Cookie` header from the `/sessions/whoami` endpoint.
the changes.
works.
=> fix: remove unused x-session-cookie parameter

.github/workflows/ci.yaml
=> chore: pin nancy

selfservice/strategy/link/strategy_verification_test.go
When user clicks the verification link sent over email and the link has expired, then Kratos creates new verification flow and browser is redirected to verification ui with the new flow id set as a URL parameter.
The problem is that the verification UI cannot fetch the new flow as it has no csrf token set. So, browser gets 403 "Forbidden" error.
This PR eliminates csrf checking if verification flow has no csrf token.
- [ x] I am following the
- [ x] I have read the [security policy](../security/policy).
- [ x] I confirm that this pull request does not address a security
vulnerability. If this pull …
=> fix: regenerate csrf if flow has expired

contrib/quickstart/kratos/cloud/kratos.yml, contrib/quickstart/kratos/email-password/kratos.yml, contrib/quickstart/oathkeeper/access-rules.yml, quickstart-oathkeeper.yml
Hi there,
I started to play with your quickstart examples and I realised that the Kratos configuration files are targeting very old versions of the tool (e.g. `v0.7.1-alpha.1`), which make them invalid according to your current configuration JSON schema.
This PR upgrades the version numbers in the Kratos configuration files located in `contrib/quickstart`. I also took the liberty to upgrade the Docker image of Oathkeeper in `quickstart-oathkeeper.yml`.
N/A
the changes.
works.
Some of the …
=> fix: quickstart demos

selfservice/strategy/oidc/provider_gitlab.go
=> fix: set accept header for GitLab

selfservice/flow/settings/hook.go, selfservice/strategy/lookup/settings_test.go, selfservice/strategy/webauthn/settings_test.go, test/e2e/cypress/integration/profiles/mfa/totp.spec.ts
Fixes a 500 error if TOTP is removed and then re-added in the same flow.
It also fixes another related bug, that can be reproduced with https://github.com/ory/kratos-selfservice-ui-react-nextjs:
1. go to settings
2. change your name (or email, or whatever)
3. try to set up TOTP
4. "invalid code"
The reason is that because the `InternalContext` is not reset properly in `PostSettingsHook`, the flow will have a new QR code and secret key (`UI` is reset), but the internal context will keep the old TOTP secret.
In the case of the original issue, `InternalContextKeyURL` is deleted from `InternalContext` when TOTP is removed, and since it's not set properly in `PostSettingsHook`, when we try to re-add TOTP, we get 500, because `InternalContextKeyURL` is missing. …
=> fix: TOTP invalid code and/or 500 error

cmd/cliclient/cleanup.go
Remove the option parameter that prevents network init. The delete queries cannot handle `nil` values for `nid`.
=> fix: remove skip network init option parameter

selfservice/strategy/oidc/provider_netid.go, selfservice/strategy/oidc/provider_userinfo_test.go
=> fix: issuer missing from netid claims

selfservice/strategy/code/.snapshots/TestRecovery-description=should_set_all_the_correct_recovery_payloads_after_submission.json, selfservice/strategy/code/.snapshots/TestVerification-description=should_set_all_the_correct_verification_payloads_after_submission.json, text/message_node.go
Fixes #3051
the changes.
works.
=> chore: fix wrong message id on resend code button

identity/handler.go, selfservice/hook/session_destroyer.go, selfservice/hook/session_issuer.go, selfservice/hook/verification.go, selfservice/hook/web_hook.go, session/session.go
This is the same as #3042 but for session devices.
Also renamed some tracing span names in hooks.
=> feat: let the database generate session device IDs

internal/client-go/api_frontend.go, internal/httpclient/api_frontend.go, selfservice/flow/registration/handler.go, spec/api.json, spec/swagger.json
Fixes: https://github.com/ory/kratos/issues/3096
the changes.
works.
=> fix: add `after_verification_return_to` to sdk and api docs

selfservice/strategy/oidc/provider_generic_oidc.go, selfservice/strategy/oidc/provider_google.go, selfservice/strategy/oidc/provider_google_test.go
google doesn't implements offline access as a scope but instead as a special uri parameter
this PR adapts the code such that if the offline_access scope is requested, it gets transformed into the parameter
access_type=offline
=> fix: implement offline scope in the way google expects

identity/handler.go, identity/handler_test.go
Fixes #2950
the changes.
works.
=> fix: correctly apply patches to identity metadata

identity/test/pool.go, persistence/sql/persister_identity.go
Closes #3105
the changes.
works.
=> fix: only return one result set for credentials_identifier

selfservice/hook/web_hook.go, selfservice/hook/web_hook_integration_test.go
The current approach does not ignore errors from the request building process, only the actual request. This patch moves the request build into the async part of the webhook as well.
the changes.
works.
_
=> fix: make async webhooks fully async

persistence/sql/identity/persister_identity.go, selfservice/hook/web_hook.go
Found by @jonas-jonas [here](https://github.com/ory/kratos/pull/3101#discussion_r1124712299) (thanks!)
The webhook tracing was broken in the last refactoring. This change restores the correct passing of span contexts, and also re-enables retries. Previously, all attempts were aborted after a total of 30s. Now, we get 30s for each attempt.
=> fix: webhook tracing and missing defers

internal/client-go/model_identity_schema_container.go, internal/httpclient/model_identity_schema_container.go, schema/handler.go, schema/handler_test.go, spec/api.json, spec/swagger.json
https://github.com/ory/network/issues/251
the changes.
works.
=> fix: use type alias instead of type definition

selfservice/flow/login/handler.go, selfservice/flow/login/handler_test.go
fixes #3108 
The `oauth2_login_request` field was missing when initially creating the login flow.
the changes.
works.
=> fix: add `HydraLoginRequest` on flow creation

embedx/config.schema.json, internal/client-go/model_update_login_flow_with_oidc_method.go, internal/client-go/model_update_registration_flow_with_oidc_method.go, internal/client-go/model_update_settings_flow_with_oidc_method.go, internal/httpclient/model_update_login_flow_with_oidc_method.go, internal/httpclient/model_update_registration_flow_with_oidc_method.go, internal/httpclient/model_update_settings_flow_with_oidc_method.go, selfservice/strategy/oidc/.schema/link.schema.json, selfservice/strategy/oidc/.schema/settings.schema.json, selfservice/strategy/oidc/provider.go, selfservice/strategy/oidc/provider_config.go, selfservice/strategy/oidc/strategy_login.go, selfservice/strategy/oidc/strategy_registration.go, selfservice/strategy/oidc/strategy_settings.go, selfservice/strategy/oidc/strategy_settings_test.go, selfservice/strategy/oidc/strategy_test.go, spec/api.json, spec/swagger.json, test/e2e/cypress/integration/profiles/oidc/login/success.spec.ts, test/e2e/cypress/integration/profiles/oidc/registration/error.spec.ts, test/e2e/cypress/integration/profiles/oidc/registration/success.spec.ts, test/e2e/cypress/integration/profiles/oidc/settings/success.spec.ts, test/e2e/cypress/support/commands.ts, test/e2e/cypress/support/index.d.ts
This PR introduces the upstream OIDC query parameters `login_hint` and `hd`. More can be added at a later stage in the `link.schema.json` and `settings.schema.json` file.
https://github.com/ory/kratos/blob/8fe11cd59cc7690abda3acaac72e61fffed87566/selfservice/strategy/oidc/.schema/link.schema.json#L20-L31
https://github.com/ory/kratos/blob/4362423c3cddd98e46745493288fec69f9c66766/selfservice/strategy/oidc/.schema/settings.schema.json
To send additional upstream parameters the form can post this on a login, registration or settings link submit.
For example the form below does an OIDC flow to Google. We can now add additional parameters such as `login_hint` and `hd` to the upstream request to Google login with a pre-filled email `email@example.com`:
```html
<form …
```
=> feat: add upstream parameters to oidc provider

go.mod, go.sum, identity/handler.go, identity/handler_test.go
The problem is that the persister uses `1` as the fist page, while the pagination header helper assumes `0` is the first page.  Therefore, until now, the second-last page was considered the last and no `next` rel was set in the `Link` header.
This is the only way I could think of to make this not a breaking change, but it is super ugly.
=> fix: do not omit last page on identity list

persistence/sql/migrations/sql/20230216142104000000_session_devices_index_drop.cockroach.down.sql, persistence/sql/migrations/sql/20230216142104000000_session_devices_index_drop.cockroach.up.sql, persistence/sql/migrations/sql/20230216142104000000_session_devices_index_drop.down.sql, persistence/sql/migrations/sql/20230216142104000000_session_devices_index_drop.mysql.down.sql, persistence/sql/migrations/sql/20230216142104000000_session_devices_index_drop.mysql.up.sql, persistence/sql/migrations/sql/20230216142104000000_session_devices_index_drop.up.sql
This index doesn't serve a real purpose and is interfering with the multi-region rollout.
=> feat: drop unused index

Makefile, courier/template/testhelpers/testhelpers.go, driver/registry_default_test.go, hash/hasher_test.go, internal/driver.go, persistence/sql/migratest/migration_test.go, selfservice/hook/web_hook_integration_test.go
=> chore: parallelize unit tests

contrib/quickstart/oathkeeper/access-rules.yml
If you're following the tutorial at https://www.ory.sh/docs/kratos/guides/zero-trust-iap-proxy-identity-access-proxy and using the reference frontend, you'll get broken images and fonts when loading the login (and other) pages.
This simply allows the other assets that the reference frontend uses to be loaded via the proxy without error.
No related issues as far as I can tell.
the changes.
works.
=> chore: update access-rules.yml example in contrib to allow more assets

go.mod, go.sum, identity/credentials.go, identity/expandables.go, identity/identity.go, identity/test/pool.go, persistence/sql/identity/persister_identity.go, persistence/sql/migratest/migration_test.go, persistence/sql/persister_test.go, selfservice/hook/web_hook_integration_test.go, selfservice/strategy/lookup/strategy_test.go, selfservice/strategy/oidc/strategy_test.go, selfservice/strategy/password/strategy_test.go, selfservice/strategy/totp/strategy_test.go, selfservice/strategy/webauthn/strategy_test.go, x/xsql/sql.go
This change revamps the way we fetch identity credentials. We no longer need most of the helper fields for gobuffalo/pop inside the `Identity` and `Credentials` structures, and we collect all the credentials in one joined query rather than using pop's `EagerPreload` functionality.
=> feat: refactor credentials fetching

selfservice/hook/verification.go
Fixes ory-corp/cloud/issues/4283
the changes.
works.
=> fix: re-use existing CSRF token in verification flows

identity/test/pool.go, persistence/sql/identity/persister_identity.go
PostgresQL does not support `... WHERE x IN ( )` with an empty argument list. Works in CRDB, though. Our tests didn't catch this because they didn't expand credentials.
Closes https://github.com/ory/kratos/issues/3194
=> fix: invalid SQL syntax in ListIdentities

test/e2e/cypress/integration/profiles/verification/login/errors.spec.ts
When account verification is required for login, the UI will instead redirect to the verification UI with the error message.
https://github.com/ory/kratos-selfservice-ui-node/pull/253
the changes.
works.
=> fix: e2e account experience redirects to verification page

selfservice/flow/registration/hook.go, selfservice/hook/web_hook.go
Changes:
* Decouple post-registration post-persistence context from request context
* Upgrade ory/x to use retrying in Jsonnet VM
* Add better logging for when webhooks fail
the changes.
works.
=> fix: improve webhook resilience

internal/client-go/api_metadata.go, internal/client-go/model_update_recovery_flow_with_code_method.go, internal/client-go/model_update_recovery_flow_with_link_method.go, internal/client-go/model_update_verification_flow_with_code_method.go, internal/client-go/model_update_verification_flow_with_link_method.go, internal/httpclient/api_metadata.go, internal/httpclient/model_update_recovery_flow_with_code_method.go, internal/httpclient/model_update_recovery_flow_with_link_method.go, internal/httpclient/model_update_verification_flow_with_code_method.go, internal/httpclient/model_update_verification_flow_with_link_method.go, selfservice/flow/recovery/error_test.go, selfservice/flow/recovery/handler_test.go, selfservice/flow/recovery/strategy.go, selfservice/flow/verification/error_test.go, selfservice/flow/verification/handler_test.go, selfservice/flow/verification/strategy.go, selfservice/strategy/code/strategy_recovery.go, selfservice/strategy/code/strategy_recovery_test.go, selfservice/strategy/code/strategy_test.go, selfservice/strategy/code/strategy_verification.go, selfservice/strategy/link/strategy_recovery.go, selfservice/strategy/link/strategy_recovery_test.go, selfservice/strategy/link/strategy_test.go, selfservice/strategy/link/strategy_verification.go, spec/api.json, spec/swagger.json
=> chore: clarify documentation on code strategy payloads

contrib/quickstart/kratos/cloud/kratos.yml, contrib/quickstart/kratos/email-password/kratos.yml, contrib/quickstart/kratos/webauthn/kratos.yml, quickstart.yml
=> fix: bump quickstart version

.github/workflows/ci.yaml, persistence/sql/persister.go, persistence/sql/persister_cleanup_test.go, persistence/sql/persister_sessiontokenexchanger.go, selfservice/flow/login/error.go, selfservice/flow/login/handler.go, selfservice/flow/login/hook.go, selfservice/flow/registration/error.go, selfservice/flow/registration/hook.go, selfservice/hook/session_issuer.go, selfservice/sessiontokenexchange/persistence.go, session/manager.go, session/manager_http.go, session/session.go, test/e2e/playwright.config.ts, test/e2e/profiles/kratos.base.yml
=> test: run Playwright in CI

driver/config/config.go, driver/config/config_test.go, driver/config/stub/.kratos.oauth2_provider.yaml, embedx/config.schema.json, hydra/fake.go, selfservice/flow/login/flow.go, selfservice/flow/login/handler.go, selfservice/flow/login/handler_test.go, selfservice/strategy/password/op_login_test.go, test/e2e/cypress/integration/profiles/oidc-provider/login.spec.ts, test/e2e/cypress/integration/profiles/oidc-provider/registration.spec.ts, test/e2e/cypress/support/config.d.ts, test/e2e/profiles/oidc-provider/.kratos.yml, test/e2e/profiles/oidc-provider/hydra.jsonnet, test/e2e/profiles/oidc-provider/identity.traits.schema.json
https://github.com/ory/network/issues/264
With `oauth2_provider.return_to_enabled = true` the following is possible:
1. Login flow switch to Registration flow, return to OAuth2 provider
2. Login flow switch to Recovery flow to Settings flow, return to OAuth2 provider
An end-user following a login flow from a Single Sign On portal to the OAuth2 provider (Hydra) will always be redirected back to the provider (Hydra) after performing a more complex flow, such as switching from `login` to `registration` or `recovery` flow in Kratos. The OAuth2 provider can then complete the flow and redirect the user accordingly.
**Note**: The provider (Hydra) URL will also need to be added to Kratos's `selfservice.allowed_return_urls` configuration. Any `return_to` parameters supplied before the login …
=> feat: return to oauth flow after switching from login to other flows

selfservice/strategy/oidc/provider_linkedin.go
LinkedIn Social Login shows the oryapis.com URL as the redirect target in the UI to the user, even when a custom domain is configured. 
This works correctly on other social login providers. This PR points the flow to the right domain.
the changes.
works.
Reported in Community Slack
=> fix: use the correct redirect_uri for linkedin social login

internal/client-go/api_frontend.go, internal/httpclient/api_frontend.go, selfservice/flow/logout/handler.go, spec/api.json, spec/swagger.json
https://github.com/ory/sdk/issues/255 `updateLogOutFlow` for go SDK doesn't work because there is no way to pass cookie.
Also reported in slack
https://ory-community.slack.com/archives/C02MR4DEEGH/p1683790647078969
Follow https://github.com/ory/kratos/pull/2454 for fixing
the changes.
works.
It is blocking my team from implementing logout, appreciate if this could be fix
=> fix: add cookie for updateLogoutFlow

.schema/openapi/patches/identity.yaml, Makefile, examples/go/identity/get/main.go, identity/.snapshots/TestHandler-suite=create_and_update-case=should_get_identity_with_credentials-case=should_get_identity_with_password_and_webauthn_credentials_included.json, identity/.snapshots/TestHandler-suite=create_and_update-case=should_get_identity_with_credentials-case=should_get_identity_with_password_credentials_included.json, identity/.snapshots/TestHandler-suite=create_and_update-case=should_get_identity_with_credentials-case=should_get_identity_without_credentials_included.json, identity/.snapshots/TestWithDeclassifiedCredentials-case=include-multi-credential=oidc.json, identity/.snapshots/TestWithDeclassifiedCredentials-case=include-multi-credential=password.json, identity/.snapshots/TestWithDeclassifiedCredentials-case=include-multi-credential=webauthn.json, identity/.snapshots/TestWithDeclassifiedCredentials-case=include-webauthn-credential=oidc.json, identity/.snapshots/TestWithDeclassifiedCredentials-case=include-webauthn-credential=password.json, identity/.snapshots/TestWithDeclassifiedCredentials-case=include-webauthn-credential=webauthn.json, identity/.snapshots/TestWithDeclassifiedCredentials-case=no-include-credential=oidc.json, identity/.snapshots/TestWithDeclassifiedCredentials-case=no-include-credential=password.json, identity/.snapshots/TestWithDeclassifiedCredentials-case=no-include-credential=webauthn.json, identity/credentials.go, identity/credentials_test.go, identity/handler.go, identity/handler_test.go, identity/identity.go, identity/identity_test.go, spec/api.json, spec/swagger.json
Closes https://github.com/ory-corp/cloud/issues/4484
=> feat: support exporting of all credential types

selfservice/strategy/oidc/.schema/link.schema.json, selfservice/strategy/oidc/.schema/settings.schema.json, selfservice/strategy/oidc/provider.go, selfservice/strategy/oidc/strategy_login.go, selfservice/strategy/oidc/strategy_registration.go, selfservice/strategy/oidc/strategy_settings.go, selfservice/strategy/oidc/strategy_settings_test.go, selfservice/strategy/oidc/strategy_test.go
Documentation:
- https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest
- https://developers.google.com/identity/openid-connect/openid-connect#prompt
Documentation added here: https://github.com/ory/docs/pull/1410
Fixes https://github.com/ory/kratos/issues/2709
the changes.
works.
=> feat: handle 'prompt' upstream parameter during OIDC flow

.docker/Dockerfile-build, .github/workflows/cve-scan.yaml, Makefile
the changes.
works.
- Update CVE scanners
- Use proper image for scans, instead of a dummy one
- Update system versions
- Dockerfile good practices
=> chore: update security scanners

selfservice/flow/login/hook.go
=> fix: missing id for login event

persistence/sql/persister_verification.go, selfservice/strategy/code/verification_code.go
=> fix: add error checking when creating verification code

identity/extension_recovery.go, identity/extension_verify.go, identity/handler_test.go, test/e2e/cypress/integration/profiles/mfa/totp.spec.ts
Fixes https://github.com/ory/kratos/issues/3187
Fixes https://github.com/ory/kratos/issues/3289
Fixes https://github.com/ory/network/issues/273
=> fix: properly normalize uppercase mail addresses

x/http_secure_redirect.go
Fixes [this alert](https://grafana-europe-cmc.production.oryapis.com/explore?orgId=1&left=%7B%22datasource%22:%22ory_datasource_loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22kratos%5C%22,source_cluster%3D%5C%22OWC%5C%22,source_location%3D%5C%22europe-west1%5C%22%7D%20%7C%20json%20%7C%20__error__%21%3D%5C%22JSONParserErr%5C%22,%20level%3D%60error%60,%20http_response_status_code%3D~%605..%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22ory_datasource_loki%22%7D,%22editorMode%22:%22code%22,%22maxLines%22:200%7D%5D,%22range%22:%7B%22from%22:%221687343471791%22,%22to%22:%221687347071791%22%7D%7D).
=> fix: return HTTP 400 instead of 500 for bad query parameters

persistence/sql/migrations/sql/20230619000000000001_sessions_add_sorted_indices.down.sql, persistence/sql/migrations/sql/20230619000000000001_sessions_add_sorted_indices.mysql.down.sql, persistence/sql/migrations/sql/20230619000000000001_sessions_add_sorted_indices.mysql.up.sql, persistence/sql/migrations/sql/20230619000000000001_sessions_add_sorted_indices.up.sql, persistence/sql/persister_session.go, session/handler_test.go
Fixes https://github.com/ory/network/issues/295
Fixes https://github.com/ory/kratos/issues/3307#issuecomment-1592599770
the changes.
works.
=> feat: order the list of identity sessions by authenticated_at

persistence/sql/persister_session.go, selfservice/flow/login/hook.go, selfservice/hook/session_issuer.go
=> fix: add missing SessionIssued event for api flows

.github/workflows/ci.yaml, test/e2e/run.sh
The `@ory/integrations` package has a peer dependency on `@ory/client`. But since we use the AX to test Kratos we sometimes need the `@ory/client` to be generated based on an open PR in Kratos. This then creates versions such as `v1.1.39-alpha.0`. The `@ory/integrations` package uses a version >= `v1.1.39` which means that our alpha version is less (<) than the required. 
We have a couple of options:
1. Remove the peer dependency requirement from `@ory/integrations`.
2. Make it more lax in version numbers `>=v1.1.30`
3. Install peer deps with `--legacy-peer-deps` …
=> fix: install kratos-selfservice-ui-node peer deps

internal/client-go/api_frontend.go, internal/httpclient/api_frontend.go, selfservice/flow/logout/handler.go, selfservice/flow/logout/handler_test.go, spec/api.json, spec/swagger.json, test/e2e/cypress/integration/profiles/email/logout/success.spec.ts, test/e2e/cypress/integration/profiles/mfa/lookup.spec.ts, test/e2e/cypress/integration/profiles/mfa/mix.spec.ts, test/e2e/cypress/support/commands.ts, test/e2e/cypress/support/index.d.ts
https://github.com/ory/kratos/issues/3100
the changes.
works.
=> feat: add return_to parameters to the `createLogout` handler

session/manager_http.go
=> fix: remove duplicate SessionIssued event

session/manager_http.go
=> fix: reintroduce ExpandAll

cmd/clidoc/main.go, selfservice/strategy/code/.snapshots/TestAdminStrategy-case=form_should_not_contain_email_field_when_creating_recovery_code.json, selfservice/strategy/code/.snapshots/TestRecovery-description=should_set_all_the_correct_recovery_payloads_after_submission.json, selfservice/strategy/code/.snapshots/TestVerification-description=should_set_all_the_correct_verification_payloads_after_submission.json, selfservice/strategy/code/strategy_recovery.go, selfservice/strategy/code/strategy_verification.go, selfservice/strategy/totp/.snapshots/TestCompleteSettings-case=device_setup_is_available_when_identity_has_no_totp_yet.json, text/id.go, text/id_test.go, text/message_node.go
The text for verification code input should be `Verification code` not `Verify code`.
the changes.
works.
=> fix: update correct typo

.schemastore/config.schema.json
Fixes https://github.com/ory/kratos/issues/3392
the changes.
works.
=> fix: remove requirement for smtp section

courier/http.go
Closes #3399
the changes.
works.
=> fix: accept all 200 responses as OK in courier

identity/credentials.go, identity/manager_test.go
closes #1889 
Somehow I could not reproduce the second case with the verified address, probably it is fixed already by accident. Added a test though.
=> fix: false-positives for requiring re-authentication on update

test/e2e/cypress/helpers/httpbin.ts, test/e2e/cypress/helpers/oauth2.ts, test/e2e/cypress/integration/profiles/oidc-provider/login.spec.ts, test/e2e/cypress/integration/profiles/oidc-provider/mfa.spec.ts, test/e2e/cypress/integration/profiles/oidc-provider/registration.spec.ts, test/e2e/run.sh
This should deflake the e2e tests a bit.
the changes.
works.
=> chore: use hosted httpbin in e2e tests

persistence/sql/migrations/sql/20230811000000000001_verification_add_oauth2_login_challenge.down.sql, persistence/sql/migrations/sql/20230811000000000001_verification_add_oauth2_login_challenge.up.sql, selfservice/flow/flow.go, selfservice/flow/registration/flow.go, selfservice/flow/registration/hook.go, selfservice/flow/registration/hook_test.go, selfservice/flow/verification/flow.go, selfservice/flow/verification/handler.go, selfservice/hook/verification.go, session/handler.go
=> fix: accept login_challenge after verification

cmd/clidoc/main.go, driver/config/config.go, embedx/config.schema.json, identity/handler_test.go, identity/manager.go, identity/manager_test.go, identity/stub/manager.schema.json, schema/errors.go, selfservice/flow/registration/error.go, selfservice/flow/registration/hook.go, selfservice/flow/settings/hook.go, selfservice/strategy/oidc/strategy.go, selfservice/strategy/password/registration_test.go, selfservice/strategy/webauthn/registration_test.go, spec/api.json, test/e2e/cypress/integration/profiles/email/registration/errors.spec.ts, test/e2e/cypress/support/config.d.ts, test/e2e/profiles/email/.kratos.yml, text/id.go, text/message_validation.go
When trying to sign up with email+password when that email has previously been used with GitHub SSO:
When trying to sign up with the same email+password twice:
=> feat: provide login hints when registration fails due to duplicate credentials/addresses

identity/error_test.go, identity/handler.go, identity/manager.go
This is a quick fix to avoid returning status code 500 when attempting to create a new identity which conflicts with an existing one.
As a follow-up, we should improve the diagnostics in the response.
=> fix: don't return 500 on conflict for POST /admin/identities

selfservice/strategy/code/strategy_recovery.go, selfservice/strategy/code/strategy_recovery_test.go, selfservice/strategy/link/strategy_recovery.go, selfservice/strategy/link/strategy_recovery_test.go
If the response to a flow-interrupting, after recovery webhook is `4xx` or `5xx`, the recovery flow should fail and no session should be issued.
Fixes #3193
the changes.
works.
=> fix: Run post recovery hook before storing the session and issuing a cookie

selfservice/strategy/oidc/strategy_registration.go, selfservice/strategy/oidc/strategy_test.go, selfservice/strategy/oidc/stub/oidc.hydra.jsonnet, selfservice/strategy/oidc/stub/registration-verifiable-email.schema.json
=> feat: allow marking OIDC provider-verified addresses as verified during registration

persistence/sql/migrations/sql/20230823000000000001_verification_add_oauth2_login_challenge_params.down.sql, persistence/sql/migrations/sql/20230823000000000001_verification_add_oauth2_login_challenge_params.mysql.up.sql, persistence/sql/migrations/sql/20230823000000000001_verification_add_oauth2_login_challenge_params.sqlite.up.sql, persistence/sql/migrations/sql/20230823000000000001_verification_add_oauth2_login_challenge_params.up.sql, selfservice/flow/verification/flow.go, selfservice/flow/verification/handler.go, selfservice/flow/verification/handler_test.go, selfservice/hook/verification.go, session/session.go
This fixes a bug in the session lookup after the verification hook ran and the OIDC challenge needs to be accepted.
Rather than looking up the session in the DB, we now pass along all information (session ID, identity ID, and AMR) to the verification hook so that the hook has all information to accept the login challenge on its own terms.
I verified that the E2E tests on Cloud pass with this change.
the changes.
works.
=> fix: verificaton after registration

selfservice/strategy/oidc/strategy_registration.go, selfservice/strategy/oidc/strategy_test.go
This addresses an oversight where emails returned from Jsonnet mappers weren't properly normalized. In case one contained any uppercase letters, resulting verifiable address wouldn't be marked as verified.
Followup to #3445 / #3448. Can be reproduced by registering with a provider that returns denormalized emails (see the new test case).
the changes.
works.
My bad :sweat_smile:
=> fix: properly normalize OIDC verified emails

embedx/config.schema.json, session/handler_test.go
=> chore: remove `earliest_possible_extend` default in schema

cmd/clidoc/main.go, selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=passwordless-case=webauthn_button_exists.json, selfservice/strategy/webauthn/login.go, text/message_login.go
Instead of `Sign in with security key` the button now is labeled `Use security key`
=> fix: remove duplicate message ID usage

internal/client-go/model_session.go, internal/httpclient/model_session.go, session/session.go, spec/api.json, spec/swagger.json
The identity is not always available in the session struct, for example when AAL2 is required.
Closes #3461
the changes.
works.
=> fix: mark identity as optional in session struct

selfservice/flow/registration/hook.go, selfservice/flow/verification/handler.go, selfservice/flow/verification/handler_test.go, selfservice/hook/session_issuer.go, selfservice/hook/session_issuer_test.go
This PR fixes an issue where the ID token claims from the identity are empty because the consent screen cannot fetch the session because it was not persisted yet.
To fix this, we now always persist the session when the post-registration hooks are executed. Note that this does not alter the behaviour of giving the session to the client.
=> fix: issue session after verification after registration with OIDC SSO

selfservice/strategy/oidc/.schema/link.schema.json, selfservice/strategy/oidc/provider.go, selfservice/strategy/oidc/strategy_test.go
The Facebook OIDC provider supports an auth_type parameter that
when set to "reauthenticate" will force the user to
reauthenticate (similar to `prompt=login` for other Providers).
the changes.
works.
=> feat: support auth_type param

selfservice/strategy/code/strategy.go, test/e2e/cypress/support/commands.ts
The registration with code method incorrectly returns UI nodes for traits on group `code`. When only the `code` method is enabled, this wouldn't cause a problem in the UI, however, with multiple methods enabled which per default use the `default` group to map methods to the UI, this becomes a problem, since the UI would map duplicate nodes. 
Although this could be changed in the UI consuming the API and would not cause any data submit problems, Kratos should rather stay consistent with using the `default` group with traits on login and registration  flows. …
=> fix: registration code ui nodes group

selfservice/strategy/oidc/provider_apple.go, selfservice/strategy/oidc/provider_apple_test.go, selfservice/strategy/oidc/provider_google.go, selfservice/strategy/oidc/provider_google_test.go, selfservice/strategy/oidc/strategy_helper_test.go
=> feat: add ID Token sign in with Google SDK

embedx/config.schema.json, selfservice/flow/settings/hook.go, selfservice/hook/error.go, selfservice/hook/session_destroyer.go, selfservice/hook/session_destroyer_test.go, selfservice/hook/verification.go, selfservice/hook/verification_test.go, selfservice/hook/web_hook.go, selfservice/hook/web_hook_integration_test.go, selfservice/strategy/password/settings_test.go, test/e2e/cypress/support/config.d.ts, test/schema/fixtures/config.schema.test.success/selfServiceAfterSettingsMethod.full.yaml
Currently, the Kratos system does not automatically log out or invalidate other active sessions when a user changes their password. This poses a significant security risk as it allows potentially unauthorized individuals to maintain access to the account even after the password has been updated.
This PR provides the option to add the `revoke_active_sessions` hook to the actions sections of the selfservice settings.
https://github.com/ory/kratos/issues/3513
the changes.
works.
=> feat: hook to revoke sessions after password changed

internal/client-go/model_continue_with_set_ory_session_token.go, internal/client-go/model_continue_with_verification_ui.go, internal/httpclient/model_continue_with_set_ory_session_token.go, internal/httpclient/model_continue_with_verification_ui.go, selfservice/flow/continue_with.go, selfservice/hook/session_issuer_test.go, spec/api.json, spec/swagger.json
The generation of the `continue_with` items somehow broke, and I am not sure how it ever worked.
Before we generated 
<details>
<summary>Before</summary>
```typescript
/**
* @type ContinueWith
* @export
*/
export declare type ContinueWith = ContinueWithSetOrySessionToken | ContinueWithVerificationUi;
/**
* Indicates that a session was issued, and the application should use this token for authenticated requests
* @export
* @interface ContinueWithSetOrySessionToken
*/
export type ContinueWithSetOrySessionToken {
/**
* Action will always be `set_ory_session_token` set_ory_session_token ContinueWithActionSetOrySessionToken show_verification_ui ContinueWithActionShowVerificationUI
* @type {string}
* @memberof ContinueWithSetOrySessionToken
*/
'action': ContinueWithSetOrySessionTokenActionEnum; …
```
=> fix: wrong continue_with enum declaration

identity/.snapshots/TestHandler-case=should_be_able_to_import_users-without_traits.json, test/schema/fixtures/config.schema.test.success/selfServiceAfterSettings.full.yaml, test/schema/fixtures/config.schema.test.success/selfServiceAfterSettingsAuthMethod.full.yaml
Test failures were introduced in https://github.com/ory/kratos/pull/3519.
Outdated snapshots were caused by merging an outdated branch.
=> fix: schema test errors

embedx/config.schema.json
Updated example for `allowed_return_urls` to include wildcard url.
[Merged PR from Nov 9th 2021](https://github.com/ory/kratos/pull/1528) for context.
None.
the changes.
works.
=> docs: update allowed_return_urls examples in config.schema.json to include wildcard

selfservice/strategy/code/strategy.go, selfservice/strategy/code/strategy_login_test.go, selfservice/strategy/code/strategy_registration_test.go, test/e2e/cypress/integration/profiles/code/login/error.spec.ts, test/e2e/cypress/integration/profiles/code/login/success.spec.ts, test/e2e/cypress/integration/profiles/code/registration/error.spec.ts, test/e2e/cypress/integration/profiles/code/registration/success.spec.ts, test/e2e/cypress/support/commands.ts, test/e2e/cypress/support/index.d.ts, test/e2e/run.sh
Adds Go tests and E2E cypress tests to the native login and registration via code APIs. 
Improves the UX of login and registration by hiding the input fields on the second (`email_sent`) state. This preserves the nodes in the API allowing the consumer to still display the fields however they would like. In the Account Experience these fields won't show up to the end-user and will be submitted along with the code.
the changes.
works.
=> feat: one-time code native flows

.schema/openapi/patches/session.yaml, spec/api.json
I found an issue in the [current client open api spec (v1.2.10)](https://github.com/ory/sdk/blob/master/spec/client/v1.2.10.json).
Line 5740 - ref: "#/components/schemas/sessionAuthenticationMethod". There is the method "code" missing. For the new one-time code passwordless feature.
the changes.
works.
=> fix: add value code to authentication method enum

driver/registry.go, driver/registry_default.go, internal/driver.go, persistence/sql/persister.go
The migration logging is really noisy. This disables it in the go unit/integration tests. Not sure how we can display errors that occur during migration, though.
the changes.
works.
=> chore: reduce logging in go tests

cmd/daemon/serve.go
The admin API is generally expected to require longer timeouts, for example during bulk identity import. 
Previously, we used `ory/graceful`'s default write timeout (10s). That has a couple of problems:
1. 10s is too short for expensive operations such as bulk identity import.
2. The server-level timeouts of `http.Server` (`WriteTimeout` etc) work in surprising ways. See https://github.com/golang/go/issues/59602. After reaching the timeout, the connection is closed and no more writes will be transported to the client. But there is no way to detect this from the handler. Writing to the `http.ResponseWriter` returns no error, and the request context is not canceled. So until now, for long requests, we would just keep truckin' and perform all the work and finally write a `200 OK` response. …
=> fix: increase connection-level timeouts and shutdown timeouts

identity/.snapshots/TestHandler-case=should_be_able_to_import_users-with_not-normalized_email.json, identity/.snapshots/TestHandler-suite=PATCH_identities-case=success-assert=identity_0.json, identity/handler.go, identity/handler_test.go
Emails that contained upper-case characters would be overwritten by the identity schema extension runner, because there all emails are lower-cased.
=> fix: lower-case recovery & verification emails on import

courier/handler.go, identity/handler.go, identity/handler_test.go, persistence/sql/identity/persister_identity.go, schema/handler.go, selfservice/hook/show_verification_ui.go, session/handler.go, x/pagination.go
This is much less brittle when Kratos is deployed behind a proxy which rewrites the Host header. Example from Ory Network: before this change, when the initial request was made to a CNAME, the Link header of the response contains `<slug>.projects.oryapis.com`.
Another problem with the previous solution was that the `/admin` prefix would occasionally be stripped from the Link header in the response. For example, the first request would go to `/admin/identities?page=0`, and the Link header would contain `</identities?page=1>; rel="next"`.
Now, we always return a modified version of the exact path that was requested. Should solve both of these issues.
=> fix: always return relative URLs in the Link header for pagination

driver/config/config.go, driver/config/config_test.go, selfservice/strategy/code/strategy_login.go, selfservice/strategy/code/strategy_login_test.go, selfservice/strategy/code/stub/code.identity.schema.json, selfservice/strategy/password/stub/registration.schema.json, test/e2e/cypress/integration/profiles/code/login/error.spec.ts, test/e2e/profiles/code/.kratos.yml
When the Identity schema contains the `code` extension, a `code` credential is automatically applied on other authentication methods, such as registering with password.
For old accounts that registered before the `code` extension, they will need to automatically migrate to have the credential added to their account. For this there is a fallback mechanism that automatically kicks in.
Since old and new accounts should share the same behavior, I have removed the `passwordless_login_fallback_enabled` config key, since its use is redundant and will only prevent old accounts from also logging in with one-time code. …
=> fix: auto migrate old accounts to use code credential

selfservice/strategy/oidc/strategy.go
Returning anything else here may cause Kratos to respond with two concatenated JSON objects: new login flow with actual error message as the first one and a very confusing '500, aborted registration hook execution' as the second one.
To reproduce this bug on current `master`:
1. Launch Kratos where default identity has email as identifier and allows registration via password and some OIDC provider (e.g. Google).
2. Register using password, providing the same email as the one from the Google account that will be used in the next step.
3. Try to register using Google account with matching email, using API flow and sending `id_token` in the request body to avoid webview/redirections.
This will trigger the code path designed to handle …
=> fix: consider OIDC registration flows errored with duplicate credential to be completed by strategy

hydra/fake.go, internal/testhelpers/selfservice_login.go, internal/testhelpers/selfservice_registration.go, selfservice/flow/registration/flow_test.go, selfservice/flow/registration/handler.go, selfservice/flow/registration/handler_test.go, selfservice/strategy/password/op_helpers_test.go, selfservice/strategy/password/op_login_test.go, selfservice/strategy/password/op_registration_test.go, test/e2e/cypress/integration/profiles/oidc-provider/registration.spec.ts
https://github.com/ory-corp/cloud/issues/5493
Using `propt=registration` on an OAuth2 Hydra login flow, the request is routed to the Kratos registration handler. This handler immediately redirects to the logout flow when there is an already existing session, which fails and ends up at the base `/welcome` page on the Account Experience (AX). 
This PR adds the functionality of accepting the login request in the registration handler if the user has a session and if the hydra `skip=true` is in the login request. 
When the `skip=false` is set, the request is redirected to the login flow with the login_challenge, which will complete the flow normally.
vulnerability. If this pull request …
=> fix: registration should accept hydra login

courier/courier.go, courier/courier_dispatcher.go, driver/config/config.go, embedx/config.schema.json
Allows one to parametrize how many messages the courier will fetch and how often it will fetch messages.
the changes.
works.
=> feat: parametrize courier worker

courier/courier.go, courier/courier_dispatcher.go, courier/courier_dispatcher_test.go, courier/handler_test.go, courier/message.go, courier/message_test.go, courier/persistence.go, courier/test/persistence.go, persistence/sql/persister_courier.go, selfservice/hook/verification_test.go, selfservice/strategy/code/code_sender_test.go, selfservice/strategy/link/sender.go, selfservice/strategy/link/sender_test.go, selfservice/strategy/profile/strategy_test.go
The setup code was simplified.
Also, the `courier.MessageStatusProcessing` was removed.
The processing state was intended as a kind of lock to allow running multiple couriers. However, in practice that did not really work because multiple instance would run into transaction conflicts a lot, because they would always try to select & update the same rows. Further, there was no "lock release" strategy, but once the lock was acquired and the worker died without finishing the message, it would never be picked up again. Removing this state means less database writes, and that the worker would pick up half-processed messages.
As a follow-up, we can implement a proper sharding strategy so multiple workers can work in parallel without conflicts or duplicates.
=> chore: simplify courier

corpx/faker.go, courier/handler_test.go, courier/test/persistence.go, go.mod, go.sum, identity/handler_test.go, identity/test/pool.go, internal/testhelpers/handler_mock.go, internal/testhelpers/selfservice.go, persistence/sql/persister_registration_code.go, selfservice/flow/login/flow_test.go, selfservice/flow/login/test/persistence.go, selfservice/flow/recovery/test/persistence.go, selfservice/flow/registration/flow_test.go, selfservice/flow/registration/handler_test.go, selfservice/flow/registration/test/persistence.go, selfservice/flow/settings/error_test.go, selfservice/flow/settings/flow_test.go, selfservice/flow/settings/test/persistence.go, selfservice/flow/verification/test/persistence.go, selfservice/hook/session_destroyer_test.go, selfservice/strategy/code/test/persistence.go, selfservice/strategy/link/test/persistence.go, session/handler_test.go, session/test/persistence.go, ui/node/node_test.go
=> chore: fix github.com/bxcodec/faker/v3 is deprecated

selfservice/strategy/oidc/strategy.go, selfservice/strategy/oidc/strategy_login.go, selfservice/strategy/oidc/strategy_registration.go, selfservice/strategy/oidc/strategy_settings_test.go, test/e2e/cypress/integration/profiles/oidc/settings/success.spec.ts
Whenever an user is asked to reauthenticate (e.g. because they wish to execute settings flow touching their credentials and their session is no longer privileged) they are asked to provide their credentials again. The forced-refresh login flow generated for such cases already excludes some strategies that are enabled in Kratos but cannot be used to authenticate as current identity, and for example the form presented to the user will not have a password field if the identity does not have a password credential.
This, however, does not currently apply to OIDC providers; the user will always see the full set even if some of them can't be used to sign in as current identity. This change causes forced refresh login flows to also omit irrelevant OIDC providers in generated form in order to …
=> fix: omit irrelevant OIDC providers in forced refresh login flows

embedx/config.schema.json, selfservice/strategy/oidc/provider_apple.go, selfservice/strategy/oidc/provider_apple_test.go, selfservice/strategy/oidc/provider_config.go, selfservice/strategy/oidc/provider_google.go, selfservice/strategy/oidc/provider_google_test.go, selfservice/strategy/oidc/strategy_helper_test.go, selfservice/strategy/oidc/token_verifier.go
Fixes https://github.com/ory/network/issues/343
the changes.
works.
=> feat: allow additional id token audiences

internal/testhelpers/session.go, selfservice/strategy/oidc/strategy.go, selfservice/strategy/oidc/strategy_test.go, session/handler_test.go
This change ensures that CSRF middleware is ignored on `/self-service/oidc/callback/apple` (previously it was only exempted).
After a user authenticates on Apple, Apple redirects the user back to Kratos using a form POST. Since this is a POST, the CSRF cookie is not passed (since the cookie's SameSite attribute is set to Lax). This causes Kratos to add a different CSRF cookie.
While this doesn't break the registration flow itself, it causes a problem if we want to send the user back to the original login flow. In some cases, we may want to do this to cancel the registration and allow the user to log in with different credentials. It may be important to maintain the existing login flow in case the login originated from an OAuth2 client via Hydra instead of simply creating a new login flow. …
=> fix: ignore CSRF middleware on Apple OIDC callback

selfservice/strategy/code/strategy_recovery.go, selfservice/strategy/code/strategy_recovery_test.go, selfservice/strategy/code/strategy_verification.go, selfservice/strategy/code/strategy_verification_test.go
Closes https://github.com/ory-corp/cloud/issues/5648
the changes.
works.
=> fix: don't return nil if code is invalid

courier/message.go, persistence/sql/migrations/sql/20240119094628000000_sessions_created_at_index.down.sql, persistence/sql/migrations/sql/20240119094628000000_sessions_created_at_index.mysql.down.sql, persistence/sql/migrations/sql/20240119094628000000_sessions_created_at_index.up.sql, persistence/sql/persister_session.go, session/handler.go, session/handler_test.go, session/session.go, session/test/persistence.go, x/pagination.go
=> feat: order sessions by created_at

internal/client-go/api_identity.go, internal/httpclient/api_identity.go, selfservice/strategy/link/strategy_recovery.go, spec/api.json, spec/swagger.json
The parameter is already handled properly, it was just missing in the API spec.
as reported by @francesconi
=> fix: add return_to parameter to API spec of createRecoveryLinkForIdenity

selfservice/strategy/oidc/provider_microsoft.go, selfservice/strategy/oidc/provider_userinfo_test.go
This reverts commit 4a7bcc9322be37e6fd141e411bd65e3977eeb692.
the changes.
works.
=> revert: feat: extend Microsoft Graph API capabilities (#3609)

identity/handler.go, identity/handler_test.go, identity/pool.go, internal/client-go/api_identity.go, internal/httpclient/api_identity.go, spec/api.json, spec/swagger.json
Fixes #3342
the changes.
works.
=> feat: have the /admin/identities list call return all fields

internal/client-go/api_frontend.go, internal/httpclient/api_frontend.go, selfservice/flow/login/handler.go, spec/api.json, spec/swagger.json
=> fix: add sms mfa via parameter to spec

cipher/chacha20.go, driver/registry_default.go, identity/.snapshots/TestWithDeclassifiedCredentials-case=oidc-credential=oidc.json, identity/.snapshots/TestWithDeclassifiedCredentials-case=oidc-credential=password.json, identity/.snapshots/TestWithDeclassifiedCredentials-case=oidc-credential=webauthn.json, identity/handler_test.go, identity/identity.go, identity/identity_test.go
Should solve 500s on identity details, if the identity was registered using native social sign in flows, and the OIDC credential doesn't contain tokens.
the changes.
works.
=> fix: ignore decrypt errors in WithDeclassifiedCredentials

identity/handler_test.go
=> fix: test assertions on declassifying OIDC tokens

continuity/container.go, selfservice/flow/settings/flow.go, selfservice/flow/settings/handler_test.go, selfservice/strategy/password/settings_test.go, selfservice/strategy/profile/strategy_test.go
=> fix: show error page on identity mismatch

internal/client-go/go.sum, selfservice/strategy/oidc/strategy.go
Sometimes there are issues with mapping the claims from a SSO provider to an identity trait. This change adds the claims that we get back to the event, so that we can better debug these issues.
the changes.
works.
=> feat: log claims

internal/client-go/go.sum, selfservice/strategy/oidc/provider_x.go
Improves the "Log in with X" experience by not asking the user to re-authenticate every time.
the changes.
works.
=> feat: use authenticate endpoint for x

driver/registry_default_hooks.go, embedx/config.schema.json, selfservice/flow/login/flow.go, selfservice/flow/login/hook.go, selfservice/flow/login/session.go, selfservice/hook/hooks.go, selfservice/hook/verification.go, selfservice/hook/verification_test.go
=> feat: add verification hook to login flow

internal/client-go/go.sum, persistence/sql/identity/persister_identity.go, persistence/sql/migrations/sql/20240318143139000000_drop_identity_search_index.down.sql, persistence/sql/migrations/sql/20240318143139000000_drop_identity_search_index.postgres.down.sql, persistence/sql/migrations/sql/20240318143139000000_drop_identity_search_index.postgres.up.sql, x/sql.go, x/sql_test.go
The trigram GIN index takes up a significant amount of database storage. Fuzzy search should instead be build using a dedicated external service. This will allow indexing other traits as well, based on needs.
=> fix: drop trigram index on identifiers

internal/client-go/go.sum, selfservice/strategy/code/hook.jsonnet, selfservice/strategy/code/strategy_recovery.go, selfservice/strategy/code/strategy_recovery_test.go, selfservice/strategy/oidc/strategy.go
This fixes some bugs where we didn't yet copy around the transient data hard enough.
https://github.com/ory-corp/cloud/issues/6067
the changes.
works.
=> fix: passing transient payloads

selfservice/flow/login/flow.go, selfservice/flow/login/flow_test.go, selfservice/flow/login/handler.go, selfservice/flow/login/handler_test.go
Use strconv.ParseBool to accept multiple "truthy" values for the `refresh` and `return_session_token_exchange_code` query parameters when creating a new login flow.
For some SDKs (e.g.: Python), these stringification of booleans is not user-controlled and these endpoints could not be used fully due to the backend ignoring any value other than `true` (all lowercase).
Closes #3839.
#3839
the changes.
works.
None
=> fix: tolerate more "truthy" values when creating new flows

quickstart.yml
Closes https://github.com/ory/kratos/issues/3828
the changes.
works.
=> fix: add missing env vars to set up guide

internal/client-go/go.sum, selfservice/hook/hooktest/web_hook_test_server.go, selfservice/strategy/code/hook.jsonnet, selfservice/strategy/code/strategy_recovery_test.go, selfservice/strategy/oidc/strategy_login.go, selfservice/strategy/oidc/strategy_test.go
This fixes a bug where we did not put the transient payload into the continuity container on OIDC logins, which caused OIDC login flows to lose the transient payload.
Also, this PR adds more webhook tests in general and a handy `hooktest` package to test webhooks.
the changes.
works.
=> fix: webhook transient payload in OIDC login flows

session/handler_test.go
=> test: deflake session test

selfservice/hook/stub/test_body.jsonnet, selfservice/hook/web_hook.go, selfservice/hook/web_hook_integration_test.go
=> feat: add session to post login webhook

persistence/sql/persister_session.go
* [fix: don't update immutable columns when upserting sessions](https://github.com/ory/kratos/commit/452122930b82284fb7d79bf059ea821ab134fb2f)
* [fix: don't emit SessionIssued and SessionChanged events multiple times when retrying database transactions](https://github.com/ory/kratos/commit/bbd7447c275c3e1fca046f951b9362a64c8db881)
=> feat: tweaks to UpsertSessions

identity/manager.go, identity/manager_test.go, internal/client-go/go.sum, selfservice/strategy/oidc/strategy_test.go, selfservice/strategy/webauthn/registration_test.go, session/handler_test.go, text/message_validation.go
Previously, we only returned one conflicting credential type in the duplicate credential error. Now, we include all conflicting credential types.
the changes.
works.
=> fix: include all credentials in the duplicate credential hint

identity/manager.go, identity/manager_test.go, internal/client-go/go.sum, persistence/sql/identity/persister_identity.go, persistence/sql/migrations/sql/20240425095000000000_identity_credentials_fix_user_handle_index.cockroach.down.sql, persistence/sql/migrations/sql/20240425095000000000_identity_credentials_fix_user_handle_index.cockroach.up.sql, persistence/sql/migrations/sql/20240425095000000001_identity_credentials_fix_user_handle_index.cockroach.down.sql, persistence/sql/migrations/sql/20240425095000000001_identity_credentials_fix_user_handle_index.cockroach.up.sql, selfservice/strategy/oidc/strategy_test.go, selfservice/strategy/passkey/passkey_registration_test.go, selfservice/strategy/webauthn/registration_test.go, text/message_validation.go
This fixes two minor bugs
- uses an improved index for getting the credential identifier from the user handle
- checks if the password hash is set before suggesting it as a credential identifier on duplicate credential errors
the changes.
works.
=> fix: db index and duplicate credentials error

continuity/manager.go, continuity/manager_cookie.go, continuity/manager_options_test.go, continuity/manager_test.go, continuity/persistence.go, continuity/test/persistence.go, internal/client-go/go.sum, persistence/sql/persister_continuity.go, selfservice/strategy/oidc/strategy.go, selfservice/strategy/oidc/strategy_test.go, x/cookie.go
=> fix(oidc): grace period for continuity container on oidc callbacks

contrib/quickstart/kratos/email-password/kratos.yml, contrib/quickstart/kratos/passkey/kratos.yml, contrib/quickstart/kratos/phone-password/kratos.yml, contrib/quickstart/kratos/webauthn/kratos.yml
Change the default return url for Quickstarts to welcome page instead of site root.
_Issue:_ Sign In redirects to root page of the self service ui.
_More context:_ The Kratos SelfService UI used by the Quickstarts does not serve a root page but instead returns a json error: `{"error":{"code":404,"status":"Not Found","message":"Requested url does not match any rules"}}`.
Steps to reproduce:
1. Start Kratos and Oathkeeper. Example: `docker compose -f quickstart.yml -f quickstart-oathkeeper.yml up --build --force-recreate` 
2. Go to the welcome page and then Sign Up.
3. Upon completing account creation you are redirected to site root and presented with the json "Not Found" error.
4. Go to the welcome page after creating an account and Sign Out.
5. Go to the welcome page and Sign In. Upon …
=> fix: change return urls in quickstarts

.github/workflows/ci.yaml, test/e2e/cypress/integration/profiles/code/login/success.spec.ts, test/e2e/cypress/integration/profiles/code/registration/success.spec.ts, test/e2e/cypress/integration/profiles/oidc/login/success.spec.ts, test/e2e/cypress/integration/profiles/two-steps/registration/code.spec.ts, test/e2e/cypress/support/commands.ts, test/e2e/profiles/code/.kratos.yml, test/e2e/run.sh
=> test: resolve flaky e2e tests

courier/courier_dispatcher.go, courier/http_channel.go, courier/smtp_channel.go
=> chore: improve courier logging

driver/config/config.go, embedx/config.schema.json, persistence/sql/persister_session.go, session/handler.go, session/persistence.go, session/test/persistence.go, x/events/events.go
This patch improves the performance for extending session lifespans. Lifespan extension is tricky as it usually is part of the middleware of Ory Kratos consumers. As such, it is prone to transaction contention when we read and write to the same session row at the same time (and potentially multiple times).
To address this, we:
1. Introduce a locking mechanism on the row to reduce transaction contention;
2. Add a new feature flag which toggles returning 204 no content instead of 200 + session.
Be aware that all reads on the session table will have to wait for the transaction to commit before they return a value. This may cause long(er) response times on `/session/whoami` for sessions that are being extended at the same time.
BREAKING CHANGES: Going forward, the `/admin/session/.../extend` …
=> feat: improve session extend performance

embedx/config.schema.json, internal/client-go/go.sum
Organizing this key to be located where all the other login methods are as well which helps with consistency when automating orgs.
the changes.
works.
=> chore: move b2b config to selfservice section

.golangci.yml, cipher/cipher_test.go, cmd/courier/watch_test.go, cmd/hashers/argon2/root.go, courier/template/load_template_test.go, driver/config/config.go, driver/config/config_test.go, driver/config/test_config.go, driver/factory.go, driver/registry_default_test.go, go.mod, hydra/hydra_test.go, internal/driver.go, internal/testhelpers/config.go, internal/testhelpers/network.go, persistence/sql/persister_hmac_test.go, session/test/persistence.go, x/redir_test.go
The new test config provider can now read some test values from the context. This allows more tests to be parallel by ensuring isolation between test runs.
=> test: deflake session extend config side-effect

driver/config/test_config.go, identity/manager_test.go, identity/test/pool.go, internal/client-go/go.sum, internal/driver.go, persistence/sql/persister_cleanup_test.go, persistence/sql/persister_code.go, persistence/sql/persister_errorx.go, persistence/sql/persister_hmac.go, persistence/sql/persister_hmac_test.go, persistence/sql/persister_recovery.go, persistence/sql/persister_test.go, persistence/sql/persister_verification.go, selfservice/flow/recovery/test/persistence.go, selfservice/flow/settings/test/persistence.go, selfservice/flow/verification/test/persistence.go, selfservice/sessiontokenexchange/test/persistence.go, selfservice/strategy/code/test/persistence.go, selfservice/strategy/link/test/persistence.go, session/test/persistence.go
Moving more tests to the context-based test configs, and enabling parallelism everywhere 🎉
=> test: deflake and parallelize persister tests

cipher/cipher_test.go, driver/config/handler_test.go, driver/config/test_config.go, driver/config/testhelpers/config.go, driver/registry_default_test.go, identity/test/pool.go, internal/driver.go, internal/testhelpers/config.go, persistence/sql/persister_hmac_test.go, selfservice/strategy/code/test/persistence.go, selfservice/strategy/link/test/persistence.go, session/test/persistence.go
With this change we can use the context-based test configs server side, e.g. in integration tests.
=> test: enable server-side config from context

internal/client-go/api_identity.go, internal/httpclient/api_identity.go, session/handler.go, spec/api.json, spec/swagger.json
=> feat: clarify session extend behavior

.github/workflows/ci.yaml, .golangci.yml, Makefile, driver/config/config.go, embedx/config.schema.json, identity/credentials_password.go, identity/credentials_password_test.go, internal/client-go/go.sum, selfservice/hook/password_migration_hook.go, selfservice/strategy/password/login.go, selfservice/strategy/password/login_test.go, selfservice/strategy/password/strategy.go
This PR adds a password migration hook to easily migrate passwords for which we do not have the hash.
- For each user that needs to be migrated to Ory Network, a new identity is created with a credential of type `password` with a config of `{"use_password_migration_hook": true}` .
- When a user logs in, the credential identifier and password will be sent to the `password_migration` web hook if all of these are true:
- The user’s identity’s password credential is `{"use_password_migration_hook": true}`
- The `password_migration` hook is configured
- After calling the `password_migration` hook, the HTTP status code will be inspected:
- On 200, we parse the response as JSON and look for `{"status": "password_match"}`. The password credential config will be replaced with the hash of the …
=> feat: password migration hook

driver/config/config.go, driver/config/config_test.go, embedx/config.schema.json
This moves the password migration hook to
```yaml
selfservice:
methods:
password:
config:
migrate_hook:
...
```
=> fix: move password migration hook config

selfservice/flow/login/error.go, selfservice/flow/login/flow.go, selfservice/flow/recovery/error.go, selfservice/flow/recovery/flow.go, selfservice/flow/registration/error.go, selfservice/flow/registration/flow.go, selfservice/flow/settings/error.go, selfservice/flow/settings/flow.go, selfservice/flow/verification/error.go, selfservice/flow/verification/flow.go
`ToLoggerField` no longer panics when used on nil
=> chore: test for null in method receiver

selfservice/strategy/oidc/strategy.go
This adds a fallback to the provider label when trying to register a duplicate identifier with an oidc.
Current error message:
`Signing in will link your account to "test@test.com" at provider "". If you do not wish to link that account, please start a new login flow.`
The label represents an optional label for the UI, but in my case it's always empty. I suggest we fallback to the provider when the label is not present. In case the label is present, the behaviour won't change.
Fallback to provider:
`Signing in will link your account to "test@test.com" at provider "google". If you do not wish to link that account, please start a new login flow.`
vulnerability. If this pull request …
=> fix: add fallback to providerLabel

selfservice/strategy/oidc/strategy_login.go, selfservice/strategy/oidc/strategy_registration.go
=> chore(docs): add google to supported providers in ID Token doc strings

internal/client-go/go.sum, selfservice/flow/settings/handler_test.go, selfservice/strategy/code/strategy_verification.go, selfservice/strategy/idfirst/strategy_login.go, selfservice/strategy/link/strategy_verification.go, selfservice/strategy/lookup/settings.go, selfservice/strategy/lookup/settings_test.go, selfservice/strategy/oidc/strategy_login.go, selfservice/strategy/oidc/strategy_settings.go, selfservice/strategy/passkey/passkey_settings.go, selfservice/strategy/passkey/passkey_settings_test.go, selfservice/strategy/password/login.go, selfservice/strategy/password/registration.go, selfservice/strategy/password/settings.go, selfservice/strategy/profile/strategy.go, selfservice/strategy/profile/two_step_registration.go, selfservice/strategy/totp/settings.go, selfservice/strategy/webauthn/registration.go, selfservice/strategy/webauthn/settings.go, selfservice/strategy/webauthn/settings_test.go
I noticed a nil-pointer dereference panic in `github.com/ory/kratos/selfservice/strategy/code.(*Strategy).handleVerificationError`
The problem really is that the internal API use(d) pointers where it was not necessary, and lacked nil checks elsewhere. This change adds nil checks, and also improves the internal API to avoid pointers when not strictly needed.
=> fix: refactor internal API to prevent panics

go.mod, go.sum
=> fix: downgrade go-webauthn

test/e2e/playwright/models/elements/login.ts, test/e2e/playwright/tests/desktop/identifier_first/code.login.spec.ts, test/e2e/playwright/tests/desktop/identifier_first/password.login.spec.ts, test/e2e/playwright/tests/mobile/app_login.spec.ts
=> test: improve stability of refresh test

selfservice/hook/web_hook.go, selfservice/hook/web_hook_integration_test.go
This enforces an allow list for the request headers sent to a web hook target.
Related to https://github.com/ory-corp/cloud/issues/6181
the changes.
works.
=> fix: filter web hook headers

x/http_secure_redirect.go
=> chore: don't return allowed return URLs

selfservice/flow/settings/hook.go
This PR fixes the SelfServiceMethodUsed attribute in the SettingsSucceeded event, which previously was always empty.
the changes.
works.
=> fix: emit SelfServiceMethodUsed in SettingsSucceeded event

identity/test/pool.go, persistence/sql/identity/persister_identity.go, selfservice/flow/login/hook.go, session/manager_http.go
Instead of re-fetching the credentials later (expensive), we load them only once.
the changes.
works.
=> fix: return credentials in FindByCredentialsIdentifier

selfservice/strategy/code/.schema/login.schema.json, selfservice/strategy/code/.schema/recovery.schema.json, selfservice/strategy/code/.schema/registration.schema.json, selfservice/strategy/code/.schema/verification.schema.json, selfservice/strategy/code/strategy_login.go, selfservice/strategy/code/strategy_login_test.go, selfservice/strategy/code/stub/no-code-id.schema.json, selfservice/strategy/idfirst/.schema/login.schema.json, session/manager_http.go, test/e2e/cypress/integration/profiles/mfa/lookup.spec.ts, test/e2e/cypress/integration/profiles/mfa/settings.spec.ts, test/e2e/cypress/integration/profiles/mfa/totp.spec.ts, test/e2e/cypress/integration/profiles/mfa/webauthn.spec.ts, test/e2e/cypress/integration/profiles/mobile/settings/success.spec.ts, test/e2e/cypress/support/configHelpers.ts, test/e2e/profiles/mfa/.kratos.yml
=> fix: whoami latency

courier/handler_test.go, internal/client-go/go.sum, persistence/sql/identity/persister_identity.go, persistence/sql/persister_courier.go, persistence/sql/persister_session.go, x/err.go
Currently the error returned is similar to `unable to fetch records: ERROR: error in argument for $2: could not parse "1" as type uuid: could not parse "1" as type uuid: uuid: incorrect UUID length: 1 (SQLSTATE 22P02)`.
=> fix: validate page tokens for better error codes

selfservice/flow/login/flow.go, selfservice/flow/login/handler.go, selfservice/strategy/oidc/.snapshots/TestStrategy-case=should_fail_to_register_and_return_fresh_login_flow_if_email_is_already_being_used_by_password_credentials-case=should_fail_registration_id_first_strategy_enabled.json, selfservice/strategy/oidc/strategy.go, selfservice/strategy/oidc/strategy_registration.go, selfservice/strategy/oidc/strategy_test.go
=> fix: don't populate id_first first step for account linking flows

selfservice/flow/verification/flow.go
This fix copies transient payload from registration flow to new verification flow
- [x ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x ] I am following the
- [x ] I have read the [security policy](../security/policy).
- [x ] I confirm that this pull request does not address a security
the changes.
works.
=> fix: transient_payload is lost when verification flow started as part of registration

identity/.snapshots/TestSchemaExtensionCredentials-case=12.json, identity/extension_credentials.go, identity/extension_credentials_test.go, identity/handler_test.go, identity/stub/extension/credentials/code-phone-email.schema.json, internal/client-go/go.sum
Closes #4076
the changes.
works.
=> fix: incorrect append of code credential identifier

identity/manager.go, persistence/sql/identity/persister_identity.go, x/events/events.go
=> feat: emit events in identity persister

identity/handler.go, identity/handler_test.go, identity/pool.go, identity/test/pool.go
We currently return a 500 error if the UUID supplied to the `ids` parameter of the identity list endpoint: 
```json
{
"error": {
"code": 500,
"status": "Internal Server Error",
"request": "fab8e637-d424-90c1-a766-9d71f157b3d8",
"message": "unable to fetch records: ERROR: error in argument for $3: could not parse \"asd\" as type uuid: could not parse \"asd\" as type uuid: uuid: incorrect UUID length: asd (SQLSTATE 22P02)"
}
}
```
the changes.
works.
=> fix: return error if invalid UUID is supplied to ids filter

identity/manager_test.go, persistence/sql/identity/persister_identity.go
The updated_at field in the identities table is not being updated when an identity's traits are modified. This is unexpected behavior because the pop library should automatically update the `updated_at` field when a record is modified.
However, in the current implementation, the identity is being saved with the old `updated_at` timestamp, which causes the pop library to skip updating this field. As a result, the `updated_at` field does not reflect recent changes, which can lead to issues with auditing, synchronization, or downstream systems relying on the correct timestamps for updated data.
The issue arises because the existing code inadvertently preserves the previous updated_at value during the update operation. When saving the identity, the pop library sees that the field is already …
=> fix: explicity set updated_at field when updating identity

selfservice/flow/verification/handler.go, spec/api.json
The idea would be to re-generate the Kratos SDK, so that one can specify a `return_to` URL when creating a Native Verification Flow using the SDK.
the changes.
works.
=> docs: add return_to query parameter to OAS Verification Flow for Native Apps

identity/pool.go, persistence/sql/identity/persister_identity.go
=> chore: override parameters

selfservice/flow/registration/hook.go
When a request is canceled at the wrong point, it can lead to some hooks not being executed.
With this change we ignore context cancelation after the identity was created so that e.g. verification emails or webhooks will always be executed.
the changes.
works.
IMO this is expected behavior so no docs changes should be required.
=> fix: registration post persist hooks should not be cancelable

internal/client-go/go.sum, selfservice/strategy/code/strategy_verification.go, selfservice/strategy/link/strategy_verification.go
Spans in tracing are not correctly nested because of this.
=> fix: pass on correct context during verification

selfservice/flow/login/export_test.go, selfservice/flow/login/hook.go, selfservice/flow/login/hook_test.go, selfservice/flow/settings/handler.go, selfservice/strategy/oidc/strategy_test.go, session/handler.go, session/manager.go, session/manager_http.go, session/manager_http_test.go
Currently account linking happens after the first factor, even when the second factor is required for a session to be issued.
=> fix: account linking should only happen after 2fa when required

identity/pool.go, identity/test/pool.go, persistence/sql/identity/persister_identity.go, x/sync_map.go, x/sync_map_test.go
=> feat: fast add credential type lookups

selfservice/flow/login/handler.go, selfservice/flow/registration/handler.go
Improve the docs to document the usage of the `organization` parameter in native self-service flows.
No code changes are required, as the parameter is processed in hooks which already handle it.
Potentially resolves https://github.com/ory/kratos/issues/4175.
Please let me know if additional work is needed to also update the auto-generated SDKs or the response in the API documentation.
- https://github.com/ory/kratos/issues/4175
the changes.
works.
=> docs: usage of `organization` parameter in native self-service flows

.schemastore/config.schema.json, embedx/config.schema.json, selfservice/strategy/oidc/provider.go, selfservice/strategy/oidc/provider_microsoft.go
In the case of Microsoft, using `sub` as an identifier can lead to problems. Because the use of OIDC at Microsoft is based on an app registration, the content of `sub` changes with every new app registration. `Sub` is therefore not uniquely related to the user. It is therefore not possible to transfer users from one app registration to another without further problems.
https://learn.microsoft.com/en-us/entra/identity-platform/id-token-claims-reference#payload-claims
With the use of `oid` it is possible to identify a user by a unique id.
- #4170 …
=> feat: add oid as subject source for microsoft

driver/config/config.go, driver/registry_default.go, embedx/config.schema.json, x/nosurf.go
Adds a new config flag  for session and all other cookies. Falls back to the previous behavior of using the dev mode to decide if the cookie should be secure or not.
the changes.
works.
=> feat: add explicit config flag for secure cookies

persistence/sql/migrations/sql/20241029153900000001_identities.down.sql, persistence/sql/migrations/sql/20241029153900000001_identities.mysql.down.sql, persistence/sql/migrations/sql/20241029153900000001_identities.mysql.up.sql, persistence/sql/migrations/sql/20241029153900000001_identities.up.sql
https://github.com/ory-corp/cloud/issues/7200
the changes.
works.
=> feat: optimize identity-related secondary indices

selfservice/flow/settings/handler.go, session/handler.go, session/manager.go, session/manager_http.go, session/manager_http_test.go
=> feat: load session only once when middleware is used

hash/hash_comparator.go, internal/client-go/go.sum
=> refactor: hash comparator instantiation

internal/client-go/go.sum, selfservice/flow/login/error.go, selfservice/flow/login/hook.go, selfservice/flow/recovery/error.go, selfservice/flow/recovery/hook.go, selfservice/flow/registration/error.go, selfservice/flow/registration/hook.go, selfservice/flow/settings/error.go, selfservice/flow/settings/hook.go, selfservice/flow/verification/error.go, selfservice/flow/verification/hook.go, selfservice/hook/session_issuer.go, x/events/events.go
Not sure if this covers all the error types we can get, but it should be the majority. We can still add more once we stumble upon them.
=> feat: add failure reason to events

courier/http_channel.go, embedx/config.schema.json, request/builder.go, request/builder_test.go, request/config.go, selfservice/hook/password_migration_hook.go, selfservice/hook/web_hook.go, selfservice/hook/web_hook_integration_test.go, x/events/events.go
With this change we add two attributes to webhook events:
- `WebhookID`: a string that can be set in the config and that helps to identify the actual webhook config that was used
- `TriggerID`: a random string that helps to correlate requests across retries
=> feat: add attributes to webhook events for better debugging

identity/handler_test.go, identity/manager.go, identity/test/pool.go, internal/client-go/go.sum, persistence/sql/identity/persister_identity.go
A follow up on #4083, where the basic feature was implemented but the transaction was eventually rolled back also it seemed like it succeeded.
=> fix: do not roll back transaction on partial identity insert error

selfservice/strategy/idfirst/.snapshots/TestFormHydration-method=PopulateLoginMethodIdentifierFirstIdentification.json, selfservice/strategy/idfirst/strategy_login.go
AFAICT, this setup adds proper support for password managers to the strategy. Though different PW managers and browsers handle this attribute differently, and it's not well documented what best to do. This combination is the only one that worked reliably.
the changes.
works.
=> fix: add missing autocomplete attributes to identifier_first strategy

selfservice/strategy/code/strategy.go, selfservice/strategy/code/strategy_recovery_admin.go, selfservice/strategy/link/strategy.go, selfservice/strategy/link/strategy_recovery.go
=> feat: use one transaction for `/admin/recovery/code`

selfservice/strategy/code/strategy_recovery_admin.go, selfservice/strategy/link/strategy_recovery.go, x/events/events.go
=> feat: emit admin recovery code event

hash/hash_comparator.go, selfservice/strategy/password/login.go, selfservice/strategy/password/login_test.go
This fixes an issue where we would successfully import long passwords (>72 chars), but fail when the user attempts to login with the correct password because we can't rehash it. In this case, we simply issue a warning to the logs, keep the old hash intact, and continue logging in the user.
=> feat: gracefully handle failing password rehashing during login

selfservice/strategy/idfirst/.snapshots/TestFormHydration-method=PopulateLoginMethodIdentifierFirstIdentification.json, selfservice/strategy/idfirst/strategy_login.go, selfservice/strategy/passkey/.snapshots/TestCompleteLogin-flow=passwordless-case=passkey_button_exists.json, selfservice/strategy/passkey/.snapshots/TestCompleteLogin-flow=refresh-case=refresh_passwordless_credentials-browser.json, selfservice/strategy/passkey/.snapshots/TestCompleteLogin-flow=refresh-case=refresh_passwordless_credentials-spa.json, selfservice/strategy/passkey/.snapshots/TestCompleteSettings-case=a_device_is_shown_which_can_be_unlinked.json, selfservice/strategy/passkey/.snapshots/TestCompleteSettings-case=one_activation_element_is_shown.json, selfservice/strategy/passkey/.snapshots/TestFormHydration-method=PopulateLoginMethodFirstFactor.json, selfservice/strategy/passkey/.snapshots/TestFormHydration-method=PopulateLoginMethodFirstFactorRefresh.json, selfservice/strategy/passkey/.snapshots/TestFormHydration-method=PopulateLoginMethodIdentifierFirstIdentification.json, selfservice/strategy/passkey/.snapshots/TestRegistration-case=passkey_button_exists-browser.json, selfservice/strategy/passkey/.snapshots/TestRegistration-case=passkey_button_exists-spa.json, selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=mfa-case=webauthn_payload_is_set_when_identity_has_webauthn.json, selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=passwordless-case=should_fail_if_webauthn_login_is_invalid-type=browser.json, selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=passwordless-case=should_fail_if_webauthn_login_is_invalid-type=spa.json, selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-passwordless_enabled=false-case=mfa_v0_credentials-browser.json, selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-passwordless_enabled=false-case=mfa_v0_credentials-spa.json, selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-passwordless_enabled=false-case=mfa_v1_credentials-browser.json, selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-passwordless_enabled=false-case=mfa_v1_credentials-spa.json, selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-passwordless_enabled=true-case=passwordless_credentials-browser.json, selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-passwordless_enabled=true-case=passwordless_credentials-spa.json, selfservice/strategy/webauthn/.snapshots/TestCompleteSettings-case=a_device_is_shown_which_can_be_unlinked.json, selfservice/strategy/webauthn/.snapshots/TestCompleteSettings-case=one_activation_element_is_shown.json, selfservice/strategy/webauthn/.snapshots/TestFormHydration-method=PopulateLoginMethodRefresh-case=mfa_enabled_and_user_has_mfa_credentials.json, selfservice/strategy/webauthn/.snapshots/TestFormHydration-method=PopulateLoginMethodRefresh-case=passwordless_enabled_and_user_has_passwordless_credentials.json, selfservice/strategy/webauthn/.snapshots/TestFormHydration-method=PopulateLoginMethodSecondFactor-case=mfa_enabled.json, selfservice/strategy/webauthn/.snapshots/TestRegistration-case=webauthn_button_exists-browser.json, selfservice/strategy/webauthn/.snapshots/TestRegistration-case=webauthn_button_exists-spa.json, x/webauthnx/js/webauthn.js
=> fix: cancel conditional passkey before trying again

internal/client-go/model_ui_node.go, internal/httpclient/model_ui_node.go, spec/api.json, spec/swagger.json, ui/node/node.go
=> fix: add missing captcha group

identity/manager.go, identity/manager_test.go, selfservice/flow/registration/hook.go
In some configurations, if the identity only has an OIDC credential, the login hint message would contain an OIDC identifier including the subject, which is useless to the user.
the changes.
works.
=> fix: don't show oidc subject in login hints

go.mod, go.sum, identity/handler.go, identity/handler_test.go
=> fix: stricter JSON patch checking for PATCH identities

identity/handler.go, identity/handler_test.go
=> fix: allow patching some /credentials sub-paths

selfservice/flow/verification/handler.go, selfservice/flow/verification/handler_test.go
=> fix: accept login_challenge in SPA verification flows

selfservice/strategy/oidc/strategy.go, selfservice/strategy/oidc/strategy_test.go
This fixes a bug in native OIDC login and registration flows, where the user already has a session in the browser the flow is continued with (usually a web view, but depending on the platform it already has a session cookie set). In the callback, we now correctly handle the case in `alreadyAuthenticated` to return the session token exchange code. 
the changes.
works.
=> fix: return `return_to` code if already authenticated

selfservice/flow/continue_with.go, selfservice/hook/session_issuer.go, selfservice/hook/session_issuer_test.go, spec/api.json, spec/swagger.json
=> fix: accept login challenge in session_issuer on SPA flows

identity/handler.go, identity/handler_test.go
=> feat: allow setting the org ID on creation

embedx/config.schema.json, selfservice/strategy/oidc/provider_config.go, test/e2e/shared/config.d.ts
#4269
the changes.
works.
The docs were already updated e.g. https://www.ory.sh/docs/kratos/social-signin/microsoft#subject-identifier-source
=> fix: enable defining oid as oidc subject_source

identity/pool.go, persistence/sql/identity/persister_identity.go, selfservice/strategy/code/code_sender.go, selfservice/strategy/code/strategy_login.go, selfservice/strategy/code/strategy_recovery.go, selfservice/strategy/code/strategy_verification.go, selfservice/strategy/link/sender.go, selfservice/strategy/link/strategy_recovery.go, selfservice/strategy/link/strategy_verification.go
This is an optimization to reduce database load.
When we specify exactly which columns changed, we should be able to elide updates to the `identity_verifiable_addresses_status_via_uq_idx (nid,via,value)` index. Updating that index requires contacting remote regions.
Also fixed a bug where we did not set the `verified_at` timestamp correctly sometimes.
=> feat: update only necessary database columns in UpdateVerifiableAddress

.docker/Dockerfile-build, .docker/Dockerfile-debug, .github/workflows/ci.yaml, .github/workflows/format.yml, go.mod, go.sum, persistence/sql/persister_test.go, selfservice/strategy/oidc/strategy_helper_test.go, selfservice/strategy/password/op_helpers_test.go, test/e2e/mock/httptarget/go.mod
=> chore: upgrade to go 1.24

selfservice/strategy/oidc/strategy.go, selfservice/strategy/oidc/strategy_login.go, selfservice/strategy/oidc/strategy_test.go
=> feat: add context param to policy

identity/identity.go, identity/identity_test.go, selfservice/strategy/oidc/strategy_login.go, selfservice/strategy/oidc/strategy_test.go, selfservice/strategy/password/validator_test.go
This fixes a bug where when an identity is merged into another, the identifier of the original identity was not updated.
=> fix: also update identifiers

persistence/sql/identity/persister_identity.go
`defer` was the incorrect code path here, as we should only record identity created if the transaction did not error (aka was rolled back).
the changes.
works.
=> fix: IdentityCreated is over-reporting on error inserts

test/e2e/cypress/integration/profiles/email/error/ui.spec.ts, test/e2e/cypress/integration/profiles/email/login/error.spec.ts, test/e2e/cypress/integration/profiles/email/login/success.spec.ts, test/e2e/cypress/integration/profiles/email/login/ui.spec.ts
=> chore: document test migration

selfservice/strategy/code/strategy.go, selfservice/strategy/code/strategy_test.go, session/manager_http_test.go, test/e2e/cypress/integration/profiles/mfa/code_optional.spec.ts, test/e2e/cypress/support/configHelpers.ts, test/e2e/profiles/mfa-optional/.kratos.yml, test/e2e/profiles/mfa-optional/identity.traits.schema.json, test/e2e/run.sh
Attempt to fix https://github.com/ory/network/issues/409
the changes.
works.
=> fix: count MFA addresses in CountActiveMultiFactorCredentials for code method

driver/config/.snapshots/TestDefaultWebhookHeaderAllowlist.json, driver/config/config.go, driver/config/config_test.go, embedx/config.schema.json, selfservice/hook/web_hook.go, selfservice/hook/web_hook_integration_test.go
Adds a `actions.web_hook.header_allowlist` configuration option for configuring the webhook header allowlist.
closes #4290 
the changes.
works.
Docs need to be updated (https://www.ory.sh/docs/guides/integrate-with-ory-cloud-through-webhooks#accessing-request-headers) --- unsure what the process is for unreleased changes.
=> feat: webhook header allowlist configuration option

Makefile, internal/client-go/go.sum
Annoyingly, the internal/client-go/go.sum is incorrect and gets constantly reset by the IDE. Running go mod tidy should ensure that we don't have such drift anymore, which results in annoying commits like https://github.com/ory/kratos/commit/47e583b3b4ca26a176c814f552783b9128ee252e.
=> chore: run `go mod tidy` during internal SDK generation

hash/hash_comparator.go, hash/hasher_argon2.go, hash/hasher_bcrypt.go, hash/hasher_pbkdf2.go
Especially during large imports of plaintext passwords there can be a lot of useless hashing, even after the request timed out or got canceled.
=> fix: ensure context is not canceled during password hashing

selfservice/flow/login/handler.go, selfservice/flow/login/hook.go, selfservice/flow/recovery/handler.go, selfservice/flow/registration/handler.go, selfservice/flow/settings/handler.go, selfservice/flow/verification/handler.go, selfservice/strategy/oidc/strategy.go, x/http.go, x/http_test.go
BREAKING CHANGES: Account linking incorrectly returned a 200 OK status code even though the login flow was not completed successfully. Going forward, the correct 400 OK status code will be sent when using the API flow or `Accept: application/json`.
the changes.
works.
=> fix: incorrect response code on account linking

go.mod, go.sum, selfservice/flow/login/handler.go, selfservice/flow/registration/handler.go, selfservice/strategy/oidc/strategy_registration.go, x/events/events.go, x/events/events_test.go
We now emit an event containing the Jsonnet input and output in anonymized form when mapping the claims in the OIDC flow fails.
=> feat: emit event on Jsonnet claims mapping error

Makefile
`make quickstart-dev` uses the make variable `QUICKSTART_OPTIONS` which is set to `""` by default. This will result in two double quotes (`""`) in the final shell command e.g. `docker-compose "" up` when the variable is not set on the make command line, which fails at the shell level. The fix is to leave the variable empty by default. No semantic changes.
=> fix: ensure `make quickstart-dev` works without options

hydra/fake.go, selfservice/flow/login/handler.go, selfservice/flow/registration/handler.go, selfservice/hook/session_issuer_test.go, x/events/events.go
**Changes:**
- Add `LoginStarted` and `RegistrationStarted` events along their required attributes
- Sort all event attributes alphabetically
- Emit these events when a new login/registration flow is created, *after* basic validation passed
- It is unclear yet how many of these events will be emitted, as such it is suggested that in a first phase, they remain internal and are not yet sent externally to avoid surprises (note: sometimes, these events can be emitted without user action such as simply visiting/being redirected to the sign-in page, etc)
**Documentation PR:** [ory/docs#2144](https://github.com/ory/docs/pull/2144)
**Issue:** https://github.com/ory-corp/cloud/issues/7895
Examples in Grafana:
- LoginStarted: <img width="955" alt="Screenshot 2025-05-06 at 14 54 32" …
=> feat: add LoginStarted and RegistrationStarted events

Makefile, persistence/sql/identity/persister_identity.go, selfservice/hook/verification.go, session/tokenizer.go
- Fix typo: parital -> partial
- Document with comments why an event is not emitted or not documented
- Emit `JsonnetMappingFailed` events on jsonnet failure when templating a jwt (see https://www.ory.sh/docs/identities/session-to-jwt-cors). After review it seems we otherwise always emit events in all the right places, except in this very case. Tested end-to-end manually with the UI.
https://github.com/ory-corp/cloud/issues/7291
the changes.
works.
=> feat: emit events on jsonnet failure when templating a jwt

driver/config/config.go, embedx/config.schema.json, selfservice/strategy/oidc/strategy.go, selfservice/strategy/oidc/strategy_login.go, selfservice/strategy/oidc/strategy_registration.go, test/e2e/profiles/kratos.base.yml
BREAKING CHANGE: Going forward, the node group of fields that are failing validation during oidc sign up are `default` and no longer `oidc`. For now, you can get the legacy behavior back by turning on `feature_flags.legacy_oidc_registration_node_group=true`.
the changes.
works.
=> fix: use default group for signup nodes in oidc
