.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/security.md
.github/ISSUE_TEMPLATE/support.md
.github/pull_request_template.md
.releaser/LICENSE.txt
CONTRIBUTING.md

Signed-off-by: aeneasr <aeneas@ory.sh>

docs: Updates issue and pull request templates

---

cmd/daemon/serve.go
driver/registry.go
driver/registry_memory.go
selfservice/handler.go
selfservice/handler_test.go
x/nosurf.go

Add tests for logout.
Closes #38

ss: Reset CSRF token on principal change

---

docs/.hive.yaml
docs/config.schema.json
driver/configuration/provider.go
driver/configuration/provider_viper.go
selfservice/handler.go
selfservice/handler_test.go
selfservice/oidc/strategy.go
selfservice/password/login.go
selfservice/password/registration.go
selfservice/password/strategy.go
session/handler.go
session/handler_mock.go
session/handler_test.go
x/http.go

Require no session when accessing login or sign up

---

cmd/daemon/serve.go
driver/registry.go
driver/registry_abstract.go

Add health endpoints

---

.circleci/config.yml

Add changelog generation task

---

docs/config.schema.json

Replace number with integer in config JSON Schema

---

selfservice/strategy/oidc/strategy.go

strategy/oidc: Allow multiple OIDC Connections

---

selfservice/strategy/oidc/strategy.go

ss/oidc: Remove obsolete request field from form

---

docs/api.swagger.json
go.mod
go.sum
internal/httpclient/models/form_field.go
internal/httpclient/models/login_request_method.go
selfservice/form/fields.go
selfservice/form/fields_test.go
selfservice/form/html_form.go
selfservice/form/stub/all_formats.schema.json

Improve field types

---

docs/api.swagger.json
internal/httpclient/models/login_request_method.go
internal/httpclient/models/registration_request_method.go
internal/httpclient/models/registration_request_method_config.go
selfservice/errorx/manager.go
selfservice/flow/login/error.go
selfservice/flow/login/handler.go
selfservice/flow/login/request_method.go
selfservice/flow/logout/handler.go
selfservice/flow/profile/error.go
selfservice/flow/profile/handler.go
selfservice/flow/registration/error.go
selfservice/flow/registration/handler.go
selfservice/flow/registration/request_method.go
selfservice/form/container.go
selfservice/strategy/oidc/strategy.go
selfservice/strategy/password/login.go
selfservice/strategy/password/login_test.go
selfservice/strategy/password/registration.go
selfservice/strategy/password/registration_test.go
selfservice/strategy/password/strategy.go
x/nosurf.go

closes #96 
A request with an expired session auth session will from now on result in a redirect to a new auth session with an error indicating that the session expired.

feat: redirect to new auth session on expired auth sessions

---

docs/api.swagger.json
identity/identity.go
internal/httpclient/models/form.go
internal/httpclient/models/form_field.go
internal/httpclient/models/identity.go
internal/httpclient/models/login_request.go
internal/httpclient/models/login_request_method.go
internal/httpclient/models/login_request_method_config.go
internal/httpclient/models/profile_management_request.go
internal/httpclient/models/registration_request.go
internal/httpclient/models/registration_request_method_config.go
internal/httpclient/models/session.go
selfservice/flow/login/persistence.go
selfservice/flow/login/request.go
selfservice/flow/login/request_method.go
selfservice/flow/profile/handler_test.go
selfservice/flow/profile/request.go
selfservice/flow/registration/persistence.go
selfservice/flow/registration/request.go
selfservice/flow/registration/request_method.go
selfservice/form/fields.go
selfservice/form/html_form.go
selfservice/strategy/oidc/types.go
selfservice/strategy/password/types.go
session/session.go

fix(swagger): Use correct annotations for request methods

---

.circleci/config.yml
Makefile
docs/api.swagger.json

Resolve flaky SDK generation issues caused by UUID

---

selfservice/flow/login/error.go
selfservice/flow/registration/error.go
selfservice/hook/session_issuer.go
selfservice/hook/session_issuer_test.go

fix: Set AuthenticatedAt in session issuer hook

---

contrib/quickstart/oathkeeper/access-rules.yml
docs/api.swagger.json
internal/httpclient/client/public/complete_self_service_browser_verification_flow_parameters.go
internal/httpclient/client/public/complete_self_service_browser_verification_flow_responses.go
internal/httpclient/client/public/public_client.go
selfservice/flow/verify/handler.go
selfservice/flow/verify/handler_test.go

fix: Update verify URLs

---

persistence/sql/persister_test.go

feat: Enable CockroachDB integration

---

README.md

N/A
Corrects a typo in README.md
N/A

docs: Typo in README.md

---

docs/config.schema.json
driver/configuration/provider.go
driver/configuration/provider_viper.go
identity/manager.go
identity/manager_test.go
identity/pool.go
selfservice/flow/profile/handler.go
selfservice/flow/profile/handler_test.go
session/handler_mock.go

feat(selfService/profile): enable updating auth related traits

---

persistence/sql/migrations/20191100000011_courier_body_type.down.fizz
persistence/sql/migrations/20191100000011_courier_body_type.up.fizz

fix(sql/migrations): change type of courier_message.body to "text"

---

driver/configuration/provider_viper.go

Fix smtp/stmp typo

---

session/handler.go

fix(session): whoami endpoint now supports all HTTP methods

---

docs/api.swagger.json
identity/doc.go
identity/handler.go
identity/handler_doc.go
internal/httpclient/client/admin/create_identity_responses.go
internal/httpclient/client/admin/get_identity_responses.go
internal/httpclient/client/admin/list_identities_responses.go
internal/httpclient/client/admin/update_identity_responses.go
internal/httpclient/models/generic_error_payload.go
swagger_types_global.go

Closes https://github.com/ory/docs/pull/279

fix(swagger): Move nolint,deadcode instructions to own file

---

docs/docs/self-service/flows/user-settings-profile-management.md

fix writing

---

cmd/daemon/serve.go
cmd/serve.go
session/handler_test.go

fix: exempt whomai from csrf protection

---

docs/package-lock.json
docs/package.json
docs/scripts/docker-tag.js
docs/scripts/fix-api.js
docs/scripts/rerelease.js

Signed-off-by: aeneasr <aeneas@ory.sh>

chore: update docusaurus template

---

docs/versioned_docs/version-v0.1/quickstart.mdx

fix: docs: spelling in quickstart

---

docs/docs/guides/high-availability-ha.md
docs/docs/guides/multi-tenancy-multitenant.md
docs/sidebar.js

Add HA and multi-tenancy docs

---

.schema/config.schema.json
docs/docs/reference/configuration.md

docs: add more examples to config schema

---

.schema/config.schema.json
courier/courier.go
docs/docs/concepts/security.mdx
docs/docs/fallback/default_return_to.mdx
docs/docs/fallback/error.mdx
docs/docs/fallback/login.mdx
docs/docs/fallback/mfa.mdx
docs/docs/fallback/registration.mdx
docs/docs/fallback/settings.mdx
docs/docs/fallback/verify.mdx
docs/docs/quickstart.mdx
driver/configuration/provider_viper.go

feat: introduce fallbacks for required configs

---

UPGRADE.md

docs: perpare changelog for 0.2.0-alpha.2

---

.schema/api.swagger.json
.schema/config.schema.json
internal/httpclient/models/generic_error_payload.go

docs: make whitelisted_return_to_urls examples an array

---

docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx

@aeneasr there is no issue I believe for this specific item but a guide for Google should be good to have.
This PR adds instructions on how to setup SSO via Google.
the changes.
works.

docs: add guide for SSO via Google

---

docs/versioned_docs/version-v0.3/guides/sign-in-with-github-google-facebook-linkedin.mdx

Added short guide for connecting kratos to AzureAD

---

docs/versioned_docs/version-v0.3/concepts/index.md

Fixed a few broken links, .md in the url was the problem.
the changes.
works.

docs: fixed broken links

---

docs/versioned_docs/version-v0.3/concepts/ui-user-interface.md

docs: fixed broken link

---

docs/versioned_docs/version-v0.3/quickstart.mdx

docs: fixed typo

---

docs/docs/self-service/flows/user-login-user-registration.mdx

docs: document refresh=true for login

---

docs/docs/quickstart.mdx

Closes #430
the changes.
works.

docs: correct SDK use in quickstart

---

docs/docs/concepts/security.mdx
docs/docs/self-service/flows/user-login-user-registration/username-email-password.mdx
docs/versioned_docs/version-v0.2/concepts/security.mdx
docs/versioned_docs/version-v0.2/guides/zero-trust-iap-proxy-identity-access-proxy.md
docs/versioned_docs/version-v0.2/self-service/strategies/username-email-password.md
docs/versioned_docs/version-v0.3/concepts/security.mdx
docs/versioned_docs/version-v0.3/guides/zero-trust-iap-proxy-identity-access-proxy.md
docs/versioned_docs/version-v0.3/self-service/flows/user-login-user-registration/username-email-password.mdx

docs: fixed broken markdown

---

selfservice/form/fields.go

See https://github.com/ory/kratos/pull/467#discussion_r434764266
the changes.
works.

docs: properly annotate forms disabled field

---

driver/registry_default.go
identity/credentials.go
internal/testhelpers/server.go
selfservice/flow/login/handler_test.go
selfservice/flow/registration/handler_test.go
selfservice/strategy/link/strategy_test.go
selfservice/strategy/oidc/strategy_helper_test.go
selfservice/strategy/oidc/strategy_settings_test.go
selfservice/strategy/oidc/strategy_test.go
selfservice/strategy/password/login_test.go
selfservice/strategy/password/registration_test.go

Fixes #417
the changes.
works.

fix: Enabled configuration for self-service strategies

---

docs/versioned_docs/version-v0.3/concepts/index.md

the changes.
works.
noticed some typos, went and tried to fix them :+1:

fix: typos in documentation overview

---

docs/docs/quickstart.mdx

docs: embedded quickstart video

---

docs/versioned_docs/version-v0.3/quickstart.mdx

docs: added youtube manual

---

docs/docs/concepts/credentials/username-email-password.mdx

docs: typos and stale links

---

docs/docs/quickstart.mdx

fix: embedded video link properly

---

docs/docs/guides/kratos-video-tutorials.mdx

I changed the wording a little, and included the transcript in collapsible field.
the changes.
works.

docs: added video tutorials to guides

---

docs/docs/guides/kratos-video-tutorials.mdx

fix: iframe error

---

docs/docs/guides/kratos-video-tutorials.mdx

fix: removed rogue slash

---

persistence/sql/persister_test.go

fix: re-add all databases to persister

---

.gitignore

refactor: improved configuration layout

---

docs/docs/debug/csrf.md

Fix typo in docs
the changes.
- [N/A ] I have added tests that prove my fix is effective or that my feature
works.

docs: fix typo

---

internal/httpclient/client/public/public_client.go
session/handler.go

Closes #483
the changes.
works.

fix: do not send debug on session/whoami

---

contrib/quickstart/kratos/email-password/.kratos.yml
driver/configuration/provider_viper.go
driver/configuration/provider_viper_test.go
internal/httpclient/client/public/public_client.go

Closes #436
the changes.
works.

fix: resolve broken redirect in verify flow

---

identity/identity.go
selfservice/strategy/oidc/strategy_settings.go
selfservice/strategy/oidc/strategy_settings_test.go

fix: allow linking oidc credentials without exiting oidc connection

---

docs/docs/concepts/credentials.md

docs: typo correction in credentials.md

---

.docker/Dockerfile
.docker/Dockerfile-build
.docker/Dockerfile-goreleaser
.docker/Dockerfile-sqlite

- expose ory home as volume to simplify passing in own config file
- declare Kratos default ports in Dockerfile
the changes.
works.

fix: improvements to Dockerfiles

---

docs/docs/concepts/credentials/username-email-password.mdx

docs: fix broken link

---

go.mod
go.sum

fix: bump pop version

---

go.mod
go.sum

chore: bump pop to latest master

---

.schema/config.schema.json

fix: ensure default_browser_return_url for flows is configured in after

---

.dockerignore
docs/docs/guides/docker.md
docs/docs/install.md
docs/sidebar.js

As the official Docker images provided by Ory are the recommend way to run Kratos, we should provide more details on the different image types and how the images can be used. 
This is only 
the changes.
works.

docs: Docker image documentation

---

selfservice/hook/verification.go
selfservice/hook/verification_test.go

fix: don't resend verification emails once verified

---

x/nocache.go
x/router.go
x/router_test.go

feat: do not cache browser-facing requests

---

.schema/config.schema.json
docs/docs/guides/login-session.mdx
docs/sidebar.js
driver/configuration/provider.go
driver/configuration/provider_viper.go
session/manager_http.go
session/session.go

feat: implement max-age for session cookie

---

identity/handler_test.go
internal/testhelpers/json.go

Closes #325
the changes.
works.

test: add handler update tests

---

.circleci/config.yml
driver/driver_default_test.go
internal/testhelpers/json.go
test/e2e/run.sh

Closes #580
the changes.
works.

test: replace e2e-memory with unit test

---

selfservice/strategy/password/validator.go
selfservice/strategy/password/validator_test.go

On network errors, the password validator ends up in a recursion loop until either the fault disappears - or more likely the stack overflows. Related to #316, @aeneasr .
Change the validator code so that when `ignoreNetworkErrors = true`, a failure during the _pwnedpasswords.com_ check returns no error, but the validation of the same password later would retry the online check.
Added test cases that previously crashed or timed out the test suite (because of the loop), but they pass now. I also took the liberty to add a few more tests for the online password leak check.
the changes.
works.
I …

fix: Network errors during pwnedpasswords.com check causing recursive loop

---

.schema/config.schema.json
docs/docs/guides/login-session.mdx
driver/configuration/provider.go
driver/configuration/provider_viper.go
identity/handler_test.go
internal/testhelpers/json.go
session/manager_http.go
session/session.go

fix: improve session max-age behavior

---

session/manager_http.go
session/manager_http_test.go

fix: resolves a bug that prevents sessions from expiring

---

.schema/api.swagger.json
docs/docs/self-service/flows/user-facing-errors.md
internal/httpclient/client/common/common_client.go
selfservice/errorx/handler.go
selfservice/errorx/handler_test.go

Closes #610
the changes.
works.

feat: add stub errors to errorx

---

docs/versioned_docs/version-v0.4/concepts/index.md

Fixed a few typos, and moved some sentences around to improve readability.
Also changed Ory to ORY throughout the doc.
the changes.
works.

docs: fixed typos/readability

---

docs/versioned_docs/version-v0.4/guides/sign-in-with-github-google-facebook-linkedin.mdx

docs: add video to OIDC guide

---

docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx

docs: add github video tutorial

---

docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx

docs: add session hook to ssi guide

---

Makefile
docs/docs/admin/managing-users-identities.mdx
docs/docs/concepts/identity-data-model.md
docs/docs/concepts/index.md
docs/docs/concepts/terminology.mdx
docs/docs/guides/configuring-cookies.mdx
docs/docs/guides/docker.md
docs/docs/guides/login-session.mdx
docs/docs/guides/secret-key-rotation.mdx
docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx
docs/docs/install.md
docs/docs/self-service/flows/user-login-user-registration.mdx
docs/docs/self-service/flows/user-logout.md

chore: format docs

---

docs/versioned_docs/version-v0.4/self-service/flows/account-recovery.mdx

docs: fixed link

---

docs/docs/guides/kratos-video-tutorials.mdx

Added Login with Github Transcript
the changes.
works.

docs: added transcript

---

docs/sidebar.json

Added Kratos Video Tutorial Transcripts document to sidebar.
the changes.
works.

docs: added sidebar item

---

.circleci/config.yml
.goreleaser.yml

ci: render version schema on release

---

docs/versioned_docs/version-v0.4/index.md

Just a simple typo fix in the documentation
the changes.
works.

Fix typo on index page

---

.schema/api.swagger.json
internal/httpclient/client/common/common_client.go
schema/handler.go
selfservice/errorx/handler.go
selfservice/flow/login/handler.go
selfservice/flow/recovery/handler.go
selfservice/flow/registration/handler.go
selfservice/flow/settings/handler.go
selfservice/flow/verification/handler.go
selfservice/strategy/oidc/strategy_settings.go
selfservice/strategy/password/settings.go
selfservice/strategy/profile/strategy.go
selfservice/strategy/recoverytoken/strategy.go
session/handler.go

Closes #664 
Use NYT Capitalization for all Swagger headlines
the changes.
works.

docs: use NYT Capitalization for all Swagger headlines #664

---

.github/workflows/labels.yml
.github/workflows/milestone.yml
.github/workflows/stale.yml
README.md
docs/docs/contributing.md

Updated repository templates to https://github.com/ory/meta/commit/e3cc51a3e1b1609daaf59b29ab140b6a3d2dadbe.

chore: update repository template to e3cc51a3

---

README.md

Updated repository templates to https://github.com/ory/meta/commit/1d3bdaf243c166ab2ed8a6de1c33ca728ff620a3.

chore: update repository template to 1d3bdaf2

---

docs/versioned_docs/version-v0.4/self-service/flows/2fa-mfa-multi-factor-authentication.md

Looks like the MFA issue was pushed to a later milestone.  Update the documentation to point to the issue instead of the milestone.
- [X ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [X ] I have read the [security policy](../security/policy).
- [X ] I confirm that this pull request does not address a security
the changes.
works.
- [X ] I have added or changed [the documentation](docs/docs).

Update MFA page

---

docs/docs/concepts/identity-data-model.md

docs: import mermaid

---

.github/workflows/closed_references.yml
CONTRIBUTING.md
README.md
SECURITY.md
docs/docs/contributing.md

Updated repository templates to https://github.com/ory/meta/commit/6f3059720c2206a267a4e511cc149439a9a90906.

chore: update repository template to 6f305972

---

.nancy-ignore

ci: remove false positives from .nancy-ignore

---

.github/workflows/closed_references.yml
.github/workflows/labels.yml
.github/workflows/milestone.yml
.github/workflows/stale.yml
.reference-ignore

Updated repository templates to https://github.com/ory/meta/commit/7900d6c75a8a6e5f583591d5110eacacda1ef286.

chore: update repository template to 7900d6c7

---

.schema/config.schema.json
test/schema/fixtures/config.schema.test.failure/selfServiceOIDCProvider.tenantNotWithGithub.yaml
test/schema/fixtures/config.schema.test.failure/selfServiceOIDCProvider.tenantRequiredWithMicrosoft.yaml
test/schema/fixtures/config.schema.test.success/selfServiceOIDCProvider.fullGithub.yaml
test/schema/fixtures/config.schema.test.success/selfServiceOIDCProvider.fullMicrosoft.yaml

fix: allow (and require) tenant only with the microsoft OIDC provider

---

README.md

Tiny fix to improve readability and make the formatting consistent. No content changes. Doesn't seem to impact formatting: https://github.com/kevgo/kratos/blob/kg-readme-newline/README.md
the changes.
works.

docs: Consistent newlines between badges

---

docs/docs/contributing.md

Updated repository templates to https://github.com/ory/meta/commit/5d8498e5ce599835fb7ee81c1b955e4fd08b6845.

chore: update repository template to 5d8498e5

---

README.md
docs/sidebar.json

Updated repository templates to https://github.com/ory/meta/commit/4fcbc1b26034d31a979608ffd6ca9923f5b6a131.

chore: update repository template to 4fcbc1b2

---

.circleci/config.yml
docs/sidebar.json

golangci timeout
the changes.
works.

chore(deps): bump cci orbs

---

cmd/daemon/serve.go
go.mod
go.sum
selfservice/strategy/oidc/provider_gitlab.go

fix: resolve logout csrf issues

---

quickstart-debug.yml

Fix csrf login

---

.schema/config.schema.json
cmd/daemon/serve.go
go.mod
go.sum
internal/testhelpers/httptest.go
selfservice/flow/login/handler.go
selfservice/flow/recovery/handler.go
selfservice/flow/registration/handler.go
selfservice/flow/request.go
selfservice/flow/settings/handler.go
selfservice/flow/verification/handler.go
selfservice/strategy/password/login.go
selfservice/strategy/password/login_test.go
selfservice/strategy/password/registration_test.go
selfservice/strategy/password/settings_test.go
selfservice/strategy/profile/strategy_test.go
test/e2e/profiles/recovery/.kratos.yml
test/e2e/profiles/verification/.kratos.yml
test/schema/fixtures/config.schema.test.success/root.full.yml
x/clean_url.go
x/clean_url_test.go

Bump gobufalo/pop

---

docs/docs/quickstart.mdx
docs/versioned_docs/version-v0.5/quickstart.mdx

None
Trivial documentation fix. Remove trailing garbage from quickstart docs.
the changes.
works.
None

Remove trailing gargbage from quickstart docs

---

docs/docs/concepts/index.md
docs/versioned_docs/version-v0.5/concepts/index.md

.mdx was missing
the changes.
works.

fix: broken doc link

---

.goreleaser.yml

Closes https://github.com/ory/homebrew-kratos/issues/1
the changes.
works.

fix: force brew install statement

---

docs/docs/concepts/identity-data-model.md
docs/docs/concepts/index.md
docs/sidebar.json
docs/versioned_docs/version-v0.5/concepts/identity-data-model.md
docs/versioned_docs/version-v0.5/concepts/index.md
docs/versioned_sidebars/version-v0.5-sidebars.json

The link to identity-data-model was still named identity-user-model thus broken. 
I didnt change the name of the document cause I thought it might break something, but would be good to change it as well. 
Let me know if I should go ahead and change it.
I tested all links now locally and it worked fine! 
(btw first time i figured out how to build kratos docs locally :D, will include a how-to in the contribute to docs soon!)
the changes.
works.

fix: docs wrong name

---

docs/docs/concepts/index.md
docs/docs/self-service/flows/user-settings.mdx

docs: fix redirect

---

docs/docs/self-service/flows/account-recovery.mdx

passed_challenge has a typo
the changes.
works.

docs: fix self-service recovery flow typo

---

docs/docs/concepts/identity-data-model.md
docs/docs/concepts/index.md
docs/docs/guides/docker.md
docs/docs/guides/login-session.mdx
docs/docs/guides/zero-trust-iap-proxy-identity-access-proxy.mdx
docs/docs/self-service.mdx
docs/docs/self-service/flows/account-recovery.mdx
docs/docs/self-service/flows/user-login.mdx
docs/docs/self-service/flows/user-registration.mdx
docs/docs/self-service/flows/user-settings.mdx
docs/docs/self-service/flows/verify-email-account-activation.mdx
docs/src/theme/ApiWarning.js
docs/versioned_docs/version-v0.5/concepts/identity-data-model.md
docs/versioned_docs/version-v0.5/self-service.mdx

Fixes some word duplications
the changes.
works.

docs: removes duplicate words & fixes spelling

---

README.md

Updated from this:
Account Recovery**: Recover access using "Forgot Password" flows, Security
Codes (in case of MKFA device loss), and others.
to this:
Account Recovery**: Recover access using "Forgot Password" flows, Security
Codes (in case of MFA device loss), and others.
the changes.
works.

docs: update MKFA to MFA

---

docs/docs/concepts/credentials/openid-connect-oidc-oauth2.mdx

The structure should be `selfservice.methods.oidc.config.providers` but in this documentation it was shown as `selfservice.methods.oidc.providers`
the changes.
works.

docs: fix oidc config example structure

---

docs/versioned_docs/version-v0.5/guides/docker.md

fix: incorrect home path

---

docs/docs/quickstart.mdx

Fix account recovery click instruction

---

package-lock.json
package.json
test/e2e/cypress/helpers/index.js
test/e2e/cypress/integration/profiles/mobile/login/success.spec.js
test/e2e/cypress/integration/profiles/mobile/registration/success.spec.js
test/e2e/cypress/integration/profiles/mobile/settings/errors.spec.js
test/e2e/cypress/integration/profiles/mobile/settings/success.spec.js
test/e2e/proxy/package-lock.json

chore: update deps

---

docs/docs/self-service.mdx

Fix typo in self-service doc

---

docs/docs/guides/configuring-cookies.mdx

docs: fix link and typo in Configuring Cookies

---

persistence/sql/persister_test.go

Closes #718
the changes.
works.

docs: remove workaround note

---

.schema/config.schema.json
driver/configuration/provider.go
driver/configuration/provider_viper.go
driver/registry_default.go
selfservice/strategy/password/validator.go
selfservice/strategy/password/validator_lcs_test.go
selfservice/strategy/password/validator_test.go

Allows configuring password breach thresholds and optionally enforces checks against the HIBP API.
Closes #450
Closes #316

fix: make password policy configurable

---

docs/docs/quickstart.mdx
quickstart-selinux.yml

Closes #831
the changes.
works.

feat: add selinux compatible quickstart config

---

.golangci.yml
identity/extension_recovery.go

Closes #891
the changes.
works.

ci: disable dupl due to false positives

---

.schema/config.schema.json

Fix typo in config schema

---

docs/versioned_docs/version-v0.5/concepts/email-sms.md

I haven't found any issue about this part
Update doc with email template specification
the changes.
works.

feat: add email template specification in doc

---

.github/workflows/codeql-analysis.yml
docs/sidebar.json

ci: add codeql

---

docs/docs/debug/performance-out-of-memory-password-hashing-argon2.md
docs/sidebar.json

docs: fix link to blogpost

---

README.md
docs/sidebar.json

Updated repository templates to https://github.com/ory/meta/commit/6aa9dbbf3cd126373bee21c096d05763f9961a4e.

chore: update repository template to 6aa9dbbf

---

.docker/Dockerfile-build

Please remember to ADD/COPY the go.mod in dockerfile for every module
replaced by a local one.
#965 
the changes.
works.

fix: broken make quickstart-dev task

---

docs/docs/guides/login-session.mdx
docs/docs/sdk.md
docs/docs/self-service.mdx
docs/docs/self-service/flows/code/login/samples/api/init.js.txt
docs/docs/self-service/flows/code/login/samples/get.js.txt
docs/docs/self-service/flows/code/recovery/samples/api/init.js.txt
docs/docs/self-service/flows/code/recovery/samples/get.js.txt
docs/docs/self-service/flows/code/registration/samples/api/init.js.txt
docs/docs/self-service/flows/code/registration/samples/get.js.txt
docs/docs/self-service/flows/code/settings/samples/api/init.js.txt
docs/docs/self-service/flows/code/settings/samples/get.js.txt
docs/docs/self-service/flows/code/verification/samples/api/init.js.txt
docs/docs/self-service/flows/code/verification/samples/get.js.txt
docs/sidebar.json
docs/versioned_docs/version-v0.5/guides/login-session.mdx
docs/versioned_docs/version-v0.5/sdk.md
docs/versioned_docs/version-v0.5/self-service.mdx
docs/versioned_docs/version-v0.5/self-service/flows/code/login/samples/api/init.js.txt
docs/versioned_docs/version-v0.5/self-service/flows/code/login/samples/get.js.txt
docs/versioned_docs/version-v0.5/self-service/flows/code/recovery/samples/api/init.js.txt
docs/versioned_docs/version-v0.5/self-service/flows/code/recovery/samples/get.js.txt
docs/versioned_docs/version-v0.5/self-service/flows/code/registration/samples/api/init.js.txt
docs/versioned_docs/version-v0.5/self-service/flows/code/registration/samples/get.js.txt
docs/versioned_docs/version-v0.5/self-service/flows/code/settings/samples/api/init.js.txt
docs/versioned_docs/version-v0.5/self-service/flows/code/settings/samples/get.js.txt
docs/versioned_docs/version-v0.5/self-service/flows/code/verification/samples/api/init.js.txt
docs/versioned_docs/version-v0.5/self-service/flows/code/verification/samples/get.js.txt

changed
@oryd/kratos-client
to 
@ory/kratos-client
in docs and ver.05 docs

docs: fix npm links

---

selfservice/flow/settings/hook.go
selfservice/strategy/oidc/strategy_settings_test.go

fix: linking a connection may result in system error

---

driver/config/config.go

fix: improve error tracing

---

.circleci/config.yml
Makefile
README.md
package-lock.json
package.json

Checks technical parts of the documentation using a documentation testing framework ([Text-Runner](https://github.com/kevgo/text-runner)) and fixes a number of issues found.
the changes.
works.
Keeping it simple for now to provide an idea of the capabilities of the tool. In later stages we can automate larger tutorials as well.

docs: Initial set of documentation tests

---

docs/docs/quickstart.mdx

docs: Describe more about login api on quickstart doc

---

docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx

Changed the headings under ## Facebook to bold to make the sidebar look consistent.
the changes.
works.

docs: minor cosmetics

---

cmd/daemon/serve.go
driver/registry_default_login.go
driver/registry_default_recovery.go
driver/registry_default_registration.go
driver/registry_default_settings.go
driver/registry_default_verify.go
go.mod
go.sum
selfservice/flow/logout/handler_test.go
selfservice/flow/recovery/handler.go
selfservice/flow/registration/hook.go
selfservice/flow/verification/handler.go
selfservice/strategy/handler.go
selfservice/strategy/link/strategy_verification.go
selfservice/strategy/oidc/provider_facebook.go
selfservice/strategy/password/strategy_test.go
x/nosurf.go
x/nosurf_test.go

Contextual cookie

---

cmd/courier/watch.go
cmd/courier/watch_test.go

fix: fix issues with tests

---

docs/docs/further-reading/kratos-video-tutorials.mdx
docs/docs/quickstart.mdx
docs/versioned_docs/version-v0.3/quickstart.mdx
docs/versioned_docs/version-v0.4/guides/kratos-video-tutorials.mdx
docs/versioned_docs/version-v0.4/quickstart.mdx
docs/versioned_docs/version-v0.5/further-reading/kratos-video-tutorials.mdx
docs/versioned_docs/version-v0.5/quickstart.mdx

Merge when the video is released.
the changes.
works.

docs: update kratos video link

---

.circleci/config.yml
.schema/config.schema.json
driver/registry_default.go
go.mod
go.sum
persistence/sql/migratest/migration_test.go

feat: add sql tracing

---

cmd/courier/watch.go
courier/courier.go
courier/courier_test.go
x/mailhog.go

feat: expose courier worker

---

docs/docs/concepts/identity-data-model.md
docs/versioned_docs/version-v0.5/concepts/identity-data-model.md

Identities States description fixed.
the changes.
works.

docs: fix identity state bullets

---

docs/sidebar.json

Since the FAQ is up and ready, its time to add it to the sidebar and let loose on our users.
There will be some documentation and infrastructure around how we generate the faq.yaml in the coming days.
Changes have been tested locally and are working.
@zepatrik 
the changes.
works.

docs: add FAQ to sidebar

---

Makefile

fix: add node_modules to format tasks

---

docs/versioned_docs/version-v0.5/guides/setting-up-password-hashing-parameters.md

docs: fix link

---

docs/faq.yaml

Added some items to the FAQ as well as rewriting some existing ones, styling the links differently. 
tested with 
`npm run gen`
`npm run start`
and working.
PS: there was a section including {id} in one answer, this caused the FAQ not to load, I removed the section with that code segment, it was not crucial anyway.
the changes.
works.

docs: FAQ improvement

---

selfservice/strategy/oidc/provider_gitlab.go

https://github.com/ory/kratos/issues/1157
Fix gitlab oidc flow
the changes.
works.

fix: gitlab oidc flow

---

driver/config/config_test.go

feat: add more tests for multi domain args

---

docs/faq.yaml

closes https://github.com/ory/kratos/pull/1124
Most of the changes from #1124 are already in the FAQ, I added the others and a new item concerning multiple system secrets. 
the changes.
works.

docs: FAQ item & minor changes

---

docs/docs/sdk.md
docs/versioned_docs/version-v0.5/sdk.md

Added .NET sdk link
and updated the latest version of the SDK page.
the changes.
works.

docs: add dotnet sdk

---

docs/package-lock.json
docs/sidebar.json

fix: docs build

---

docs/docs/concepts/identity-data-model.md
docs/versioned_docs/version-v0.5/concepts/identity-data-model.md

Fixes the currently broken https://www.ory.sh/kratos/docs/concepts/identity-data-model page
the changes.
works.

chore: fix mermaid

---

docs/docs/concepts/email-sms.md
docs/versioned_docs/version-v0.5/concepts/email-sms.md

closes https://github.com/ory/kratos/issues/1194
@Mrmebelman can you confirm this? 
I didnt get around to test it yet. 
the changes.
works.

fix: courier adress

---

docs/sidebar.json
docs/src/css/theme.css

feat: global docs sidebar

---

driver/config/config.go

fix: do not include smtp in tracing

---

go.mod
selfservice/strategy/oidc/strategy.go
selfservice/strategy/oidc/strategy_registration.go
selfservice/strategy/profile/strategy.go
test/e2e/cypress/integration/profiles/oidc/registration/success.spec.js
test/e2e/profiles/oidc/identity.traits.schema.json
ui/container/container.go
ui/node/node_test.go

fix: resolve incorrect field types on oidc sign up completion

---

selfservice/strategy/oidc/provider_github.go

feat: add gh login to claims

---

continuity/manager_cookie.go
selfservice/strategy/oidc/strategy_registration.go

fix: remove continuity cookies on errors

---

.schema/api.openapi.json
.schema/openapi.json
docs/versioned_docs/version-v0.6/reference/configuration.md
driver/config/.schema/config.schema.json
internal/httpclient/README.md
internal/httpclient/api/openapi.yaml
internal/httpclient/api_admin.go
internal/httpclient/docs/AdminApi.md
schema/errors.go
spec/api.json
spec/openapi.json
spec/swagger.json

Hi @aeneasr, some little changes in the docs + single spelling.

Documentation fixes: Hydra => Kratos

---

docs/docs/sdk.md
docs/versioned_docs/version-v0.6/sdk.md

chore: fix misprint

---

docs/docs/self-service/flows/code/registration/samples/password.policy.txt
docs/docs/self-service/flows/code/settings/samples/password.policy.txt
selfservice/strategy/password/validator.go

fix: remove trailing double-dot from error

---

docs/docs/concepts/email-sms.md
docs/versioned_docs/version-v0.6/concepts/email-sms.md

Update a link to example email template in documentation.
the changes.
works.

Fix: Update link to example email template.

---

session/manager_http.go
session/manager_http_test.go

fix(session): use specific headers before bearer use

---

docs/docs/self-service/flows/code/login/samples/api/init.go.txt
docs/docs/self-service/flows/code/login/samples/api/init.js.txt
docs/docs/self-service/flows/code/recovery/samples/api/init.go.txt
docs/docs/self-service/flows/code/recovery/samples/api/init.js.txt
docs/docs/self-service/flows/code/registration/samples/api/init.go.txt
docs/docs/self-service/flows/code/registration/samples/api/init.js.txt
docs/docs/self-service/flows/code/settings/samples/api/init.go.txt
docs/docs/self-service/flows/code/settings/samples/api/init.js.txt
docs/docs/self-service/flows/code/verification/samples/api/init.go.txt
docs/docs/self-service/flows/code/verification/samples/api/init.js.txt

docs: update sdk use

---

internal/testhelpers/selfservice_recovery.go
internal/testhelpers/server.go
selfservice/flow/recovery/handler.go
selfservice/strategy/link/.schema/recovery.schema.json
selfservice/strategy/link/.schema/verification.schema.json
selfservice/strategy/link/strategy_recovery_test.go
selfservice/strategy/link/strategy_verification_test.go

test: add tests for cookie behavior of API and browser endpoints

---

selfservice/strategy/link/strategy_recovery_test.go
selfservice/strategy/link/strategy_verification_test.go
selfservice/strategy/oidc/strategy_settings_test.go
selfservice/strategy/oidc/strategy_test.go
selfservice/strategy/profile/strategy_test.go
text/message.go
ui/node/fixtures/sort/expected/1.json
ui/node/fixtures/sort/expected/2.json
ui/node/fixtures/sort/expected/3.json

Closes #1361
Closes #1362
the changes.
works.

fix: mark ui node message as optional

---

docs/docs/concepts/email-sms.md

Fixes https://github.com/ory/kratos/issues/1351

docs: update documentation for plaintext templates

---

.github/ISSUE_TEMPLATE/config.yml
.github/pull_request_template.md
CONTRIBUTING.md
README.md
docs/docs/contributing.md

Updated repository templates to https://github.com/ory/meta/commit/064b19ddd16977b9a9fba72c3383b967d9f8ad78.

chore: update repository template to 064b19dd

---

.circleci/config.yml
spec/openapi.json
spec/swagger.json

ci: use explicit go mod cache

---

.schema/openapi/patches/meta.yaml
internal/httpclient/README.md
internal/httpclient/api/openapi.yaml
spec/openapi.json
spec/swagger.json
swagger_meta.go

Closes #1426
the changes.
works.

fix: deprecate sessionCookie

---

courier/courier.go
test/e2e/profiles/kratos.base.yml

Closes #781
the changes.
works.

fix: use STARTTLS for smtps connections

---

persistence/sql/persister.go

fix: do not cache incomplete migrations

---

README.md

Should be merged after https://github.com/ory/kratos/pull/1438. 
When this is correct, I will add it to hydra,keto,oathkeeper in a similar fashion.
https://github.com/ory/kratos/issues/1423
the changes.
works.

chore: add CoC shield

---

README.md

As discussed in https://github.com/ory/kratos/pull/1444, 
here is the completed CII badge for Kratos.

docs: correct CII badge

---

README.md

Updated repository templates to https://github.com/ory/meta/commit/9eaaf9b10f7713120aea9fe435fb73d49be29acd.

chore: update repository template to 9eaaf9b1

---

README.md

docs: updated go dependency to 1.16 because of embed package. GOMODULES is on in this version by default, so I removed it.
the changes.
works.

docs: Update README.md golang dependency

---

go.mod
go.sum

@aeneasr: this is a follow up for https://github.com/ory/x/pull/356 PR. It just makes use of the corresponding version.
the changes.
works.

feat: using ory/x v0.0.256

---

docs/docs/install.md

The old instructions did not work (same result as described here: https://github.com/ory/kratos/issues/979)

docs: [install] fix building from source

---

docs/docs/install.md
docs/versioned_docs/version-v0.5/install.md
docs/versioned_docs/version-v0.6/install.md

closes https://github.com/ory/kratos/issues/1508
the changes.
works.

fix: link to docker guide

---

selfservice/strategy/link/strategy_verification.go
selfservice/strategy/link/strategy_verification_test.go
text/message_verification.go

Closes #1450
the changes.
works.

fix: add verification success message

---

docs/docs/self-service/flows/verify-email-account-activation.mdx
docs/versioned_docs/version-v0.7/self-service/flows/verify-email-account-activation.mdx

The formatting of the `v0.7` and `next` documentation page contains some broken formatting. It seems like the introduction of the Tabs for Ory Cloud Platform and Ory Kratos broke the Markdown formatting (see images below).
the changes.
works.
Please let me know if the indentation of the config snippet is correct.

autogen(docs): fix formatting of Email and Phone Verification Flow tab content

---

docs/config.js
driver/config/.schema/config.schema.json
quickstart.yml

Resolve various 0.7.0 issues

---

docs/README.md
docs/docs/self-service/flows/user-registration.mdx

docs: add instruction for creating user 

---

go.mod
internal/testhelpers/e2e_server.go
selfservice/flow/nosurf.go
selfservice/flow/recovery/flow.go
selfservice/flow/verification/flow.go
selfservice/strategy/link/strategy_recovery.go
selfservice/strategy/link/strategy_recovery_test.go
selfservice/strategy/link/strategy_verification.go
selfservice/strategy/link/strategy_verification_test.go

fix: generate CSRF token on validation creation

---

internal/testhelpers/e2e_server.go
schema/.schema/extension/identity.schema.json

Schema what

---

schema/extension.go

fix: export extensionschemas

---

docs/docs/debug/csrf.mdx

Closes #1557
the changes.
works.

docs: update csrf pitfall flow section

---

selfservice/strategy/link/fixtures/recovery_init.json
selfservice/strategy/link/fixtures/recovery_submit.json
selfservice/strategy/link/fixtures/verification_init.json
selfservice/strategy/link/fixtures/verification_submit.json
selfservice/strategy/link/strategy_recovery.go
selfservice/strategy/link/strategy_recovery_test.go
selfservice/strategy/link/strategy_verification_test.go
test/e2e/cypress/integration/profiles/recovery/recovery/errors.spec.js
test/e2e/cypress/integration/profiles/recovery/recovery/success.spec.js
test/e2e/cypress/integration/profiles/verification/verify/success.spec.js

fix: do not reset link method

---

selfservice/strategy/profile/.schema/settings.schema.json
session/handler.go
session/handler_test.go

fix: do not set csrf cookies on /sessions/whoami

---

selfservice/flow/logout/handler.go
selfservice/flow/logout/handler_test.go
spec/api.json

Before, the logout endpoint would invalidate the session cookie, but not remove it. This was a regression introduced in 0.7.0. This patch resolves that issue.
Closes #1584
the changes.
works.

fix: remove session cookie on logout

---

x/nosurf.go
x/nosurf_test.go

See https://github.com/ory-corp/cloud/issues/1252
the changes.
works.

fix: update csrf token cookie name

---

docs/config.js
docs/package.json

Closes #1597
the changes.
works.

fix(docs): ensure config reference is updated

---

docs/docs/concepts/identity-data-model.mdx
docs/versioned_docs/version-v0.7/concepts/identity-data-model.mdx

closes https://github.com/ory/kratos/issues/43
the changes.
works.

docs: document that traits are visible to user

---

docs/docs/self-service/flows/account-recovery.mdx
docs/docs/self-service/flows/verify-email-account-activation.mdx
docs/versioned_docs/version-v0.7/self-service/flows/account-recovery.mdx
docs/versioned_docs/version-v0.7/self-service/flows/verify-email-account-activation.mdx

Fixes incorrect YAML indentation in docs for Account Recovery and Account Activation
the changes.
works.

docs: Fixes incorrect yaml identation

---

docs/docs/self-service/flows/user-facing-errors.md
docs/versioned_docs/version-v0.7/self-service/flows/user-facing-errors.md

closes https://github.com/ory/kratos/issues/1568
the changes.
works.

docs: fix stub error example

---

selfservice/flow/registration/hook.go
selfservice/strategy/password/registration_test.go

fix:add session in spa registration if session cook is configured

---

docs/docs/concepts/browser-redirect-flow-completion.mdx

Improve the documentation on browser redirect whitelist urls.
the changes.
works.

docs: browser redirects

---

session/manager_http.go
session/manager_http_test.go

Closes #1695
the changes.
works.

fix: do not panic if cookiemanager returns a nil cookie

---

selfservice/flow/logout/handler.go
spec/api.json
spec/swagger.json

docs: mark logout_url always available

---

.circleci/config.yml

ci: bump goreleaser orb

---

.circleci/config.yml
.schema/openapi/patches/selfservice.yaml

ci: bump goreleaser

---

.schema/openapi/patches/selfservice.yaml
internal/httpclient/api/openapi.yaml
internal/httpclient/docs/SelfServiceLogoutUrl.md
internal/httpclient/docs/SubmitSelfServiceRegistrationFlowBody.md
internal/httpclient/docs/SubmitSelfServiceSettingsFlowBody.md
internal/httpclient/docs/V0alpha1Api.md
internal/httpclient/model_self_service_logout_url.go
internal/httpclient/model_submit_self_service_registration_flow_body.go
internal/httpclient/model_submit_self_service_settings_flow_body.go
spec/api.json

fix: corret sdk annotations for enums

---

docs/docs/self-service.mdx

the changes.
works.
[related discussion](https://github.com/ory/kratos/discussions/1748)

docs: fix the flow links used for rendering

---

docs/docs/self-service/flows/user-logout.mdx

docs: add a commandline example for the logout

---

internal/httpclient/README.md
internal/httpclient/api/openapi.yaml
internal/httpclient/api_v0alpha1.go
internal/httpclient/docs/V0alpha1Api.md
session/handler.go
spec/api.json
spec/swagger.json

This is an addendum to #1740 . I've missed one spot in the swagger definitions and had to regenerate SDK.
Contributes to #655 
the changes.
works.

fix: update SDK and fix /identities/:id/session endpoint in swagger/openapi

---

docs/docs/self-service/flows/code/logout/samples/browser/node.txt
internal/httpclient/api/openapi.yaml
internal/httpclient/docs/SelfServiceLogoutUrl.md
internal/httpclient/model_self_service_logout_url.go
selfservice/flow/logout/handler.go
selfservice/flow/logout/handler_test.go
spec/api.json
spec/swagger.json

feat(logout): add logout token to browser response

---

schema/handler.go
schema/handler_test.go
schema/schema.go
schema/schema_test.go

This PR implements an endpoint to list all Json schemas
https://github.com/ory/kratos/issues/1699
the changes.
works.

feat: Add all json schemas endpoint

---

docs/docs/quickstart.mdx

Closes #1793
the changes.
works.

docs: use correct link

---

docs/versioned_docs/version-v0.7/guides/login-session.mdx

Add missing angle bracket

---

.docker/Dockerfile
.docker/Dockerfile-build
.docker/Dockerfile-sqlite
.github/workflows/cve-scan.yaml
Makefile

feat: introduce cve scanning

---

.github/workflows/cve-scan.yaml
go.mod
go.sum
selfservice/strategy/oidc/provider_microsoft.go

- Replace deprecated go-jwt library with its new version
the changes.
works.

chore: replace deprecated package

---

.schema/openapi/patches/session.yaml
spec/api.json

Fixes #1913 
the changes.
works.

fix: adds missing webauthn authentication method

---

.circleci/config.yml
cmd/clidoc/main.go
docs/docs/concepts/ui-user-interface.mdx
selfservice/strategy/link/.snapshots/TestRecovery-description=should_set_all_the_correct_recovery_payloads.json
selfservice/strategy/link/.snapshots/TestVerification-description=should_set_all_the_correct_verification_payloads.json
selfservice/strategy/link/strategy_recovery.go
selfservice/strategy/link/strategy_verification.go
text/message_node.go

Closes #1909
the changes.
works.

fix: include text label for link email field

---

docs/docs/concepts/ui-user-interface.mdx
test/e2e/package-lock.json
test/e2e/run.sh

fix: speed up git clone

---

Makefile
contrib/quickstart/kratos/cloud/Caddyfile
contrib/quickstart/kratos/cloud/identity.schema.json
contrib/quickstart/kratos/cloud/kratos.yml
contrib/quickstart/kratos/cloud/quickstart.yml
contrib/quickstart/kratos/email-password/kratos.yml
docs/docs/concepts/ui-user-interface.mdx

Add hostedui

---

cmd/daemon/serve.go
docs/docs/concepts/ui-user-interface.mdx
driver/registry.go
driver/registry_default.go
go.mod
go.sum
session/manager_http_test.go
x/nosurf.go

fix: do not use csrf for meta endpoints

---

docs/docs/concepts/email-sms.md

docs: update email template docs (#1960)

---

docs/docs/concepts/ui-user-interface.mdx
text/message_verification.go

the changes.
works.
This PR fixes an apparent mistake that causes the message ID 1060002 to be shared by two unrelated messages.

fix: verification error code

---

.docker/Dockerfile
.docker/Dockerfile-build
.docker/Dockerfile-sqlite
docs/docs/concepts/ui-user-interface.mdx

CI failing on master: https://github.com/ory/kratos/runs/4285533419?check_suite_focus=true

chore: bump alpine images

---

docs/docs/debug/csrf.mdx
docs/versioned_docs/version-v0.8/debug/csrf.mdx

docs(debug): fix typo

---

go.mod
go.sum

Closes #1645
the changes.
works.

fix: resolve freebsd build issue

---

docs/docs/quickstart.mdx
docs/versioned_docs/version-v0.8/quickstart.mdx

- fixes the social login links in quickstart.
same format as the other working links in the document.

fix: quickstart next steps links

---

test/e2e/cypress/integration/profiles/verification/registration/errors.spec.ts
test/e2e/cypress/integration/profiles/verification/verify/errors.spec.ts
test/e2e/cypress/integration/profiles/verification/verify/success.spec.ts

#1973 de-duplicated some message IDs. One of them changed that was used as a selector in the e2e test. This PR replaces it for the new ID.
CI is currently failing on all branches because of that

test: fix changed message ID

---

docs/docs/faq.mdx

Not sure if there is a better link/documentation to link to.
the changes.
works.

docs: webhooks have landed

---

docs/docs/concepts/security.mdx

docs: Levenshtein-Distance has been released

---

docs/docs/concepts/security.mdx

docs: password-strength meter has been dropped

---

docs/docs/self-service/flows/user-settings.mdx

docs: this has been done

---

embedx/config.schema.json
test/schema/fixtures/config.schema.test.success/root.full.yml

fix: support complex lifespans

---

docs/docs/concepts/email-sms.md
docs/versioned_docs/version-v0.8/concepts/email-sms.md

- removes a duplicate sentence

fix: duplicate sentence

---

.docker/Dockerfile-build

Looks like this was attempted before but the magic comment was not on the first line.
the changes.
works.

Enable Buildkit

---

courier/template/load_template.go
courier/template/load_template_test.go
courier/template/recovery_invalid.go
courier/template/recovery_valid.go
courier/template/stub.go
courier/template/verification_invalid.go
courier/template/verification_valid.go

feat: expose courier template load

---

test/e2e/package-lock.json
test/e2e/package.json

test: update cypress

---

quickstart.yml

Fixes quickstart.yml
the changes.
works.

Added missed version tag in quickstart.yml

---

continuity/manager_cookie.go
continuity/manager_test.go
x/nosurf.go

Closes #2109
the changes.
works.

fix: resolve resumable and csrf cookie issues

---

go.mod
go.sum

Resolves an issue where, when multiple CSRF cookies are set, a random one would be used to verify the CSRF token. Now, regardless of how many conflicting CSRF cookies exist, if one of them is valid, the request will pass and clean up the cookie store.
See ory/kratos#2121
See ory-corp/cloud#1786
the changes.
works.

fix: choose correct CSRF cookie when multiple are set

---

continuity/manager_cookie.go
continuity/manager_test.go
x/cookie.go
x/cookie_test.go

Resolves several reports related to incorrect handling of invalid continuity issues.
Closes #2121
Closes ory-corp/cloud#1786
Closes https://github.com/ory/kratos/issues/2016
Potentially https://github.com/ory/kratos/discussions/2108
the changes.
works.

fix(continuity): properly reset cookies that became invalid

---

courier/test/persistence.go
persistence/sql/persister_test.go

feat: generalise courier tests

---

persistence/sql/persister_test.go
persistence/sql/testhelpers/network.go

fix: expose network wrapper

---

courier/test/persistence.go
persistence/sql/persister_test.go
persistence/sql/testhelpers/network.go

fix: improve courier test signature

---

quickstart-standalone.yml

This change updates the service definition for the `kratos-selfservice-ui-node` container found in `./quickstart-standalone.yml`. The `docker-compose` command will fail due to the invalid yaml configuration. 
I was following the steps in the [Quickstart](https://www.ory.sh/kratos/docs/quickstart/#clone-ory-kratos-and-run-it-in-docker) section for Ory Kratos using macOS. The set of docker containers will not run as instructed without this fix.
This bug was introduced with [this change](https://github.com/ory/kratos/commit/52420ccc17a8d395f0b13c0ad03ac334434c4b0e). …

fix: quickstart standalone service definition

---

persistence/sql/persister_identity.go
selfservice/strategy/password/login_test.go
selfservice/strategy/password/registration_test.go
test/e2e/cypress/integration/profiles/email/login/success.spec.ts

All identifiers are trimmed before they are passed to the database.
closes #2158
the changes.
works.

fix: Ignore whitespace around identifier with password strategy

---

docs/docs/guides/production.md
driver/config/config.go
driver/config/config_test.go
driver/registry_default.go
embedx/config.schema.json
go.mod
go.sum
persistence/sql/testhelpers/network.go
selfservice/hook/web_hook.go
selfservice/hook/web_hook_integration_test.go
selfservice/hook/web_hook_test.go
x/http.go

Closes #2152
the changes.
works.

feat(security): add option to disallow private IP ranges in webhooks

---

.schema/openapi/patches/session.yaml

Closes https://github.com/ory/sdk/issues/147
the changes.
works.

fix: add missing enum

---

driver/registry.go

fix: add CourierConfig to default registry

---

.github/workflows/ci.yaml

Fixes branch protection error.

fix: pass token to render-version-schema

---

driver/config/handler.go
driver/config/handler_test.go
driver/registry_default.go
selfservice/flow/settings/strategy_helper_test.go
test/e2e/.gitignore
test/e2e/cypress.json
test/e2e/cypress/integration/profiles/mfa/mix.spec.ts
test/e2e/cypress/integration/profiles/mfa/webauthn.spec.ts
test/e2e/cypress/plugins/index.js
test/e2e/cypress/support/commands.ts
test/e2e/package-lock.json
test/e2e/package.json

test(e2e): wait for initial network requests

---

selfservice/strategy/password/validator.go
selfservice/strategy/password/validator_test.go

Closes #2145
the changes.
works.

fix: do not error when HIBP behaves unexpectedly

---

cmd/jsonnet/lint.go
go.mod
go.sum
persistence/sql/persister_test.go
request/builder.go
request/builder_test.go
request/stub/cancel_body.jsonnet
selfservice/hook/stub/cancel_template.jsonnet
selfservice/hook/web_hook.go
selfservice/hook/web_hook_integration_test.go

feat: cancelable web hooks

---

embedx/config.schema.json
persistence/sql/persister_test.go
selfservice/hook/web_hook.go
selfservice/hook/web_hook_integration_test.go
test/schema/fixtures/config.schema.test.success/selfServiceWebHook.noauth.yaml

Introduces the ability to ignore responses from web hooks in favor of faster and non-blocking execution.
Closes #1702
the changes.
works.

feat: ignore web hook response

---

selfservice/strategy/password/login.go

Closes https://github.com/ory/kratos/issues/2264
the changes.
works.

chore: remove issue reference

---

selfservice/flow/login/sort.go

fix: order regression

---

selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=mfa-case=webauthn_payload_is_set_when_identity_has_webauthn.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=passwordless-case=should_fail_if_webauthn_login_is_invalid-type=browser.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=passwordless-case=should_fail_if_webauthn_login_is_invalid-type=spa.json
selfservice/strategy/webauthn/login.go
selfservice/strategy/webauthn/login_test.go
test/e2e/cypress/integration/profiles/mfa/webauthn.spec.ts

fix(webauthn): resolve missing identifier bug

---

.docker/Dockerfile-alpine
.docker/Dockerfile-build

fix: update alpine version

---

ui/node/attributes.go

Closes https://github.com/ory/sdk/issues/157
the changes.
works.

fix: mark width and height as required

---

README.md

chore: update coupon

---

selfservice/flow/login/sort.go
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=mfa-case=webauthn_payload_is_set_when_identity_has_webauthn.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=passwordless-case=webauthn_button_exists.json
selfservice/strategy/webauthn/login_test.go

fix: unstable webauthn order

---

.github/workflows/ci.yaml
.schema/version.schema.json

The path in the CI parameter was wrong.

fix: update v0.9.0-alpha.2 config schema path

---

.schema/version.schema.json

Manual migration according to https://github.com/ory/cli/pull/155

fix(version schema): require version or fall back to latest

---

continuity/manager_cookie.go

fix: typo in error message

---

selfservice/flow/login/handler.go
selfservice/flow/recovery/handler.go
selfservice/flow/registration/handler.go
selfservice/flow/settings/handler.go
selfservice/flow/verification/handler.go

docs: add missing error codes

---

selfservice/flow/login/handler.go
selfservice/flow/login/handler_test.go

Closes #2341
the changes.
works.

fix: refresh is always false when session exists

---

courier/courier.go

fix(courier): add ability to specify backoff

---

.docker/Dockerfile-alpine
.docker/Dockerfile-build

Currently when executing `make docker` on master, I get the following errors:
```shell
root@somewhere:~/kratos# make docker
DOCKER_BUILDKIT=1 docker build -f .docker/Dockerfile-build --build-arg=COMMIT=9097a60ede283fb2f6a912f2ab1ae1713d6598dd --build-arg=BUILD_DATE=2022-04-12T09:25:47Z -t oryd/kratos:latest .
[+] Building 2.0s (6/6) FINISHED                                                                                                                                                                                                                                         
=> [internal] load build definition from Dockerfile-build …
```

fix: make docker on master (inexistent docker alpine version)

---

.schema/openapi/patches/session.yaml

Closes #2398
the changes.
works.

fix: add legacy session value

---

hash/hash_comparator.go
hash/hasher_test.go
identity/.snapshots/TestHandler-case=should_be_able_to_import_users-with_argon2i_password.json
identity/handler_import.go
identity/handler_test.go

[Is Ory Kratos support for hasher $argon2i instead using $argon2id](https://github.com/ory/kratos/discussions/2373)
the changes.
works.

Support argon2i password

---

embedx/config.schema.json
selfservice/strategy/oidc/provider_config.go
selfservice/strategy/oidc/provider_netid.go
selfservice/strategy/oidc/provider_private_net_test.go

Added support for NetID as a separate provider in Kratos config.
As discussed with @aeneasr added also screen record of the working flow.
I have also docs https://github.com/ory/docs/pull/755 describing how to set it up. 
Note: due to tech limitations of NetID redirect URIs for local testing I had to use https and fake domain `test.local` on my machine - which complicated a bit the local setup but that's a different stOry ;-) 
the changes.
works. …

feat: add support for netID provider 

---

selfservice/strategy/password/types.go

Closes #2408
the changes.
works.

fix: remove required legacy field

---

selfservice/strategy/oidc/provider_netid.go

fix: compile issues from merge conflict

---

examples/go/selfservice/login/main.go

db638cd3bb1fdb5688d1acc44045dd94595d5e77
the changes.
works.

fix: use pointer of string for PasswordIdentifier in example code

---

embedx/config.schema.json

I just ran into the issue described in the change so I thought it would be nice to be documented here.

Add docs about change in default schema

---

Makefile
script/add-down-migrations.sh

In order for the migration box to work correctly, every up migration
must have a corresponding down migration. We just add empty files
in this case.
the changes.
works.

chore: add missing down migrations

---

Makefile

Closes #2488
the changes.
works.

fix: quickstart docker-compose

---

identity/identity_verification.go

the changes.
works.
I have explained in detail regarding this issue over here: https://github.com/ory/kratos/issues/2506

fix: make ID field in VerifiableAddress struct optional

---

selfservice/flow/logout/handler.go

vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the
maintainers to push the changes.

docs(sdk): incorrect URL

---

selfservice/flow/verification/handler.go

vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the
maintainers to push the changes.

chore: broken link in API docs

---

cmd/identities/definitions.go

chore: dry up code

---

.docker/Dockerfile-alpine
.docker/Dockerfile-build

fix: bump docker image

---

selfservice/flow/recovery/error.go
test/e2e/cypress/integration/profiles/recovery/recovery/errors.spec.ts

fix: duplicate messages in recovery flow

---

cmd/identities/validate.go
internal/httpclient/.openapi-generator/FILES
internal/httpclient/README.md
internal/httpclient/api/openapi.yaml
internal/httpclient/api_v0alpha2.go
internal/httpclient/docs/IdentitySchemaContainer.md
internal/httpclient/docs/V0alpha2Api.md
internal/httpclient/model_identity_schema_container.go
schema/handler.go
spec/api.json
spec/swagger.json

BREAKING CHANGE: SDK Method `getJsonSchema` was renamed to `getIdentitySchema`.

refactor(sdk): rename `getJsonSchema` to `getIdentitySchema`

---

driver/config/config.go
driver/config/config_test.go

test: parallelize and speed up config tests

---

selfservice/strategy/link/.snapshots/TestRecovery-description=should_set_all_the_correct_recovery_payloads_after_submission.json
selfservice/strategy/link/.snapshots/TestVerification-description=should_set_all_the_correct_verification_payloads_after_submission.json
selfservice/strategy/link/strategy_recovery.go
selfservice/strategy/link/strategy_verification.go
test/e2e/cypress/support/commands.ts

fix: disappearing title label on verification and recovery flow

---

internal/httpclient/api/openapi.yaml
internal/httpclient/docs/UiNodeInputAttributes.md
internal/httpclient/model_ui_node_input_attributes.go
spec/api.json
spec/swagger.json
ui/node/attributes.go

fix: revert removal of required field in uiNodeInputAttributes

---

.github/conventional_commits.json

Add the additional scopes used in this repo, taken from https://github.com/ory/kratos/commit/e55d22f1601e343a7a910ce3a50874a2991cebef.

ci: additional types and scopes for conventional commits

---

driver/registry_default.go

See https://github.com/ory-corp/cloud/issues/2691

fix: cache migration status

---

persistence/sql/persister.go

fix: wrap migration error in WithStack

---

.docker/Dockerfile-build

add missing dependencies for docker build, without them the `make docker` command will fail with the following error
```
=> ERROR [base 9/9] RUN --mount=type=cache,target=/root/.cache/go-build go build -tags sqlite     -ldflags="-X 'github.com/ory/kratos/driver/config.Version=${VERSION}' -X 'github.com/ory/kratos/driver/config.Date=2022-08-05T08  0.8s
------
> [base 9/9] RUN --mount=type=cache,target=/root/.cache/go-build go build -tags sqlite     -ldflags="-X 'github.com/ory/kratos/driver/config.Version=${VERSION}' -X 'github.com/ory/kratos/driver/config.Date=2022-08-05T08:57:33Z' -X 'github.com/ory/kratos/driver/config.Commit=8fa14ecb41aa08f9d532439cf5d50bcd8fc5f55f'"     -o /usr/bin/kratos:
#18 0.746 # github.com/mattn/go-sqlite3
#18 0.746 cgo: C compiler "gcc" not found: exec: "gcc": …
```

fix: add missing docker dependencies

---

.github/workflows/ci.yaml
identity/handler.go
request/builder.go
request/builder_test.go
schema/handler.go
selfservice/errorx/handler.go
selfservice/flow/login/handler.go
selfservice/flow/logout/handler.go
selfservice/flow/recovery/handler.go
selfservice/flow/registration/handler.go
selfservice/flow/settings/handler.go
selfservice/flow/verification/handler.go
selfservice/hook/web_hook.go
selfservice/hook/web_hook_integration_test.go
selfservice/strategy/link/strategy_recovery.go
selfservice/strategy/oidc/strategy.go
selfservice/strategy/oidc/strategy_login.go
selfservice/strategy/oidc/strategy_registration.go
selfservice/strategy/oidc/strategy_settings.go
selfservice/strategy/oidc/strategy_state_test.go
selfservice/strategy/webauthn/handler.go
session/handler.go
swagger_meta.go
x/http.go
x/http_test.go

feat: improve oidc state

---

session/handler.go
session/handler_test.go

fix: ignore CSRF for session extension on public route

---

.schema/openapi/patches/schema.yaml

fix: remove rust workaround

---

quickstart.yml

fix: re-add service to quickstart

---

cmd/identities/import.go

docs: importing credentials supported

---

selfservice/strategy/password/validator.go
selfservice/strategy/password/validator_test.go

fix: ignore commata in HIBP response

---

driver/config/config.go
driver/registry_default_recovery.go
driver/registry_default_settings.go
driver/registry_default_test.go
driver/registry_default_verify.go
embedx/config.schema.json
internal/testhelpers/selfservice.go
selfservice/flow/recovery/handler.go
selfservice/flow/recovery/hook.go
selfservice/flow/recovery/hook_test.go
selfservice/flow/registration/hook.go
selfservice/flow/registration/hook_test.go
selfservice/flow/settings/error.go
selfservice/flow/settings/handler.go
selfservice/flow/settings/hook.go
selfservice/flow/settings/hook_test.go
selfservice/flow/verification/handler.go
selfservice/flow/verification/hook.go
selfservice/flow/verification/hook_test.go
selfservice/hook/error.go
selfservice/hook/web_hook.go
selfservice/strategy/link/strategy.go

Adds pre-hooks to settings, verification, and recovery flows.

feat: add pre-hooks to settings, verification, recovery

---

package-lock.json
package.json

Getting everything properly formatted with the latest formatting standard to prepare rolling out formatting checks on CI.
the changes.
works.

chore: organize package.json

---

hash/hash_comparator.go
hash/hasher_scrypt.go
hash/hasher_test.go
identity/.snapshots/TestHandler-case=should_be_able_to_import_users-with_scrypt_password.json
identity/handler_import.go
identity/handler_test.go

#2422 
If this pull request addresses a security. vulnerability,

feat: allow importing scrypt hashing algorithm

---

identity/handler.go
identity/handler_test.go

fix: patch invalidates credentials

---

.github/workflows/format.yml
Makefile
package.json

Addresses parts of https://github.com/ory-corp/general/issues/735.
the changes.
works.

chore: format using Make

---

package.json

Cleanup a leftover empty script.
https://github.com/ory-corp/general/issues/735
the changes.
works.

chore: remove empty script

---

cmd/identities/delete.go
cmd/identities/get.go
cmd/identities/import.go
cmd/identities/list.go
cmd/root.go
cmd/root_test.go
go.mod
go.sum

similar to https://github.com/ory/hydra/pull/3279

refactor: use gotemplates for command usage

---

identity/handler.go

fix: proper annotation for patch

---

.gitignore
test/e2e/cypress/integration/profiles/email/error/ui.spec.ts
test/e2e/cypress/integration/profiles/email/login/error.spec.ts
test/e2e/cypress/integration/profiles/email/logout/success.spec.ts
test/e2e/cypress/integration/profiles/email/registration/errors.spec.ts
test/e2e/cypress/integration/profiles/email/registration/success.spec.ts
test/e2e/cypress/integration/profiles/email/settings/ui.spec.ts
test/e2e/cypress/integration/profiles/import/import.spec.ts
test/e2e/cypress/integration/profiles/mfa/lookup.spec.ts
test/e2e/cypress/integration/profiles/mfa/mix.spec.ts
test/e2e/cypress/integration/profiles/mfa/totp.spec.ts
test/e2e/cypress/integration/profiles/network/errors.spec.ts
test/e2e/cypress/integration/profiles/oidc/login/success.spec.ts
test/e2e/cypress/integration/profiles/oidc/logout/success.spec.ts
test/e2e/cypress/integration/profiles/oidc/registration/success.spec.ts
test/e2e/cypress/integration/profiles/oidc/settings/error.spec.ts
test/e2e/cypress/integration/profiles/oidc/settings/success.spec.ts
test/e2e/cypress/integration/profiles/passwordless/flows.spec.ts
test/e2e/cypress/integration/profiles/recovery/code/errors.spec.ts
test/e2e/cypress/integration/profiles/recovery/link/errors.spec.ts
test/e2e/cypress/integration/profiles/webhoooks/registration/success.spec.ts
test/e2e/cypress/support/commands.ts
test/e2e/cypress/support/index.d.ts

fix: express e2e tests

---

selfservice/strategy/code/strategy_recovery.go
selfservice/strategy/code/strategy_recovery_test.go

This PR fixes an issue, where the field validation message is not cleared if a "global" error (e.g. invalid code) occures.
#2799
the changes.
works.

fix: clear recovery code validation message on every submission

---

session/session.go
session/session_test.go

fix: x-forwarded-for header parsing

---

session/handler.go
session/handler_test.go
session/manager.go
session/manager_http.go

feat: add cache headers

---

.github/ISSUE_TEMPLATE/BUG-REPORT.yml
.github/ISSUE_TEMPLATE/DESIGN-DOC.yml
.github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
README.md

Reword intro to refer to the Ory Network
Contributes to https://github.com/ory-corp/cloud/issues/3186

feat: update for the Ory Network

---

persistence/sql/persister_recovery.go

Quick fix, as I noticed it during the monitoring workshop.
the changes.
works.

fix: correct name of span on recovery code deletion

---

internal/httpclient/api/openapi.yaml
internal/httpclient/docs/AdminCreateSelfServiceRecoveryCodeBody.md
internal/httpclient/docs/AdminCreateSelfServiceRecoveryLinkBody.md
internal/httpclient/model_admin_create_self_service_recovery_code_body.go
internal/httpclient/model_admin_create_self_service_recovery_link_body.go
selfservice/strategy/code/strategy_recovery.go
selfservice/strategy/link/strategy_recovery.go
spec/api.json
spec/swagger.json

Closes #2579
the changes.
works.

fix: wrong config key in admin recovery documentation

---

hydra/hydra.go

chore: debugf

---

.schema/openapi/patches/identity.yaml

Closes https://github.com/ory/sdk/issues/218
the changes.
works.

fix(sdk): identity metadata is nullable

---

selfservice/strategy/code/.snapshots/TestAdminStrategy-case=form_should_not_contain_email_field_when_creating_recovery_code.json
selfservice/strategy/code/strategy_recovery.go
selfservice/strategy/code/strategy_recovery_test.go

Another quick fix for issues I noticed during example making
#2845
the changes.
works.

fix: admin recovery CSRF & duplicate form elements

---

go.mod
go.sum
session/handler.go

chore: update ory/x

---

go.mod
go.sum
identity/extension_credentials.go
identity/extension_credentials_test.go
identity/stub/extension/credentials/multi.schema.json

fix: distinguish credential types properly when collecting identifiers

---

codecov.yml

fix: codecov

---

.mailmap
AUTHORS
Makefile

https://github.com/ory-corp/general/issues/732
and signed the CLA.
confirm that I got approval (please contact
the changes.
works.
appropriate).

chore: list contributors in file

---

selfservice/hook/web_hook.go
selfservice/hook/web_hook_integration_test.go

See https://github.com/ory-corp/cloud/issues/3360
the changes.
works.

fix: do not double-commit webhooks on registration

---

cmd/courier/watch.go
courier/courier.go
courier/courier_dispatcher_test.go
courier/sms_test.go
courier/smtp.go
courier/smtp_test.go
driver/config/config.go
driver/config/config_test.go
driver/registry_default.go
selfservice/strategy/code/sender.go
selfservice/strategy/link/sender.go

Closes https://github.com/ory-corp/cloud/issues/3321
the changes.
works.

fix: do not crash process on invalid smtp url

---

internal/client-go/model_ui_text.go
internal/httpclient/model_ui_text.go
selfservice/hook/web_hook.go
spec/api.json
spec/swagger.json
text/message.go
text/message_recovery.go
text/message_settings.go
text/message_verification.go
text/type.go

feat: add "success" UITextType

---

driver/config/config_test.go
embedx/config.schema.json

- Fix the feature flag default to be false.

fix: session whoami cache default to false

---

selfservice/hook/web_hook.go

Previously the context was not propagated to the http client. As a result the (instrumented) client did not find the existing span and the sapns for outgoing http request have been orphains.  With this simple Fix they are now children of the corresponding webhook spans.
the changes.
works.

fix: tracing in web hooks

---

driver/config/config_test.go

chore: cleanup test

---

internal/client-go/api_identity.go
internal/httpclient/api_identity.go
selfservice/strategy/code/strategy_recovery.go
selfservice/strategy/link/strategy_recovery.go
session/handler.go
spec/api.json
spec/swagger.json

chore: add missing security annotations to admin handlers

---

persistence/sql/migrations/sql/20221220124639000000_errors_index.down.sql
persistence/sql/migrations/sql/20221220124639000000_errors_index.mysql.down.sql
persistence/sql/migrations/sql/20221220124639000000_errors_index.mysql.up.sql
persistence/sql/migrations/sql/20221220124639000000_errors_index.up.sql
persistence/sql/persister_courier.go

https://cockroachdb.github.io/distsqlplan/decode.html#eJyUU91OGz0Qvf-eYjT6LkAyZH8SCishpU2DCH9BIaIXVRQ560mwsmsvtrckQjxWX6BPVu1uoGQJtLn0mTnj43PGj2jvE4zwa_eiO-zCyaB_Cdosx3PDnbb7ityDNnMLn29eweMX-Ntpd9AFKeAY_veRodKCrnhKFqPveIQjhpnRMVmrTQE9lg09scDIYyhVlrsCHjGMtSGMHtFJlxBGOOSThAbEBZmGhwwFOS6TcqylZGrJ_JAxjckYbWz7LTRWUoylWCDDjk7yVNkIpGCgpECGNxkvgD1keH4LTqYUQauZ2uoca-VIOanVquT9-rkqGf1gwRAXERyy4Miv0MnS0TPcCltwLr9UhdngugMxTxIbQdF7edvpgHWUQaxz5WCHFq4hldstxjVDv3HIms3gpZFo_rYxbITIMOULSCnVZgk8SXTMHYkIDgJvdfmEu_iOLOjcZbmL4AgZluKfgUr-6IlhhaxysI7PCCP_if17VsX1CdiYK5jk0ykZ8Br-ema0oDh_5agfVpbWZfp1me9LDN6V-EdZrrQRZEisqRkVzL-1bHjnKbd3Z1oqMo1g_XnDZUYRXHRPhnDTvezBWb93hQwTmrqddrB7bOTszu20_V1k2C-e1fZZu5jxxpeDg8qYzfm2nuMtyvY-AUdpBkLaOeSWz4pVhU3pe3VbvXdtDbdPvlpRv9zLDzLfa4X7n8Iw3ZT7FgKb2wgckM20slTPf-NkrwidxIyqJbI6NzFdGx …

fix: add missing indexes

---

session/error.go
session/handler.go

feat: improve error message when no session is found

---

selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=mfa-case=webauthn_payload_is_set_when_identity_has_webauthn.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=passwordless-case=should_fail_if_webauthn_login_is_invalid-type=browser.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=passwordless-case=should_fail_if_webauthn_login_is_invalid-type=spa.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-case=mfa_v0_credentials-passwordless_enabled=false#01-browser.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-case=mfa_v0_credentials-passwordless_enabled=false#01-spa.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-case=mfa_v0_credentials-passwordless_enabled=false#02-browser.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-case=mfa_v0_credentials-passwordless_enabled=false#02-spa.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-case=mfa_v0_credentials-passwordless_enabled=false-browser.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-case=mfa_v0_credentials-passwordless_enabled=false-spa.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-case=mfa_v0_credentials-passwordless_enabled=true#01-browser.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-case=mfa_v0_credentials-passwordless_enabled=true#01-spa.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-case=mfa_v0_credentials-passwordless_enabled=true#02-browser.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-case=mfa_v0_credentials-passwordless_enabled=true#02-spa.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-case=mfa_v0_credentials-passwordless_enabled=true-browser.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-case=mfa_v0_credentials-passwordless_enabled=true-spa.json
selfservice/strategy/webauthn/.snapshots/TestCompleteSettings-case=a_device_is_shown_which_can_be_unlinked.json
selfservice/strategy/webauthn/.snapshots/TestCompleteSettings-case=one_activation_element_is_shown.json
selfservice/strategy/webauthn/.snapshots/TestRegistration-case=webauthn_button_exists-browser.json
selfservice/strategy/webauthn/.snapshots/TestRegistration-case=webauthn_button_exists-spa.json

test: update integrity snapshots

---

.github/workflows/cve-scan.yaml
identity/test/pool.go

test: improve parallelization

---

.orycli.yml

chore: unset email and name after release hook

---

selfservice/strategy/oidc/provider_patreon.go

fix: handle upstream errors in patreon provider

---

embedx/config.schema.json
hydra/hydra.go
persistence/sql/persister_identity.go
selfservice/hook/.snapshots/TestWebHooks-update_identity_fields-case=update_identity_fields-case=body_is_empty.json
selfservice/hook/.snapshots/TestWebHooks-update_identity_fields-case=update_identity_fields-case=identity_has_updated_admin_metadata.json
selfservice/hook/.snapshots/TestWebHooks-update_identity_fields-case=update_identity_fields-case=identity_has_updated_public_metadata.json
selfservice/hook/.snapshots/TestWebHooks-update_identity_fields-case=update_identity_fields-case=identity_has_updated_recovery_addresses.json
selfservice/hook/.snapshots/TestWebHooks-update_identity_fields-case=update_identity_fields-case=identity_has_updated_state.json
selfservice/hook/.snapshots/TestWebHooks-update_identity_fields-case=update_identity_fields-case=identity_has_updated_traits.json
selfservice/hook/.snapshots/TestWebHooks-update_identity_fields-case=update_identity_fields-case=identity_has_updated_verified_addresses.json
selfservice/hook/.snapshots/TestWebHooks-update_identity_fields-case=update_identity_fields-case=identity_is_present_but_empty#01.json
selfservice/hook/.snapshots/TestWebHooks-update_identity_fields-case=update_identity_fields-case=identity_is_present_but_empty.json
selfservice/hook/web_hook.go
selfservice/hook/web_hook_integration_test.go
test/e2e/cypress/integration/profiles/webhoooks/registration/success.spec.ts
test/e2e/cypress/support/commands.ts
test/e2e/cypress/support/index.d.ts
test/e2e/mock/webhook/main.go
test/e2e/package-lock.json
test/e2e/package.json
test/e2e/profiles/webhooks/identity.traits.schema.json
test/e2e/profiles/webhooks/webhook_body.jsonnet
x/coalesce.go

Introducing a new configuration `response.parse` in webhooks. This enables updating of identity data during registration, including admin/public metadata, identity traits, enabling/disabling identity, and modifying verified/recovery addresses.
Closes #2161
the changes.
works.

feat: webhooks that update identities

---

.github/workflows/ci.yaml

chore: update GHA versions

---

driver/config/config.go
driver/config/config_test.go
internal/testhelpers/fake.go
selfservice/strategy/code/strategy_recovery.go
selfservice/strategy/code/strategy_recovery_test.go
selfservice/strategy/link/strategy_recovery.go
selfservice/strategy/link/strategy_recovery_test.go
x/http_secure_redirect.go

Fixes https://github.com/ory-corp/cloud/issues/1405
the changes.
works.

fix: respect the after recovery return to URL from config

---

persistence/sql/migrations/sql/20230322144139000001_missing_login_index.down.sql
persistence/sql/migrations/sql/20230322144139000001_missing_login_index.mysql.down.sql
persistence/sql/migrations/sql/20230322144139000001_missing_login_index.up.sql

fix: add missing index

---

go.mod
go.sum
identity/handler.go
identity/handler_test.go

revert: "fix: do not omit last page on identity list"

---

selfservice/strategy/oidc/.snapshots/TestSettingsStrategy-suite=unlink-case=should_not_be_able_to_unlink_an_non-existing_connection-flow=fetch.json
selfservice/strategy/oidc/.snapshots/TestSettingsStrategy-suite=unlink-case=should_not_be_able_to_unlink_an_non-existing_connection-flow=json.json
selfservice/strategy/oidc/strategy_settings.go
selfservice/strategy/oidc/strategy_settings_test.go
test/e2e/cypress/integration/profiles/oidc/login/success.spec.ts
test/e2e/cypress/integration/profiles/oidc/settings/success.spec.ts
test/e2e/run.sh

[ory-corp/cloud#3514](https://github.com/ory-corp/cloud/issues/3514)
the changes.
works.

fix: account settings broken on OIDC removal

---

selfservice/strategy/oidc/provider_auth0.go
selfservice/strategy/oidc/provider_gitlab.go
selfservice/strategy/oidc/provider_netid.go

Closes https://github.com/ory/kratos/issues/3182
Closes https://github.com/ory/kratos/issues/3040
the changes.
works.

fix: missing issuer regression in OIDC

---

.github/workflows/pm.yml

chore: don't run pm workflow on forks

---

cmd/daemon/serve.go

fix: sqa config values unified across projects

---

x/http_secure_redirect.go
x/http_secure_redirect_test.go

chore: minor improvements around secure redirect helpers

---

identity/manager.go

fix: IdentityCreated event

---

cmd/identities/list_test.go
go.mod
go.sum
identity/handler_test.go
persistence/sql/identity/persister_identity.go

Resolves a pesky issue that would skip the last page.
the changes.
works.

fix: identity list pagination

---

embedx/config.schema.json

fix: do not require items to be unique

---

identity/handler.go
internal/client-go/api_identity.go
internal/httpclient/api_identity.go
spec/api.json
spec/swagger.json

Fixes #3346
the changes.
works.

fix: Return the updated identity as described in the API spec

---

.docker/Dockerfile-alpine
.docker/Dockerfile-build
.docker/Dockerfile-distroless-static
.goreleaser.yml

feat: add distroless and static images

---

persistence/sql/identity/persister_identity.go
session/handler_test.go
session/stub/identity.schema.json

fix: incorrect override in identity hydrate

---

internal/client-go/api_frontend.go
internal/httpclient/api_frontend.go
session/handler.go

chore: fix typo

---

hash/hash_comparator.go
hash/hasher_argon2.go
hash/hasher_bcrypt.go
hash/hasher_pbkdf2.go

feat: add OpenTelemetry span for password hash comparison

---

selfservice/flow/login/handler.go
selfservice/flow/registration/handler.go

See https://github.com/ory/kratos/discussions/3388
the changes.
works.

docs: remove experimental warnings

---

test/e2e/cypress/helpers/express.ts
test/e2e/cypress/integration/profiles/email/logout/success.spec.ts

Related PR https://github.com/ory/kratos-selfservice-ui-node/pull/274
the changes.
works.

test: logout return_to

---

selfservice/flow/registration/handler.go
selfservice/strategy/oidc/strategy_helper_test.go
selfservice/strategy/oidc/strategy_login.go
selfservice/strategy/oidc/strategy_test.go

Fixes https://github.com/ory/kratos/issues/3321
the changes.
works.

fix: carry `oauth2_login_challenge` over to registration flow

---

.github/CODEOWNERS

chore: add hperl as codeowner

---

persistence/sql/persister_errorx.go
selfservice/strategy/oidc/strategy.go

Fixes missing tracing during code exchange in the OIDC strategy. Example trace: 0000000000000000641685d32e9a7f07
the changes.
works.

chore: add missing tracing & attributes in oidc strategy

---

driver/config/config_test.go

The comment triggered ORY Closed Reference Notifier GitHub action. However, this is not relevant anymore.
Resolve: #2630
#2630
- [ x I have referenced an issue containing the design document if my change
- [ x I am following the
the changes.
works.

fix: remove comment because the upstream issue has been fixed

---

session/manager_http.go

fix: pass context

---

.docker/Dockerfile-alpine

chore: update Dockerfile-alpine

---

cmd/clidoc/main.go
hash/hasher_bcrypt.go
schema/errors.go
selfservice/flow/recovery/.snapshots/TestHandleError-flow=api-case=fails_if_active_strategy_is_disabled.json
selfservice/flow/recovery/.snapshots/TestHandleError-flow=spa-case=fails_if_active_strategy_is_disabled.json
selfservice/strategy/password/registration.go
selfservice/strategy/password/settings_test.go
selfservice/strategy/password/validator.go
selfservice/strategy/password/validator_test.go
selfservice/strategy/webauthn/.snapshots/TestCompleteSettings-case=fails_to_remove_security_key_if_it_is_passwordless_and_the_last_credential_available-type=browser-response.json
selfservice/strategy/webauthn/.snapshots/TestCompleteSettings-case=fails_to_remove_security_key_if_it_is_passwordless_and_the_last_credential_available-type=spa-response.json
test/e2e/cypress/integration/profiles/email/registration/errors.spec.ts
test/e2e/cypress/integration/profiles/email/settings/errors.spec.ts
test/e2e/cypress/integration/profiles/email/settings/success.spec.ts
test/e2e/cypress/support/commands.ts
text/id.go
text/message.go
text/message_login.go
text/message_recovery.go
text/message_registration.go
text/message_settings.go
text/message_validation.go
text/message_verification.go
text/type.go
ui/container/container.go
ui/container/container_test.go

Some messages are now split into new messages with more details.

feat: improve messages for easier i18n

---

.github/workflows/ci.yaml
test/e2e/cypress/integration/profiles/email/login/ui.spec.ts
test/e2e/cypress/integration/profiles/email/settings/ui.spec.ts
test/e2e/cypress/integration/profiles/mfa/totp.spec.ts
test/e2e/cypress/integration/profiles/oidc/settings/success.spec.ts
test/e2e/cypress/integration/profiles/recovery/code/errors.spec.ts
test/e2e/cypress/integration/profiles/recovery/code/success.spec.ts
test/e2e/cypress/integration/profiles/recovery/link/errors.spec.ts
test/e2e/cypress/integration/profiles/recovery/link/success.spec.ts
test/e2e/cypress/integration/profiles/recovery/return-to/success.spec.ts
test/e2e/cypress/integration/profiles/recovery/settings/success.spec.ts
test/e2e/cypress/integration/profiles/verification/login/errors.spec.ts
test/e2e/cypress/integration/profiles/verification/login/success.spec.ts
test/e2e/cypress/integration/profiles/verification/registration/errors.spec.ts
test/e2e/cypress/integration/profiles/verification/registration/success.spec.ts
test/e2e/cypress/integration/profiles/verification/settings/error.spec.ts
test/e2e/cypress/integration/profiles/verification/verify/errors.spec.ts
test/e2e/cypress/integration/profiles/verification/verify/success.spec.ts
test/e2e/cypress/support/commands.ts
test/e2e/cypress/support/configHelpers.ts
test/e2e/cypress/support/index.d.ts
test/e2e/run.sh

A few test changed a lot of config values and waited for the whole config update in beforeEachs which could take a few seconds per test. This added up. This PR changes it, so that these tests update the config just once or twice during their runtime. 
Also fixes the broken tests.
the changes.
works.

chore: speed up e2e tests

---

identity/handler.go

Update link to hashed password formats docs.
[Docs #1529](https://github.com/ory/docs/pull/1529)
the changes.
works.

chore: update link to hashed password formats

---

schema/handler.go
schema/handler_test.go

fix: use registry client for schema loading

---

selfservice/strategy/code/strategy_login.go
selfservice/strategy/code/strategy_login_test.go
selfservice/strategy/code/strategy_registration.go
selfservice/strategy/code/strategy_registration_test.go
selfservice/strategy/code/stub/code.identity.schema.json
test/e2e/cypress/integration/profiles/code/login/error.spec.ts
test/e2e/cypress/integration/profiles/code/login/success.spec.ts
test/e2e/cypress/integration/profiles/code/registration/error.spec.ts
test/e2e/cypress/integration/profiles/code/registration/success.spec.ts
test/e2e/cypress/integration/profiles/email/login/ui.spec.ts
test/e2e/cypress/integration/profiles/email/settings/ui.spec.ts
test/e2e/cypress/integration/profiles/mfa/totp.spec.ts
test/e2e/profiles/code/identity.traits.schema.json

This PR fixes:
1. 2FA incorrectly populates code method group
2. Registration type assertion on identity schema containing traits other than strings.
https://github.com/ory-corp/cloud/issues/5280
the changes.
works.

fix: code method on registration and 2fa

---

driver/config/config.go
go.mod
go.sum

I am actually not sure if it fixes the concurrent map read-write, as I could not reproduce it locally. The changes however seem reasonable.

fix: do not encode full config in multiple places

---

go.mod
go.sum

Contains the updated event geolocation attributes.
CC @mszekiel 
the changes.
works.

chore: upgrade ory/x to v0.0.589

---

test/e2e/package-lock.json
test/e2e/package.json
test/e2e/run.sh

chore: allow node 18

---

.docker/Dockerfile-build
.docker/Dockerfile-debug
.docker/Dockerfile-distroless-static

Should make the image scanners happy.
the changes.
works.

chore: update docker base images

---

embedx/config.schema.json

Adds more hooks to the post-settings flow for methods totp, webauthn, lookup_secret.
the changes.
works.

feat: enable hooks for totp, webauthn, lookup_secret

---

test/e2e/cypress.config.ts
test/e2e/run.sh

See https://github.com/cypress-io/cypress/issues/27804
Upgrading turned out to be a bigger effort, as there were a bunch of breaking changes.

test: fix cypress setup

---

cmd/daemon/serve.go

...as this can lead to race conditions. We should in fact get rid of most "JIT" initialization in the registry, and where it makes sense at least add a lock or `sync.Once`.

fix: do not initialize parts of the registry in parallel

---

selfservice/flow/login/handler.go

fix: use org ID from session if available in login flow

---

selfservice/strategy/oidc/provider_apple.go
selfservice/strategy/oidc/provider_apple_test.go

Closes #3551
the changes.
works.

fix: using first name as last name

---

selfservice/hook/.snapshots/TestWebHooks-update_identity_fields-case=update_identity_fields-case=identity_has_updated_admin_metadata.json
selfservice/hook/web_hook.go
selfservice/hook/web_hook_integration_test.go

fix: allow updating admin metadata from webhook responses

---

driver/config/config.go
driver/config/config_test.go
embedx/config.schema.json
identity/pool.go
identity/test/pool.go
persistence/sql/identity/persister_identity.go
selfservice/strategy/code/strategy_login.go
selfservice/strategy/code/strategy_login_test.go
test/e2e/cypress/integration/profiles/code/login/error.spec.ts
test/e2e/cypress/integration/profiles/code/login/success.spec.ts
test/e2e/cypress/integration/profiles/code/registration/error.spec.ts
test/e2e/cypress/integration/profiles/code/registration/success.spec.ts
test/e2e/profiles/code/.kratos.yml

Should be able to login with the `code` credential even if the user did not register on the `code` credential. 
Only `identifier` matching is done and validation based on the identity schema.
the changes.
works.

feat: login with code on any credential type

---

embedx/config.schema.json
test/e2e/playwright/setup/default_config.ts

fix: add max-age to default cors headers

---

Makefile
script/add-down-migrations.sh
script/debug-entrypoint.sh
script/test-envs.sh
script/testenv.sh
test/e2e/run.sh

Signed-off-by: nxy7 <lolnoxy@gmail.com>
Not every linux distribution has /bin/bash. One of examples of such distros is NixOS which only has /bin/sh.
Fix to that is pretty easy, instead of linking to /bin/bash we can use /usr/bin/env bash which will find correct bash path.
Other way to solve it would be using /bin/sh (some distros have it linked to bash anyway).
If I'm not mistaken this is non breaking change and shouldn't affect anyone negatively.
the changes.
works.

fix: change shebangs and makefile from /bin/bash to /usr/bin/env bash

---

courier/courier.go
courier/courier_dispatcher.go
courier/courier_dispatcher_test.go
courier/smtp.go

fix: respect gomail.SendError in mail queue

---

selfservice/strategy/code/code_sender.go
selfservice/strategy/link/sender.go

Found in https://github.com/ory/kratos/discussions/2822
the changes.
works.

chore: fix email address in courier log line

---

identity/handler.go
identity/handler_test.go
identity/pool.go
identity/test/pool.go
persistence/sql/identity/persister_identity.go

Signed-off-by: nxy7 <lolnoxy@gmail.com>
test for filder ids added
Signed-off-by: nxy7 <lolnoxy@gmail.com>
Right now if you want to get many idendities you have to get them one by one. This change allows to filter `/admin/identities` by id
with the following syntax `/admin/identities?ids=id1&ids=id2&ids=id3`. This way we make less requests, decrease latency and bandwith used by apps
interacting with kratos. 
fixes: #2448
the changes.
works.
Before adding documentation to ory/docs I'd like to …

feat: batch list identities

---

embedx/config.schema.json

fix: additional_id_token_audiences key in config schema

---

contrib/quickstart/kratos/email-password/kratos.yml

Adds the ability to complete the recovery flow properly on API flows. This PR also streamlines the behavior for SPA flows to not return 422 errors anymore. To enable this new behavior, set the features.use_continue_with_transitions flag in the config to `true`.
See also https://github.com/ory/kratos/pull/3273
the changes.
works.

feat: add support for native recovery

---

selfservice/strategy/oidc/strategy_settings.go
selfservice/strategy/oidc/strategy_settings_test.go

fix: don't list org SSOs in settings

---

selfservice/strategy/code/strategy_recovery.go

fix: panic in recovery

---

x/http_secure_redirect.go

Before:
After:
the changes.
works.

chore: pretty print allowed redirect URLs in error

---

selfservice/strategy/oidc/strategy.go

fix: use provider label in link message

---

identity/handler.go

Closes #3676 #3675
the changes.
works.

fix: incorrect swagger spec for filter parameter

---

selfservice/strategy/code/strategy_recovery.go
selfservice/strategy/code/strategy_recovery_test.go

fix: do not generate CSRF token for api flows

---

internal/client-go/go.sum
selfservice/strategy/code/strategy_recovery.go

Closes #3705
the changes.
works.

fix: csrf token regenerate on browser flows

---

selfservice/strategy/code/strategy_verification_test.go
selfservice/strategy/link/strategy_verification_test.go

Resolves https://github.com/ory-corp/cloud/issues/5633
the changes.
works.

test: expand test suite for verification + OAuth challenge

---

identity/handler_test.go
identity/test/pool.go
internal/client-go/go.sum
persistence/sql/identity/persister_identity.go

Fixes https://github.com/ory/kratos/issues/3333
the changes.
works.

feat: list by OIDC cred

---

.github/workflows/ci.yaml
selfservice/strategy/oidc/strategy_helper_test.go
selfservice/strategy/password/op_helpers_test.go

chore: fix tests on master

---

selfservice/strategy/oidc/provider_generic_oidc.go

fix: set issuer in userinfo claims if missing

---

internal/testhelpers/config.go
selfservice/strategy/code/strategy_login.go
selfservice/strategy/code/strategy_login_test.go

Removes the requirement to set the phone number as a code credential in the identity schema for MFA via SMS, as we already have the identity from the session in MFA flows and can use it from there.
the changes.
works.

fix: don't require code credential for MFA flows

---

courier/smtp.go
courier/smtp_test.go

fix: prevent SMTP URL leak on unparsable URL

---

internal/client-go/go.sum
persistence/sql/migrations/sql/20240214113828000000_courier_dispatch_indices.down.sql
persistence/sql/migrations/sql/20240214113828000000_courier_dispatch_indices.mysql.down.sql
persistence/sql/migrations/sql/20240214113828000000_courier_dispatch_indices.mysql.up.sql
persistence/sql/migrations/sql/20240214113828000000_courier_dispatch_indices.up.sql

fix: add missing indexes and remove unused index

---

selfservice/flow/registration/hook.go
selfservice/hook/session_issuer.go

This PR adds NewLoginSucceeded event to post registration hook 
the changes.
works.

fix: add login succeeded event to post registration hook

---

driver/config/config.go
driver/config/config_test.go
driver/config/stub/.kratos.courier.channels.yaml

fix: make sure emails can still be sent with SMS enabled

---

.schema/openapi/templates/go/api.mustache
cmd/daemon/serve.go
courier/smtp.go
driver/config/config.go
internal/client-go/api_courier.go
internal/client-go/api_frontend.go
internal/client-go/api_identity.go
internal/client-go/api_metadata.go
internal/httpclient/api_courier.go
internal/httpclient/api_frontend.go
internal/httpclient/api_identity.go
internal/httpclient/api_metadata.go
schema/handler.go
schema/schema.go
selfservice/strategy/oidc/error.go
selfservice/strategy/oidc/provider_auth0.go

fix: audit issues

---

.schemastore/config.schema.json
driver/config/config.go
embedx/config.schema.json
internal/client-go/go.sum
session/handler.go
session/handler_test.go

feat: control edge cache ttl

---

.schema/openapi/gen.go.yml
internal/client-go/model_continue_with.go
internal/client-go/model_ui_node_anchor_attributes.go
internal/client-go/model_ui_node_attributes.go
internal/client-go/model_ui_node_image_attributes.go
internal/client-go/model_ui_node_input_attributes.go
internal/client-go/model_ui_node_script_attributes.go
internal/client-go/model_ui_node_text_attributes.go
internal/client-go/model_update_login_flow_body.go
internal/client-go/model_update_recovery_flow_body.go
internal/client-go/model_update_registration_flow_body.go
internal/client-go/model_update_settings_flow_body.go
internal/client-go/model_update_verification_flow_body.go
internal/httpclient/model_continue_with.go
internal/httpclient/model_ui_node_anchor_attributes.go
internal/httpclient/model_ui_node_attributes.go
internal/httpclient/model_ui_node_image_attributes.go
internal/httpclient/model_ui_node_input_attributes.go
internal/httpclient/model_ui_node_script_attributes.go
internal/httpclient/model_ui_node_text_attributes.go
internal/httpclient/model_update_login_flow_body.go
internal/httpclient/model_update_recovery_flow_body.go
internal/httpclient/model_update_registration_flow_body.go
internal/httpclient/model_update_settings_flow_body.go
internal/httpclient/model_update_verification_flow_body.go
spec/api.json
spec/swagger.json
ui/node/attributes.go
ui/node/node.go

fix(sdk): improve discriminators for node and Go

---

session/handler.go

Closes #3842
the changes.
works.

fix: expand identity in session extension

---

.schema/openapi/patches/selfservice.yaml
internal/client-go/model_update_login_flow_body.go
internal/client-go/model_update_registration_flow_body.go
internal/client-go/model_update_settings_flow_body.go
internal/httpclient/model_update_login_flow_body.go
internal/httpclient/model_update_registration_flow_body.go
internal/httpclient/model_update_settings_flow_body.go
spec/api.json

fix: improve SDK discriminators

---

go.mod
go.sum
internal/client-go/go.sum

chore: upgrade ory/x to v0.0.619

---

selfservice/strategy/passkey/passkey_registration_test.go
selfservice/strategy/passkey/passkey_strategy.go
test/e2e/profiles/passkey/.kratos.yml

fix: don't treat passkeys as AAL2

---

driver/config/config_test.go
driver/config/stub/.kratos.webauthn.invalid.yaml
driver/config/stub/.kratos.webauthn.origin.yaml
driver/config/stub/.kratos.webauthn.origins.yaml
driver/config/stub/.kratos.yaml
driver/registry_default_test.go
embedx/config.schema.json

chore: add headers to web hook config

---

embedx/config.schema.json

(Actually) Closes https://github.com/ory/kratos/issues/3559 and closes https://github.com/ory/kratos/issues/3693
the changes.
works.

chore: don't require connection_uri in SMTP

---

selfservice/strategy/passkey/.schema/settings.schema.json
selfservice/strategy/passkey/passkey_settings.go

chore: don't require method to be  passkey in settings schema

---

internal/client-go/go.sum
internal/testhelpers/selfservice_verification.go
selfservice/strategy/code/strategy_verification.go
selfservice/strategy/code/strategy_verification_test.go
selfservice/strategy/link/strategy_verification.go
selfservice/strategy/link/strategy_verification_test.go

fix: use correct post-verification identity state in post-hooks

---

selfservice/strategy/oidc/provider_linkedin_v2.go

This fixes the linkedin provider, which now reports the correct issuer URL.
the changes.
works.

fix: linkedin issuer override

---

identity/handler.go
package-lock.json
session/handler.go
spec/api.json
spec/swagger.json

fix: enum type of session expandables

---

internal/testhelpers/selfservice_verification.go

close res body
the changes.
works.

fix: close res body

---

x/mailhog.go

chore: allow smtp jim config

---

test/e2e/package-lock.json
test/e2e/package.json
test/e2e/playwright/actions/generate.ts
test/e2e/playwright/actions/login.ts
test/e2e/playwright/actions/session.ts
test/e2e/playwright/fixtures/index.ts
test/e2e/playwright/lib/helper.ts
test/e2e/playwright/lib/request.ts
test/e2e/playwright/models/elements/login.ts
test/e2e/playwright/selectors/input.ts
test/e2e/playwright/tests/desktop/identifier_first/login.spec.ts
test/e2e/playwright/types/index.ts

test: improve login tests

---

CHANGELOG.md

The code uses `selfservice.flows.registration.enable_legacy_one_step` everywhere, so I believe `enable_legacy_flow` won't work.
To be changed in https://github.com/ory/kratos/releases/tag/v1.2.0 also :)
the changes.
works.

docs: typo in changelog

---

courier/courier_dispatcher.go
courier/smtp_channel.go

chore: improve courier logging

---

selfservice/flow/login/strategy_form_hydrator.go
selfservice/flow/login/strategy_form_hydrator_test.go
selfservice/strategy/code/strategy_login_test.go
selfservice/strategy/idfirst/strategy_login.go
selfservice/strategy/idfirst/strategy_login_test.go
selfservice/strategy/oidc/strategy_login_test.go
selfservice/strategy/passkey/passkey_login_test.go
selfservice/strategy/password/login_test.go
selfservice/strategy/webauthn/login_test.go

chore: re-add WithIdentifier

---

identity/.snapshots/TestHandler-case=should_be_able_to_import_users-with_password_migration_hook_enabled.json
identity/handler.go
identity/handler_import.go
identity/handler_test.go
internal/client-go/model_identity_with_credentials_password_config.go
internal/httpclient/model_identity_with_credentials_password_config.go
spec/api.json
spec/swagger.json

This fixes a bug where the `/admin/identities` handler did not correctly handle `use_password_migration_hook` in the password credentials payload.
the changes.
works.

fix: pw migration param

---

selfservice/flow/login/hook.go
selfservice/strategy/totp/.snapshots/TestCompleteLogin-case=totp_payload_is_set_when_identity_has_totp.json
selfservice/strategy/totp/login.go

fix: add continue with only for json browser requests

---

driver/config/config.go
internal/client-go/go.sum
request/builder.go
selfservice/strategy/password/login_test.go

fix: password migration hook config

---

cmd/clidoc/main.go

fix: typo in login link CLI error messages

---

.schemastore/config.schema.json
embedx/config.schema.json
selfservice/strategy/oidc/provider_config.go
selfservice/strategy/oidc/provider_salesforce.go
selfservice/strategy/oidc/provider_salesforce_unit_test.go
selfservice/strategy/oidc/provider_userinfo_test.go
test/e2e/shared/config.d.ts

Support for sign-in with Salesforce.
Resolves #3984
the changes.
works.
This mirrors what has been done for Auth0 which uses the same format for `updated_at`.

feat: add support for Salesforce as identity provider

---

.github/workflows/codeql-analysis.yml

Upgrades Code QL GitHub Action to v2.
the changes.
works.
https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/

ci: update Code QL action to v2

---

selfservice/strategy/oidc/provider_salesforce_unit_test.go
selfservice/strategy/oidc/provider_userinfo_test.go

Fixes invalid Salesforce tests due to remaining mentions of Auth0.
follow up to #4003
the changes.
works.

test: update incorrect usage of Auth0 in Salesforce tests

---

selfservice/strategy/oidc/strategy.go
selfservice/strategy/oidc/strategy_login.go
selfservice/strategy/oidc/strategy_registration.go
selfservice/strategy/oidc/strategy_test.go

fix: trigger oidc web hook on sign in after registration

---

go.mod
go.sum

chore: upgrade dockertest to address cve

---

go.mod
go.sum
identity/.snapshots/TestUpgradeCredentials-type=code-from=v0_with_correct_value.json
identity/.snapshots/TestUpgradeCredentials-type=code-from=v0_with_email_empty_space_value-with_one_identifier.json
identity/.snapshots/TestUpgradeCredentials-type=code-from=v0_with_email_empty_space_value-with_two_identifiers.json
identity/.snapshots/TestUpgradeCredentials-type=code-from=v0_with_empty_value.json
identity/.snapshots/TestUpgradeCredentials-type=code-from=v0_with_unknown_value.json
identity/credentials.go
identity/credentials_migrate.go
identity/extension_credentials.go
identity/manager.go
internal/testhelpers/session.go
selfservice/strategy/code/strategy_login.go
test/e2e/cypress/integration/profiles/code/login/error.spec.ts

test: resolve CI failures

---

cmd/clidoc/main.go
identity/manager.go
selfservice/strategy/oidc/.snapshots/TestStrategy-login-hints-enabled=false-case=should_fail_to_register_and_return_fresh_login_flow_if_email_is_already_being_used_by_oidc_credentials-case=should_fail_login.json
selfservice/strategy/oidc/.snapshots/TestStrategy-login-hints-enabled=false-case=should_fail_to_register_and_return_fresh_login_flow_if_email_is_already_being_used_by_oidc_credentials-case=should_fail_registration.json
selfservice/strategy/oidc/.snapshots/TestStrategy-login-hints-enabled=false-case=should_fail_to_register_and_return_fresh_login_flow_if_email_is_already_being_used_by_oidc_credentials-case=should_fail_registration_id_first_strategy_enabled.json
selfservice/strategy/oidc/.snapshots/TestStrategy-login-hints-enabled=false-case=should_fail_to_register_and_return_fresh_login_flow_if_email_is_already_being_used_by_password_credentials-case=should_fail_login.json
selfservice/strategy/oidc/.snapshots/TestStrategy-login-hints-enabled=false-case=should_fail_to_register_and_return_fresh_login_flow_if_email_is_already_being_used_by_password_credentials-case=should_fail_registration.json
selfservice/strategy/oidc/.snapshots/TestStrategy-login-hints-enabled=false-case=should_fail_to_register_and_return_fresh_login_flow_if_email_is_already_being_used_by_password_credentials-case=should_fail_registration_id_first_strategy_enabled.json
selfservice/strategy/oidc/.snapshots/TestStrategy-login-hints-enabled=true-case=should_fail_to_register_and_return_fresh_login_flow_if_email_is_already_being_used_by_oidc_credentials-case=should_fail_login.json
selfservice/strategy/oidc/.snapshots/TestStrategy-login-hints-enabled=true-case=should_fail_to_register_and_return_fresh_login_flow_if_email_is_already_being_used_by_oidc_credentials-case=should_fail_registration.json
selfservice/strategy/oidc/.snapshots/TestStrategy-login-hints-enabled=true-case=should_fail_to_register_and_return_fresh_login_flow_if_email_is_already_being_used_by_oidc_credentials-case=should_fail_registration_id_first_strategy_enabled.json
selfservice/strategy/oidc/.snapshots/TestStrategy-login-hints-enabled=true-case=should_fail_to_register_and_return_fresh_login_flow_if_email_is_already_being_used_by_password_credentials-case=should_fail_login.json
selfservice/strategy/oidc/.snapshots/TestStrategy-login-hints-enabled=true-case=should_fail_to_register_and_return_fresh_login_flow_if_email_is_already_being_used_by_password_credentials-case=should_fail_registration.json
selfservice/strategy/oidc/.snapshots/TestStrategy-login-hints-enabled=true-case=should_fail_to_register_and_return_fresh_login_flow_if_email_is_already_being_used_by_password_credentials-case=should_fail_registration_id_first_strategy_enabled.json
selfservice/strategy/oidc/strategy.go
selfservice/strategy/oidc/strategy_test.go
text/message_login.go

fix: include duplicate credentials in account linking message

---

embedx/config.schema.json

fix: add PKCE config key to config schema

---

cipher/aes.go
cipher/chacha20.go
cipher/cipher.go
cipher/cipher_test.go
cipher/noop.go
driver/config/config.go
driver/registry_default.go
identity/identity_test.go

Towards https://github.com/ory-corp/cloud/issues/6613

chore: refactor API in package cipher for easier dependency injection

---

.goreleaser.yml

chore: upgrade goreleaser to v2

---

identity/.snapshots/TestSchemaExtensionCredentials-case=13.json
identity/extension_credentials_test.go
identity/stub/extension/credentials/email.schema.json

test: additional code credential test case

---

persistence/sql/identity/persister_identity.go

fix: truncate updated at

---

selfservice/strategy/passkey/.snapshots/TestCompleteLogin-flow=passwordless-case=passkey_button_exists.json
selfservice/strategy/passkey/.snapshots/TestCompleteLogin-flow=refresh-case=refresh_passwordless_credentials-browser.json
selfservice/strategy/passkey/.snapshots/TestCompleteLogin-flow=refresh-case=refresh_passwordless_credentials-spa.json
selfservice/strategy/passkey/.snapshots/TestCompleteSettings-case=a_device_is_shown_which_can_be_unlinked.json
selfservice/strategy/passkey/.snapshots/TestCompleteSettings-case=one_activation_element_is_shown.json
selfservice/strategy/passkey/.snapshots/TestFormHydration-method=PopulateLoginMethodFirstFactor.json
selfservice/strategy/passkey/.snapshots/TestFormHydration-method=PopulateLoginMethodFirstFactorRefresh.json
selfservice/strategy/passkey/.snapshots/TestFormHydration-method=PopulateLoginMethodIdentifierFirstIdentification.json
selfservice/strategy/passkey/.snapshots/TestRegistration-case=passkey_button_exists-browser.json
selfservice/strategy/passkey/.snapshots/TestRegistration-case=passkey_button_exists-spa.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=mfa-case=webauthn_payload_is_set_when_identity_has_webauthn.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=passwordless-case=should_fail_if_webauthn_login_is_invalid-type=browser.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=passwordless-case=should_fail_if_webauthn_login_is_invalid-type=spa.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-passwordless_enabled=false-case=mfa_v0_credentials-browser.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-passwordless_enabled=false-case=mfa_v0_credentials-spa.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-passwordless_enabled=false-case=mfa_v1_credentials-browser.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-passwordless_enabled=false-case=mfa_v1_credentials-spa.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-passwordless_enabled=true-case=passwordless_credentials-browser.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-passwordless_enabled=true-case=passwordless_credentials-spa.json
selfservice/strategy/webauthn/.snapshots/TestCompleteSettings-case=a_device_is_shown_which_can_be_unlinked.json
selfservice/strategy/webauthn/.snapshots/TestCompleteSettings-case=one_activation_element_is_shown.json
selfservice/strategy/webauthn/.snapshots/TestFormHydration-method=PopulateLoginMethodRefresh-case=mfa_enabled_and_user_has_mfa_credentials.json
selfservice/strategy/webauthn/.snapshots/TestFormHydration-method=PopulateLoginMethodRefresh-case=passwordless_enabled_and_user_has_passwordless_credentials.json
selfservice/strategy/webauthn/.snapshots/TestFormHydration-method=PopulateLoginMethodSecondFactor-case=mfa_enabled.json
selfservice/strategy/webauthn/.snapshots/TestRegistration-case=webauthn_button_exists-browser.json
selfservice/strategy/webauthn/.snapshots/TestRegistration-case=webauthn_button_exists-spa.json

test: update snapshots

---

internal/client-go/go.sum
persistence/sql/migrations/sql/20241029102200000001_self_service.down.sql
persistence/sql/migrations/sql/20241029102200000001_self_service.mysql.down.sql
persistence/sql/migrations/sql/20241029102200000001_self_service.mysql.up.sql
persistence/sql/migrations/sql/20241029102200000001_self_service.up.sql

https://github.com/ory-corp/cloud/issues/7199
the changes.
works.

feat: improve secondary indices for self service tables

---

persistence/sql/migrations/sql/20241108105000000001_index_cleanup.autocommit.down.sql
persistence/sql/migrations/sql/20241108105000000001_index_cleanup.autocommit.up.sql
persistence/sql/migrations/sql/20241108105000000001_index_cleanup.mysql.autocommit.down.sql
persistence/sql/migrations/sql/20241108105000000001_index_cleanup.mysql.autocommit.up.sql

feat: drop unused indices post index migration

---

internal/client-go/go.sum
persistence/sql/identity/persister_identity.go

fix: incorrect query plan

---

internal/client-go/go.sum
selfservice/strategy/passkey/.snapshots/TestCompleteLogin-flow=passwordless-case=passkey_button_exists.json
selfservice/strategy/passkey/.snapshots/TestCompleteLogin-flow=refresh-case=refresh_passwordless_credentials-browser.json
selfservice/strategy/passkey/.snapshots/TestCompleteLogin-flow=refresh-case=refresh_passwordless_credentials-spa.json
selfservice/strategy/passkey/.snapshots/TestCompleteSettings-case=a_device_is_shown_which_can_be_unlinked.json
selfservice/strategy/passkey/.snapshots/TestCompleteSettings-case=one_activation_element_is_shown.json
selfservice/strategy/passkey/.snapshots/TestFormHydration-method=PopulateLoginMethodFirstFactor.json
selfservice/strategy/passkey/.snapshots/TestFormHydration-method=PopulateLoginMethodFirstFactorRefresh.json
selfservice/strategy/passkey/.snapshots/TestFormHydration-method=PopulateLoginMethodIdentifierFirstIdentification.json
selfservice/strategy/passkey/.snapshots/TestRegistration-case=passkey_button_exists-browser.json
selfservice/strategy/passkey/.snapshots/TestRegistration-case=passkey_button_exists-spa.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=mfa-case=webauthn_payload_is_set_when_identity_has_webauthn.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=passwordless-case=should_fail_if_webauthn_login_is_invalid-type=browser.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=passwordless-case=should_fail_if_webauthn_login_is_invalid-type=spa.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-passwordless_enabled=false-case=mfa_v0_credentials-browser.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-passwordless_enabled=false-case=mfa_v0_credentials-spa.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-passwordless_enabled=false-case=mfa_v1_credentials-browser.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-passwordless_enabled=false-case=mfa_v1_credentials-spa.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-passwordless_enabled=true-case=passwordless_credentials-browser.json
selfservice/strategy/webauthn/.snapshots/TestCompleteLogin-flow=refresh-case=passwordless-passwordless_enabled=true-case=passwordless_credentials-spa.json
selfservice/strategy/webauthn/.snapshots/TestCompleteSettings-case=a_device_is_shown_which_can_be_unlinked.json
selfservice/strategy/webauthn/.snapshots/TestCompleteSettings-case=one_activation_element_is_shown.json
selfservice/strategy/webauthn/.snapshots/TestFormHydration-method=PopulateLoginMethodRefresh-case=mfa_enabled_and_user_has_mfa_credentials.json
selfservice/strategy/webauthn/.snapshots/TestFormHydration-method=PopulateLoginMethodRefresh-case=passwordless_enabled_and_user_has_passwordless_credentials.json
selfservice/strategy/webauthn/.snapshots/TestFormHydration-method=PopulateLoginMethodSecondFactor-case=mfa_enabled.json
selfservice/strategy/webauthn/.snapshots/TestRegistration-case=webauthn_button_exists-browser.json
selfservice/strategy/webauthn/.snapshots/TestRegistration-case=webauthn_button_exists-spa.json
x/webauthnx/js/webauthn.js

docs: improve SecurityError error message for ory elements local

---

go.mod
go.sum

To fix a regression in the migrator on CRDB.

chore: bump ory/x

---

codecov.yml

chore(ci): adjust codecov config

---

internal/client-go/go.sum
internal/testhelpers/selfservice_verification.go
selfservice/strategy/code/strategy_recovery.go
selfservice/strategy/code/strategy_recovery_test.go
selfservice/strategy/link/strategy_recovery.go
selfservice/strategy/link/strategy_recovery_test.go

fix: send correct verification status in post-recovery hook

---

test/e2e/package-lock.json
test/e2e/package.json

chore: upgrade playwright

---

selfservice/hook/verification.go
selfservice/hook/verification_test.go

Closes https://github.com/ory/kratos/issues/3741
the changes.
works.

fix: add resend node to after registration verification flow

---

internal/client-go/model_ui_node.go
internal/httpclient/model_ui_node.go
spec/api.json
spec/swagger.json
ui/node/node.go

fix: add missing saml group

---

persistence/sql/identity/persister_identity.go

Ref https://support.cockroachlabs.com/hc/en-us/requests/25430

feat: index hint for CRDB when deleting identity credentials

---

session/handler.go
session/handler_test.go

Fixes #3671 by checking AAL on `/sessions` in the same way it's checked on `/sessions/whoami`
closes #3671
the changes.
works.

fix: check aal on sessions list endpoint

---

driver/config/config.go
embedx/config.schema.json

fix: schema key

---

selfservice/strategy/code/strategy_login.go
test/e2e/cypress/integration/profiles/code/login/error.spec.ts
test/e2e/cypress/integration/profiles/code/registration/error.spec.ts

fix: show code email in most error states

---

codecov.yml

ci: improve codecov config

---

embedx/config.schema.json

fix: rename b2b_sso hook

---

selfservice/strategy/oidc/types.go

fix: exclude orgs

---

.schema/openapi/patches/selfservice.yaml
internal/client-go/model_update_login_flow_body.go
internal/client-go/model_update_registration_flow_body.go
internal/client-go/model_update_settings_flow_body.go
internal/httpclient/model_update_login_flow_body.go
internal/httpclient/model_update_registration_flow_body.go
internal/httpclient/model_update_settings_flow_body.go
spec/api.json

fix: add missing submit group

---

internal/client-go/model_update_settings_flow_with_saml_method.go
internal/httpclient/model_update_settings_flow_with_saml_method.go
selfservice/strategy/saml/settings.go
spec/api.json
spec/swagger.json

fix: add missing csrf_token

---

ui/node/.snapshots/TestNodeMarshalJSON-anchor_node.json
ui/node/.snapshots/TestNodeMarshalJSON-division_node.json
ui/node/.snapshots/TestNodeMarshalJSON-empty_type_inferred_from_attributes.json
ui/node/.snapshots/TestNodeMarshalJSON-image_node.json
ui/node/.snapshots/TestNodeMarshalJSON-input_node.json
ui/node/.snapshots/TestNodeMarshalJSON-script_node.json
ui/node/.snapshots/TestNodeMarshalJSON-text_node.json
ui/node/node.go
ui/node/node_test.go

fix: div decoding

---

.schema/openapi/patches/schema.yaml
internal/client-go/model_ui_node_attributes.go
internal/httpclient/model_ui_node_attributes.go
spec/api.json

fix: add missing discriminator

---

selfservice/strategy/oidc/strategy_settings.go

fix: settings linking error override

---

selfservice/strategy/oidc/fedcm/definitions.go

fix: add transient payload to fedcm

---

x/events/events.go

chore: update error event name

---

courier/http_channel.go
courier/http_test.go
courier/stub/request.config.mailer.jsonnet
courier/template/courier/builtin/templates/test_stub/email.body.gotmpl
courier/template/email/stub.go

feat: add HTML email support to HTTP channel
fixes #4350
the changes.
works.

feat: add HTML email support to HTTP channel

---

internal/client-go/model_ui_node_input_attributes.go
internal/httpclient/model_ui_node_input_attributes.go
selfservice/strategy/idfirst/strategy_login.go
selfservice/strategy/passkey/passkey_login.go
selfservice/strategy/webauthn/login.go
spec/api.json
spec/swagger.json
ui/node/attributes.go

fix(sdk): add missing enum type to autocomplete

---

identity/handler.go
identity/handler_test.go

feat: improve identity import limits
